### PR TITLE
Changes to the logging formats

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
1. Added milliseconds everywhere
2. Added a detailed subformat to be used in the files, containing also
   the thread name, filename, and function name.
3. Added a "hidden" configuration option to use the detailed format
   for stdout.
4. Removed some manual [action_finished] tags.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/518)

### CODE REVIEW

**Comment by giomasce** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/io/triggeredservice.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7Yd5x0nhN-KRI5sdGj:-K7Yd5x0nhN-KRI5sdGk:-847267419) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/io/triggeredservice.py#L5)):*
You did not change anything here but ok...

---

*[cms/log.py, line 259 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YfP5DUiSW-3seSl_y:-K7YfP5EbVWBwcWNd7tR:-328086145) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L259)):*
Can this actually happen? If I am not wrong, `coordinates` has always at least the service name and shard (or `None`, or whatever it is).

---

*[cms/log.py, line 284 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YebNyY3VjDQojiY5A:-K7YebNzx6gpE3aEhESZ:-458076653) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L284)):*
Nit picking: here I would use `<unknown>`. Referring to the Python `None` object is not really sensible for the user.

---

*[cms/log.py, line 287 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YhGLa3s-k-s8GojyL:-K7YhGLa3s-k-s8GojyM:1601393955) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L287)):*
Here I do not like very much that the coordinates and the operation are colored together. To me it is useful that they are distinct.

---

*[cms/log.py, line 312 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YflDXIkwOYZWUV2Ld:-K7YflDXIkwOYZWUV2Le:-1426081601) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L312)):*
Personal taste: I would leave `.py`. Do as you wish.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/518)*

**Comment by stefano-maggiolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/log.py, line 259 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YfP5DUiSW-3seSl_y:-K7YiWGmMjp2yrzE1n5Q:557543282) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L259)):*
It's just that with this class structure one might override get_coordinates and not do_format.

---

*[cms/log.py, line 284 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YebNyY3VjDQojiY5A:-K7YixNwabgYexFKO_rv:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L284)):*
Done.

---

*[cms/log.py, line 287 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YhGLa3s-k-s8GojyL:-K7YikR2wmJA6LvcCPtO:1187803898) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L287)):*
I would argue that we almost never use operation and (if I'm correct) never to track the same operation in different services...

---

*[cms/log.py, line 312 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YflDXIkwOYZWUV2Ld:-K7YjWtHCLZ1DLE5OkTQ:-425109018) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L312)):*
I prefer to remove everything that is non-informative, as lines are already pretty long. 

---

*[cms/io/triggeredservice.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7Yd5x0nhN-KRI5sdGj:-K7YhvRzamLNgYVbnEMX:-2072734692) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/io/triggeredservice.py#L5)):*
Ahah half-revert. Will fully-revert.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/518)*

**Comment by giomasce** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/log.py, line 287 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YhGLa3s-k-s8GojyL:-K7YldZGcyYofoF6g2yk:-1189727109) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L287)):*
But often we use it to track two consecutive operations on the same service. Well, in theory the two operations are uncorrelated, but I find really easier to follow operation boundaries when the color scheme is more distinctive. So please let me insist on this! :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/518)*

**Comment by stefano-maggiolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/log.py, line 287 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YhGLa3s-k-s8GojyL:-K7YmN2WRFzBm8gQ938C:210101320) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L287)):*
And since it's the same service and same operations, it will get the same color. But since you insist, I changed it. ;p

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/518)*

**Comment by giomasce** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cms/log.py, line 287 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/518#-K7YhGLa3s-k-s8GojyL:-K7YsBkwQbdUr5aVGhzS:-1819997766) ([raw file](https://github.com/cms-dev/cms/blob/9df38185f8281474fe21fc8fa78f3da0c7b51892/cms/log.py#L287)):*
No, the operation color changes between two operations! (moreover, with double colors the colorspace becomes much larger and there are many less clashes).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/518)*

**Pull request merged**
