### PR TITLE
Add bcrypt password hashing support for users

### PR DESCRIPTION
**Pull request by lerks**
Taken from #711.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/747)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[cms/db/user.py, line 76 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3f021r5-mnwmvUJ8X:-Ki3f021r5-mnwmvUJ8Y:b-3t2mal) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/db/user.py#L76)):*
> ```Python
>         Unicode,
>         nullable=False,
>         default=lambda: hash_password(generate_random_password(), "text"))
> ```

build_password (see later)

---

*[cms/server/admin/handlers/contestuser.py, line 229 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3g-rzwfCwi9_ZIqzk:-Ki3g-rzwfCwi9_ZIqzl:b-4hge2n) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/handlers/contestuser.py#L229)):*
> ```Python
>                 # must have meant to clear it.
>                 attrs["password"] = None
> ```

This code is quite convoluted, and I don't understand the second elif (why don't you look at the password itself? Why you have a conditional for the special value "text"? Could you make it more clear? Also it doesn't handle the ValueError (if for some reason the preexisting password was unparsable, you cannot change it).

---

*[cms/server/admin/handlers/user.py, line 84 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3geMDnDkcadWUVRhL:-Ki3geMDnDkcadWUVRhM:bbgid50) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/handlers/user.py#L84)):*
> ```Python
>                 # it untouched then we don't change it. Otherwise they
>                 # must have really meant to set an empty password.
>                 attrs["password"] = hash_password("", method)
> ```

Same here (also, common method)?

---

*[cms/server/admin/templates/add_user.html, line 43 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRgDLUIA21acfOWPnq:-KhRgDLVJcRl9KMlXEwk:br2lzn7) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/templates/add_user.html#L43)):*
> ```HTML
>           <select name="method">
>             <option value="text">Plain text</option>
>             <option value="bcrypt">Hashed (bcrypt)</option>
> ```

Selected as default

---

*[cms/server/admin/templates/user.html, line 119 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRg4yJ9tAQAEHvr2xH:-KhRg4yJ9tAQAEHvr2xI:b41lkg0) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/templates/user.html#L119)):*
> ```HTML
>           </script>
>           {% end %}
>         </td>
> ```

Can we factor this into a fragment shared by user & participation?

---

*[cmscommon/crypto.py, line 214 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRdr7MujCNf3TwG6mD:-KhRdr7MujCNf3TwG6mE:b-rlx6oz) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscommon/crypto.py#L214)):*
> ```Python
>         except ValueError:
>             return False
>     elif method == "text":
> ```

Maybe `plain`, `plaintext` or `unencrypted`? 

---

*[cmscontrib/AddParticipation.py, line 86 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRedUSwaHux_KxPIZ0:-KhRedUTKKEfuWrpyhE_:bg2klyt) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddParticipation.py#L86)):*
> ```Python
>                     # TODO make sure it's a valid bcrypt hash if method
>                     # is bcrypt.
>                     password = "%s:%s" % (method, password)
> ```

I'd add a `build_password` alongside `hash_password` to build the password from explicit values (so that the format is completely encapsulated and the todo is moved to a better place).

---

*[cmscontrib/AddParticipation.py, line 139 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRf4Nj732-tYXEByYg:-KhRf4Nj732-tYXEByYh:b-l5fyf8) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddParticipation.py#L139)):*
> ```Python
>     password_group.add_argument(
>         "-H", "--hashed-password", action="store", type=utf8_decoder,
>         help="password of the user, already hashed (using the given algorithm)")
> ```

'using the given algorithm (currently only --bcrypt)` or something (the issue: when --bcrypt is not specified is not easy for the user to understand how to fix)

---

*[cmscontrib/AddUser.py, line 57 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfbgVVFzMHYMQxKXI:-KhRfbgVVFzMHYMQxKXJ:bs6983d) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddUser.py#L57)):*
> ```Python
>     if is_hashed:
>         # TODO make sure it's a valid bcrypt hash if method is bcrypt.
>         stored_password = "%s:%s" % (method, password)
> ```

`build_password`

---

*[cmscontrib/AddUser.py, line 111 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfT2oYkRoP85tfcic:-KhRfT2oYkRoP85tfcid:buo9nmt) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddUser.py#L111)):*
> ```Python
>     password_group.add_argument(
>         "-H", "--hashed-password", action="store", type=utf8_decoder,
>         help="password of the user, already hashed (using the given algorithm)")
> ```

Same here

---

*[cmscontrib/updaters/update_28.py, line 45 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfXRu6G4Ml8IPY4GH:-KhRfXRu6G4Ml8IPY4GI:b-1c57v4) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/updaters/update_28.py#L45)):*
> ```Python
> 
>             if v["_class"] == "User":
>                 v["password"] = "text:%s" % v["password"]
> ```

use `build_password` (same two line below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/747)*

**Comment by lerks** [comment]
Review status: 4 of 16 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[cms/db/user.py, line 76 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3f021r5-mnwmvUJ8X:-KjF4rmyDhPBVIvnBfeX:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/db/user.py#L76)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

build_password (see later)
</blockquote></details>

Done.

---

*[cms/server/admin/handlers/contestuser.py, line 229 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3g-rzwfCwi9_ZIqzk:-KjEysql63sJxJ32PQct:b-hd6dzb) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/handlers/contestuser.py#L229)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

This code is quite convoluted, and I don't understand the second elif (why don't you look at the password itself? Why you have a conditional for the special value "text"? Could you make it more clear? Also it doesn't handle the ValueError (if for some reason the preexisting password was unparsable, you cannot change it).
</blockquote></details>

Done. I've unified the two pieces of code into a method of the superclass. I've added more comments and changed the condition to its negative which I think is easier to understand. Let me know if you think additional clarifications are needed.

---

*[cms/server/admin/handlers/user.py, line 84 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3geMDnDkcadWUVRhL:-KjEz9UgVArjpqoO2k_J:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/handlers/user.py#L84)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Same here (also, common method)?
</blockquote></details>

Done.

---

*[cms/server/admin/templates/add_user.html, line 43 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRgDLUIA21acfOWPnq:-KjEzGVF2p8rtBprIgRO:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/templates/add_user.html#L43)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Selected as default
</blockquote></details>

Done.

---

*[cms/server/admin/templates/user.html, line 119 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRg4yJ9tAQAEHvr2xH:-KjF19V45KwCsibJg5Wm:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/templates/user.html#L119)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Can we factor this into a fragment shared by user & participation?
</blockquote></details>

Done.

---

*[cmscommon/crypto.py, line 214 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRdr7MujCNf3TwG6mD:-KjF2pMLtZVmw5oga3SD:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscommon/crypto.py#L214)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Maybe `plain`, `plaintext` or `unencrypted`? 
</blockquote></details>

Done.

---

*[cmscontrib/AddParticipation.py, line 86 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRedUSwaHux_KxPIZ0:-KjF378jZ9M_WTbC46Oi:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddParticipation.py#L86)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

I'd add a `build_password` alongside `hash_password` to build the password from explicit values (so that the format is completely encapsulated and the todo is moved to a better place).
</blockquote></details>

Done.

---

*[cmscontrib/AddParticipation.py, line 139 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRf4Nj732-tYXEByYg:-KjF4iH0pFe0e4yB_Pn9:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddParticipation.py#L139)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

'using the given algorithm (currently only --bcrypt)` or something (the issue: when --bcrypt is not specified is not easy for the user to understand how to fix)
</blockquote></details>

Done.

---

*[cmscontrib/AddUser.py, line 57 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfbgVVFzMHYMQxKXI:-KjF3JI58fVxZxgI8rkt:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddUser.py#L57)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

`build_password`
</blockquote></details>

Done.

---

*[cmscontrib/AddUser.py, line 111 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfT2oYkRoP85tfcic:-KjF4hYe7-s_5ySkFPmR:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/AddUser.py#L111)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[cmscontrib/updaters/update_28.py, line 45 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-KhRfXRu6G4Ml8IPY4GH:-KjF3PqjnGqjRLrFWzVS:b9o2hmg) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cmscontrib/updaters/update_28.py#L45)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

use `build_password` (same two line below)
</blockquote></details>

I disagree: I don't think updaters should rely on any code from any other module, as they need to keep doing this operation forever no matter how the rest of the code changes (say, we don't want to keep that `build_password` method with that semantics around forever, even if the authentication syntax changes, just because one updater uses it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/747)*

**Comment by stefano-maggiolo** [comment]
LGTM

---

Reviewed 11 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cms/server/admin/handlers/contestuser.py, line 229 at r2](https://reviewable.io:443/reviews/cms-dev/cms/747#-Ki3g-rzwfCwi9_ZIqzk:-KjTCZzgkGBFiii0wetp:b-ucfknh) ([raw file](https://github.com/cms-dev/cms/blob/e1752b5ca428a78a219e86ff7fcf736c63b6b200/cms/server/admin/handlers/contestuser.py#L229)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Done. I've unified the two pieces of code into a method of the superclass. I've added more comments and changed the condition to its negative which I think is easier to understand. Let me know if you think additional clarifications are needed.
</blockquote></details>

Thanks!

---

*[cms/server/admin/templates/fragments/hashed_password_form.html, line 31 at r4](https://reviewable.io:443/reviews/cms-dev/cms/747#-KjTD6BXwvpZUhc7bpPf:-KjTD6BYpTQV-Uv2aUrC:b-of9w6o) ([raw file](https://github.com/cms-dev/cms/blob/749408d54c51f471658642326d0183c666fb6c26/cms/server/admin/templates/fragments/hashed_password_form.html#L31)):*
> ```HTML
>   $("[name=method]").change();
> </script>
> {% end %}
> ```

Nit: file doesn't end with whiteline (is it a problem?!).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/747#-:-KjTDREkU7PMqyUVlmmv:bb6ywmx)*

**Comment by lerks** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cms/server/admin/templates/fragments/hashed_password_form.html, line 31 at r4](https://reviewable.io:443/reviews/cms-dev/cms/747#-KjTD6BXwvpZUhc7bpPf:-KjTH5hZLt3Aaz6M7IE4:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/749408d54c51f471658642326d0183c666fb6c26/cms/server/admin/templates/fragments/hashed_password_form.html#L31)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Nit: file doesn't end with whiteline (is it a problem?!).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/747)*

**Pull request closed without merging**
