### PR TITLE
Make ES contest-agnostic

### PR DESCRIPTION
**Pull request by wil93**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/545)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Despite not being a huge patch, I'd prefer to keep this for the beginning of the release cycle.

**Comment by stefano-maggiolo** [comment]
Obviously this never happened. I'm going to merge this.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cms/service/esoperations.py, line 297 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/545#-KPUl3xjC59rSlDp8AnT:-KPUl3xkTbEBNia9VnQb:b-wsjmtd) ([raw file](https://github.com/cms-dev/cms/blob/992523427af5737f7808a2bcd6de58c92dc56662/cms/service/esoperations.py#L297)):*
> ```Python
>     session (Session): the database session to use.
>     contest_id (int): the contest for which we want the operations.
>         If none, get operations for any contest.
> ```

int|None in this case. 

---

*[cms/service/esoperations.py, line 404 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/545#-KPUl8KkqAyXd1o_flN0:-KPUl8KkqAyXd1o_flN1:b-89a4l7) ([raw file](https://github.com/cms-dev/cms/blob/992523427af5737f7808a2bcd6de58c92dc56662/cms/service/esoperations.py#L404)):*
> ```Python
>     session (Session): the database session to use.
>     contest_id (int): the contest for which we want the operations.
>         If none, get operations for any contest.
> ```

Ditto

---

*[cms/service/EvaluationService.py, line 176 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/545#-KPUlBXHhTZZiLH3lQaU:-KPUlBXHhTZZiLH3lQaV:b-6dn98o) ([raw file](https://github.com/cms-dev/cms/blob/992523427af5737f7808a2bcd6de58c92dc56662/cms/service/EvaluationService.py#L176)):*
> ```Python
>     WORKER_CONNECTION_CHECK_TIME = timedelta(seconds=10)
> 
>     def __init__(self, shard, contest_id=None):
> ```

Out of curiosity, do you think it makes sense to support "a certain number of contests"?

---

*[cms/service/Worker.py, line 81 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/545#-KPUlMtBn48Nvd8HB4Ya:-KPUlMtCJNYk1zjkUC-k:biwvyop) ([raw file](https://github.com/cms-dev/cms/blob/992523427af5737f7808a2bcd6de58c92dc56662/cms/service/Worker.py#L81)):*
> ```Python
>         logger.info("Precaching files for contest %d.", contest_id)
>         with SessionGen() as session:
>             files = []
> ```

Why is this necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/545#-:-KPUmBwZWJOJFrW_Id7T:b-yv3gsu)*

**Comment by veluca93** [comment]
No, it seems it was a leftover from some previous version.

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/545#-:-KPmZ-gKhXolLJQ5UAvM:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
