### PR TITLE
Tests for OutputOnly

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/962)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm: 

Commit msg in imperative form

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmstestsuite/unit_tests/grading/tasktypes/OutputOnlyTest.py, line 49 at r2](https://reviewable.io/reviews/cms-dev/cms/962#-LCYxXGs3WiFSvqcmxJu:-LCYxXGs3WiFSvqcmxJv:bp7qt74) ([raw file](https://github.com/cms-dev/cms/blob/29d2041d27bb14462e40b6c134a2a67e92e1333c/cmstestsuite/unit_tests/grading/tasktypes/OutputOnlyTest.py#L49)):*
> ```Python
> 
>     prepare() creates a task type and a job with the given arguments, and in
>     addition set up successful return values for eval_output.
> ```

s/set/sets/

---

*[cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py, line 109 at r2](https://reviewable.io/reviews/cms-dev/cms/962#-LCYw2Oa3rr35WIXOfPS:-LCYw2Oa3rr35WIXOfPT:b-tveonx) ([raw file](https://github.com/cms-dev/cms/blob/29d2041d27bb14462e40b6c134a2a67e92e1333c/cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py#L109)):*
> ```Python
>             patcher.start()
>             self.addCleanup(patcher.stop)
>         except Exception:
> ```

Can the exception type be narrowed down? (same below)

Can you only put in the `try` the one line that can fail?

---

*[cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py, line 152 at r2](https://reviewable.io/reviews/cms-dev/cms/962#-LCYwGt28r-raM7NZLmr:-LCYwGt28r-raM7NZLms:baha14m) ([raw file](https://github.com/cms-dev/cms/blob/29d2041d27bb14462e40b6c134a2a67e92e1333c/cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py#L152)):*
> ```Python
>             self.addCleanup(patcher.stop)
>         except Exception:
>             pass
> ```

Would it make sense to extract this pattern into a method?

Also, maybe in the except clause set the attribute to a new `MagicMock()` rather than leaving it unset: this allows child classes to still call `assert_not_called()` on it, for example.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/962#-:-LCYv7EX04Cuzuik4eC9:bcqqydy)*

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py, line 124 at r3](https://reviewable.io/reviews/cms-dev/cms/962#-LC_UdiWE3VV3WacTGuq:-LC_UdiX6wKcijAw3HIW:b-fottv1) ([raw file](https://github.com/cms-dev/cms/blob/c7a9eacc8dc2ec8c1353de04634c1420e6ab0c51/cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py#L124)):*
> ```Python
>         self.eval_output = self._maybe_patch("eval_output")
> 
>     def _maybe_patch(self, name, **kwargs):
> ```

Maybe passing `*args, **kwargs` could make the calls look more "natural" (i.e., like a real call to `patch`)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/962)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py, line 124 at r3](https://reviewable.io/reviews/cms-dev/cms/962#-LC_UdiWE3VV3WacTGuq:-LC_bqJBDpbGdTHCH2cs:b47jshi) ([raw file](https://github.com/cms-dev/cms/blob/c7a9eacc8dc2ec8c1353de04634c1420e6ab0c51/cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py#L124)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The idea was that then you could remove the `new=`...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/962)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py, line 124 at r3](https://reviewable.io/reviews/cms-dev/cms/962#-LC_UdiWE3VV3WacTGuq:-LC_cDSTBPHWIktZ3TU3:bpfxegz) ([raw file](https://github.com/cms-dev/cms/blob/c7a9eacc8dc2ec8c1353de04634c1420e6ab0c51/cmstestsuite/unit_tests/grading/tasktypes/tasktypetestutils.py#L124)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

The idea was that then you could remove the `new=`...
</blockquote></details>

I found it clearer with the new anyway, given patch has a bunch of kw arguments that do a bunch of different things and the order is not very meaningful.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/962)*

**Pull request merged**
