### PR TITLE
Handle correctly connections to Postgres via unix domain sockets

### LINKED ISSUE #807: "Using default port 5432 for Postgres DB" reported for Unix sockets
The warning about the default PostgreSQL port is reported even for Unix (non-TCP/IP) connections. It comes from `cms/db/session.py`.

See http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unix-domain-connections, the Unix socket connection is indicated by an empty host value in the connection string.

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Fixes #807.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/915)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmstestsuite/unit_tests/db/session_test.py, line 49 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/915#-L8Xl02f3ssvAq6XlT9W:-L8Xl02f3ssvAq6XlT9X:bd204gv) ([raw file](https://github.com/cms-dev/cms/blob/32bb37e200e1e951a4bddf359c9057bc76738a9d/cmstestsuite/unit_tests/db/session_test.py#L49)):*
> ```Python
>         # Simple TCP connection.
>         with _patch_db("postgresql+psycopg2://usrn:pwd@hooost:5433/dbname"):
>             custom_psycopg2_connection()
> ```

Maybe assign the return value to `res` and then add `self.assertIs(res, connect.return_value)`.  Same below. (BTW, this also fixes Codacy's comments ;) )

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/915)*

**Comment by stefano-maggiolo** [comment]
Done.

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/915#-:-L8Yr50oGuv5e0mTE1TD:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
