### PR TITLE
Allow to override task name, relax assertions on task dirname

### PR DESCRIPTION
**Pull request by wil93**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/616)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmscontrib/ImportTask.py, line 63 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJlG2T4WAX07b0ppS42:-KJlG2T4WAX07b0ppS43:1303306992) ([raw file](https://github.com/cms-dev/cms/blob/4d0fefd27718825b555954a45f387f9ed1ceeae5/cmscontrib/ImportTask.py#L63)):*
> ```Python
>     """
> 
>     def __init__(self, path, prefix, override_name, update, no_statement,
> ```

This is getting too complicated. Mind adding pydocs?

---

*[cmscontrib/loaders/italy_yaml.py, line 340 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJlGjBprmXTpHmatQ5Z:-KJlGjBprmXTpHmatQ5_:-464987093) ([raw file](https://github.com/cms-dev/cms/blob/4d0fefd27718825b555954a45f387f9ed1ceeae5/cmscontrib/loaders/italy_yaml.py#L340)):*
> ```Python
>             logger.info("The task name (%s) and the directory name (%s) are "
>                         "different. The former will be used.", args["name"],
>                         name)
> ```

It is easier and more readable and less prone to having forgotten something if you add here name = args["name"] (if you prefer, change the previously called name to directory, or something).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/616)*

**Comment by wil93** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmscontrib/ImportTask.py, line 63 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJlG2T4WAX07b0ppS42:-KJmCEqR9a84X0bbJ7XJ:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/4d0fefd27718825b555954a45f387f9ed1ceeae5/cmscontrib/ImportTask.py#L63)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> This is getting too complicated. Mind adding pydocs?
</details>
Done.

---

*[cmscontrib/loaders/italy_yaml.py, line 340 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJlGjBprmXTpHmatQ5Z:-KJmF0xR9Tnbvc4AFqPs:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/4d0fefd27718825b555954a45f387f9ed1ceeae5/cmscontrib/loaders/italy_yaml.py#L340)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> It is easier and more readable and less prone to having forgotten something if you add here name = args["name"] (if you prefer, change the previously called name to directory, or something).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/616)*

**Comment by stefano-maggiolo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmscontrib/ImportTask.py, line 74 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJo6b30Kr0zyO-7wNEz:-KJo6b30Kr0zyO-7wNF-:-933868576) ([raw file](https://github.com/cms-dev/cms/blob/a1e405a8146c5fab9856b750fef1a1068205bb03/cmscontrib/ImportTask.py#L74)):*
> ```Python
>         contest_id (int): if set, the new task will be tied to this contest.
> 
> 	"""
> ```

A wild tab appears!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/616)*

**Comment by wil93** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmscontrib/ImportTask.py, line 74 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/616#-KJo6b30Kr0zyO-7wNEz:-KJo7tK35OVKSHaKYTLP:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/a1e405a8146c5fab9856b750fef1a1068205bb03/cmscontrib/ImportTask.py#L74)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> A wild tab appears!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/616)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/616#-:-KKCqV-ZJEMQO2QWolUJ:1417088721)*

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
