### PR TITLE
Simplify installation and retrieval of translation files

### PR DESCRIPTION
**Pull request by wil93**
At the moment, `./prerequisites.py build_l10n` creates the `.mo` files, and `./prerequisites.py install_l10n` installs them.

With this PR, `./prerequisites.py install_l10n` is not needed anymore because the `.mo` files are installed by setup.py

This is cleaner because we can retrieve the files with pkg_resources instead of looking for specific paths.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/478)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
It sure looks cleaner, but I was wondering whether it would make more sense to put locale/ inside cms/server/contest since it's the only service using it. WDYT?

**Comment by wil93** [comment]
Yes I thought about putting locale/ there, but in the future one may want to localize other parts of cms. It's ok with me if we move it there, anyways.

Also: I considered dropping the LC_MESSAGES part of the paths but then I didn't do that. I think it doesn't actually serve any purpose....

**Comment by stefano-maggiolo** [comment]
It's fine to leave them there - I don't see us translating much else, but doesn't really hurt thinking that we might. Regarding LC_MESSAGES, seems a standard structure from gettext, so that's ok as well.

**Comment by stefano-maggiolo** [comment]
I'll check that it works with my setup, if so it looks good.


---

Reviewed 32 of 32 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
Add copyright notice.


---

<sup>**[cms/locale/locale.py, line 96 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-0A58BDCWry3nF9E)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/locale.py#L96)):</sup>
Fix indentation


---

<sup>**[docs/Localization.rst, line 46 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V1ESM0D6Q4Z7Y6AIW)** ([raw file](https://github.com/cms-dev/cms/blob/d87b63f4e56b67a1c26c6082e8699dec183a9d92/docs/Localization.rst#L46)):</sup>
*you are


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by stefano-maggiolo** [comment]
Yep, looks good also for non-installed. Thanks!


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by wil93** [comment]
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
If I'm not mistaken, there was this rule of thumb not to put copyright notices in __init__.py files?


---

<sup>**[cms/locale/locale.py, line 96 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-0A58BDCWry3nF9E)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/locale.py#L96)):</sup>
Done.


---

<sup>**[docs/Localization.rst, line 46 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V1ESM0D6Q4Z7Y6AIW)** ([raw file](https://github.com/cms-dev/cms/blob/d87b63f4e56b67a1c26c6082e8699dec183a9d92/docs/Localization.rst#L46)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by stefano-maggiolo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
Well, if there is we're not following it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by wil93** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
Maybe it was just for the *empty* ones... https://github.com/cms-dev/cms/commit/1edb4bb6093aa483ee5df20817d64b9d9d6d7051


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by wil93** [comment]
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
Added (btw I just relized that by copyright notice you meant the "This program is free software.." part and not the single copyright claims (with the name, email, date).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1V-jBmmfOy2fUTvk9C)** ([raw file](https://github.com/cms-dev/cms/blob/2e20a1efdf56a21cf83469946379309b7d11e7ed/cms/locale/__init__.py#L1)):</sup>
Yeah, sorry about that. If you want feel free to add your name as well.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cms/locale/__init__.py, line 31 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/478#-K1aQhJto0vBCxgA8rr-)** ([raw file](https://github.com/cms-dev/cms/blob/45a173471b6875e33e3b83d4e6f0b7d21f2d666d/cms/locale/__init__.py#L31)):</sup>
FYI there were a few more errors here: mostly it should have been `from .locale import [...]`, then two empty lines need to go after all imports, not between them.

I fixed these and pushed, no need to fix them yourself.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/478)

**Comment by stefano-maggiolo** [comment]
Merged in 747109379df35ca434e247caeef2cdc9a84cf38b and 9dbd80c6270f8924daa5294573ac10979eb9d123

**Pull request closed without merging**
