### PR TITLE
Implement regular expression support for specifying testcases

### PR DESCRIPTION
**Pull request by wafrelka**
It is useful if we can specify the testcases of each subtask by regular expressions at `ScoreTypeGroup`.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/511)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Thanks, this looks really nice!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/grading/ScoreType.py, line 277 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h80qlIaxLGc-diex9:-K7h80qlIaxLGc-diexA:1594694455) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L277)):*
Have you tried what happens when a testcase is matched by more than one regex?

---

*[cms/grading/ScoreType.py, line 279 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h2naAxoQa7PrqAYby:-K7h2naAxoQa7PrqAYbz:-435689069) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L279)):*
No need for the continuation here, it is inside a parenthesis. (Also it's slightly more readable to add the newline right after "(", so the string is not split)

---

*[cms/grading/ScoreType.py, line 285 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h2blXE-24Ny--lwKE:-K7h2blXE-24Ny--lwKF:-1149527507) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L285)):*
"In the score type parameters, the second value of each element must have the same type (int or str)"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/511#-:-K7h8QYpNpZj19pqRY3I:-97158405)*

**Comment by wafrelka** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/grading/ScoreType.py, line 277 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h80qlIaxLGc-diex9:-K7p6_rpmZ2KIn-idHro:-250130936) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L277)):*
The testcase will be assigned to multiple subtasks, and the outcome will be used for determining the score of the multiple subtasks. I tested it. I think there's no problem.

---

*[cms/grading/ScoreType.py, line 279 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h2naAxoQa7PrqAYby:-K7p5aD0pMr3l5BzqbeM:228479898) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L279)):*
Thank you for the improvement. I fixed it.

---

*[cms/grading/ScoreType.py, line 285 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h2blXE-24Ny--lwKE:-K7p6IwjVUHB0_QeAQ6Z:1758359711) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L285)):*
Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/511)*

**Comment by stefano-maggiolo** [comment]
Thanks, pushing this. I'll add a change to the documentation to make this possibility more visible

---

Reviewed 1 of 1 files at r3.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[cms/grading/ScoreType.py, line 277 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/511#-K7h80qlIaxLGc-diex9:-K7thkqhhQ_HCLKtN1K4:-76354732) ([raw file](https://github.com/cms-dev/cms/blob/c8bf56d6825a17fd573c37920780f316565e4426/cms/grading/ScoreType.py#L277)):*
Thanks for trying! I agree, it shouldn't create any problem.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/511#-:-K7thtSnH214eEJH4_qF:611721961)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/511)*

**Comment by stefano-maggiolo** [comment]
Merged!

**Pull request closed without merging**
