### PR TITLE
Some work on AWS templates

### LINKED ISSUE #529: What is the format of "Allowed web interface localization"?
Assume that I only allow English and Vietnamese to be used in the CWS. What should I input in the box "Allowed web interface localization"?

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/532)

Fixes #529

### CODE REVIEW

**Comment by giomasce** [comment]
Reviewed 10 of 10 files at r1.
Review status: 7 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by giomasce** [comment]
Reviewed 9 of 11 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/server/admin/templates/add_dataset.html, line 118 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hPqOMsStIwJeKOEBm:-K9hPqOMsStIwJeKOEBn:553522332) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/add_dataset.html#L118)):*
Here (and in many similar lines) we hardcode the version number. Can we reuse the value known by `setup.py`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by wil93** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/server/admin/templates/add_dataset.html, line 118 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hPqOMsStIwJeKOEBm:-K9hUSq31VsT7Jg2_LVJ:-1414445050) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/add_dataset.html#L118)):*
[Here](http://read-the-docs.readthedocs.org/en/latest/features.html#version-control-support-matrix) they say that RTD creates endpoints for each git branch/tag. I'm not sure about that (I tried with the "v1.2.0" tag and it didn't work), but maybe it's enough to tag the latest released version (as "stable"?) and then link to `http://cms.readthedocs.org/en/stable/Score%20types.html`. But maybe you wanted to keep the actual version there?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by giomasce** [comment]
Reviewed 2 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by giomasce** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/admin/templates/contest.html, line 24 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hn0FVB-LZZbGzSxDh:-K9hn0FVB-LZZbGzSxDi:305047634) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/contest.html#L24)):*
Missing trailing dot. Also in other `name` fields.

---

*[cms/server/admin/templates/participation.html, line 75 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hmDSk2mjkrii5ROvt:-K9hmDSlhsbkXyP-WMr-:-1421230989) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/participation.html#L75)):*
Maybe we could repeat here that the password is stored in plain text.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/admin/templates/add_dataset.html, line 118 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hPqOMsStIwJeKOEBm:-K9iTePLbUUSqGpEzQry:-595351102) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/add_dataset.html#L118)):*
Yes, we want to point to the version corresponding to the sources.

---

*[cms/server/admin/templates/contest.html, line 24 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hn0FVB-LZZbGzSxDh:-K9ieycez7ja_GYQAGM_:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/contest.html#L24)):*
Done.

---

*[cms/server/admin/templates/participation.html, line 75 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/532#-K9hmDSk2mjkrii5ROvt:-K9ifH265_fqF4t3Ey4W:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bf2b8604b106a17a88150a5732359ac9f2c685f5/cms/server/admin/templates/participation.html#L75)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by giomasce** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Comment by giomasce** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/532)*

**Pull request merged**
