### PR TITLE
Detect virtualenv

### PR DESCRIPTION
**Pull request by wil93**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/723)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
This still doesn't work with non-installed virtualenv. I'll see if there is a way to save it...

**Comment by stefano-maggiolo** [comment]
What about 
```py
bin_path = os.path.join(os.getcwd(), sys.argv[0])
bin_name = os.path.basename(ran_path)
bin_is_python = bin_name in ["ipython", "python", "python2", "python3"]
bin_in_installed_path = bin_path.startswith(sys.prefix) or (
    hasattr(sys, 'real_prefix') and bin_path.startswith(sys.real_prefix))
self.installed = bin_in_installed_path and not bin_is_python
```

**Comment by wil93** [comment]
> non-installed virtualenv

What is that?

**Comment by stefano-maggiolo** [comment]
All libraries are installed in a virtualenv, CMS is ran from the sources.

(There was a "ran_path" which should have been a "bin_path", changing it in the code above.)

**Comment by wil93** [comment]
> All libraries are installed in a virtualenv, CMS is ran from the sources

Oh, OK... even if I can't really see why one would want to do that :smile:

> What about [...]

LGTM

**Pull request merged**
