### PR TITLE
Get rid of SmartMappedCollection

### PR DESCRIPTION
**Pull request by lerks**
The troubles it caused far exceeded its benefits.

Addresses #736 and possibly #726 and #666.

(Negative diff is best diff.)

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/737)

### CODE REVIEW

**Comment by lerks** [comment]
PS: I didn't do any manual testing; just ran the test suite.

**Comment by stefano-maggiolo** [comment]
Looks fine, IIUC the reason why we have so few changed lines is that we never move objects between different parents, and that to add children we usually use the pattern of creating the parent, then creating the children objects directly (since we don't use them in the rest of the session anyway). Correct? 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/737#-:-KgmqnON42fhSQixXYu1:bz4mi16)*

**Comment by lerks** [comment]
Yes, quite. Also, the main deficiency of SA's mapped_collection that SMC tried to address is the inability to respond to child objects changing their value on the column that acts as key. Apparently, though, we never did that or it never bit us.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/737#-:-KgoBAgzGzZAZ8X1eNmJ:b5hhcsm)*

**Comment by stefano-maggiolo** [comment]
One more thing, can we do these with column_mapped_collection?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/737#-:-Kgo_0HzKiWHklfezzwL:b87pasq)*

**Comment by lerks** [comment]
Apparently not. I tried and Alchemy fails, saying that it expected a `Column`-based argument but got a `unicode` instead. In fact, the documentation specifies that "`column_mapped_collection` [...] is almost like `attribute_mapped_collection` except given the `Column` object directly". We cannot give the `Column` object, as we haven't built it yet. Unless you have other ideas on how to do this I'm sticking to `attribute_mapped_collection`.

PS: I'm still waiting for your review and LGTM...

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/737#-:-KgrGn3Nf21bj8XTmPiS:b-6rum50)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/737#-:-KgrJI17k3mtSnTp1iO9:bnfp4nl)*

**Pull request closed without merging**
