### PR TITLE
Fix cmsAddUser: do not try to add a user that already exists

### PR DESCRIPTION
**Pull request by lucach**
This aligns AddUser with AddContest and AddTask.

Adding a user without checking if it is a duplicate wastes an ID each time.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/500)

### CODE REVIEW

**Comment by wil93** [comment]
If I'm not mistaken this doesn't change the script's behavior, right?

If that's the case, I think the old approach (with `try`-`catch`) was more pyhonic, as for [EAFP](https://docs.python.org/2/glossary.html#term-eafp).

**Comment by lucach** [comment]
You're right, it's equivalent except that this way we do not create "holes" in the IDs progression.

**Comment by wil93** [comment]
That's a good point... Maybe the most clean solution is to add `session.rollback()` just after `except IntegrityError:`, I'm not sure if it does what I think it does (it should).

**Comment by wil93** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/500)_

**Comment by wil93** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/500)_

**Comment by lucach** [comment]
Rebased after f8ba5b9
If we want to keep this style, it should be also changed the new cmsAddTeam.

**Comment by stefano-maggiolo** [comment]
I'm honestly agnostic with respect to this change :)
IDs are not guaranteed nor required to be consecutive, and on the other hand I don't particularly prefer try-except over if-else... Maybe slightly in favor of if-else as IntegrityError in theory could be raised by other problems.

If we want to make this an abstract style discussion though, I'd prefer the fast-return pattern:

```python
old_user = [...]
if old_user is not None:
  [log]
  return
[add user
```

Mostly because in other situations the else branch could be large.
Can you change it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/500#-:-K4EDJC8Q8Z0o1M-snfL:-1725016436)*

**Comment by lucach** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/500#-:-K4M_XPZxFPMC05Sr3lo:-499146009)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/500)*

**Pull request closed without merging**
