### PR TITLE
Add link to AUR packages

### PR DESCRIPTION
**Pull request by wil93**

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Will include this soon.

**Comment by stefano-maggiolo** [comment]
Done. ea16881f826c78b611355b99a19f49ef032857ec
Thanks!

**Comment by wil93** [comment]
I think that the links were broken, I pushed this fixup 26be6f6eedb64af4f8d3565ff2030ef0010aac8a

**Comment by stefano-maggiolo** [comment]
Ops, I didn't notice the fixup. I included it now.

**Pull request closed without merging**
