### PR TITLE
Add cmsImportDataset command

### PR DESCRIPTION
**Pull request by wil93**
Tired of uploading zips full of testcases via AdminWebServer? This pull request allows you to finally import new datasets from the command line!

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/613)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmscontrib/__init__.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8x6KUTSwIof_CthSe:-KP8x6KUTSwIof_CthSf:bw3w1z) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/__init__.py#L100)):*
> ```Python
>         # graph, recursing only on "vector" relationships.
>         # TODO Find a better way to handle all of this.
>         # TODO Actually, avoid *ever* using this :P
> ```

Expand or remove... ;p

---

*[cmscontrib/ImportDataset.py, line 22 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xBuY1H6jgkMrXP7Y:-KP8xBuY1H6jgkMrXP7Z:b-vtpndi) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L22)):*
> ```Python
> """This script works kind of like cmsImportTask, but it assumes that the task
> already exists. Specifically, it will just add a new dataset (without
> activating it.
> ```

Missing )

---

*[cmscontrib/ImportDataset.py, line 53 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xJD9F-Rph5e2likM:-KP8xJD9F-Rph5e2likN:b223qow) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L53)):*
> ```Python
>     """This script creates a dataset
> 
>     """
> ```

Make comment useful or remove. (Also with oneliners you can do """...""")

---

*[cmscontrib/ImportDataset.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xU-6vv9i7ueTYjrV:-KP8xU-6vv9i7ueTYjrW:b2nvuqs) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L78)):*
> ```Python
>         if self.description is None:
>             import petname
>             dataset.description = petname.Generate(2, " ").title()
> ```

Nope. Remove dependency from petname please (forcing description seems also a good idea to force the admin to be able to find it back after).

---

*[cmscontrib/ImportDataset.py, line 83 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xftSH6nSaR8UF2Y5:-KP8xftTcPQMcangZdMg:b-x0392t) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L83)):*
> ```Python
> 
>         # Store the dataset
>         logger.info("Creating new dataset for task %s on the database.",
> ```

Print also dataset name?

---

*[cmscontrib/ImportDataset.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xrRQoOckW_n2JfpW:-KP8xrRQoOckW_n2JfpX:b-1bs85i) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L100)):*
> ```Python
>             else:
>                 logger.error("The specified task does not exist. "
>                              "Aborting, no dataset imported.")
> ```

missed a return? Also easy "if" case first is usually more understandable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/613)*

**Comment by wil93** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmscontrib/__init__.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8x6KUTSwIof_CthSe:-KP930r-BT2xhEpKfzn6:b-xht6wk) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/__init__.py#L100)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Expand or remove... ;p
</details>
Removed. I think that code should not be used because it's messy and it doesn't seem to work correctly (e.g. the `--update` flag when importing a task is so unpredictable that I never use it, and that's basically why I wrote `cmsImportDataset`, which I believe it's the best way to do the `--update` thing).

---

*[cmscontrib/ImportDataset.py, line 22 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xBuY1H6jgkMrXP7Y:-KP8z8KUV19uWOnUZXGM:b-fce8ur) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L22)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Missing )
</details>
It's already fixed in a later commit

---

*[cmscontrib/ImportDataset.py, line 53 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xJD9F-Rph5e2likM:-KP93pLUEI-P69ZK1k7l:b-9al89f) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L53)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Make comment useful or remove. (Also with oneliners you can do """...""")
</details>
Remved. I had copied that from `cmscontrib/ImportTask.py`

---

*[cmscontrib/ImportDataset.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xU-6vv9i7ueTYjrV:-KP94CDAuglWGU5bqNYZ:b-8cxcpl) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L78)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Nope. Remove dependency from petname please (forcing description seems also a good idea to force the admin to be able to find it back after).
</details>
Mmm I think it can be useful sometimes, especially during contests, when you might want to quickly import a new dataset without having to figure out a name for it.

An alternative may be to name it "Default2" (or "Default3", and so on). Or do you want to actually force a description?

---

*[cmscontrib/ImportDataset.py, line 83 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xftSH6nSaR8UF2Y5:-KP94wV1TIxcQIHQ9H1F:b-ib55ar) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L83)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Print also dataset name?
</details>
Already fixed in later commit

---

*[cmscontrib/ImportDataset.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xrRQoOckW_n2JfpW:-KP957Vj5BP62nYpDYPR:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L100)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> missed a return? Also easy "if" case first is usually more understandable.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/613)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmscontrib/ImportDataset.py, line 22 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xBuY1H6jgkMrXP7Y:-KP9qid8qkVZ21AsqxeS:b-xzaky) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L22)):*
<details><summary><i>Previously, wil93 (William Di Luigi) wrote…</i></summary>
> It's already fixed in a later commit
</details>
Sorry, I'm used to review PR with one real commit per commit.

---

*[cmscontrib/ImportDataset.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xU-6vv9i7ueTYjrV:-KP9qouwnyTIJ7zJRRl6:b7v3ohx) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L78)):*
<details><summary><i>Previously, wil93 (William Di Luigi) wrote…</i></summary>
> Mmm I think it can be useful sometimes, especially during contests, when you might want to quickly import a new dataset without having to figure out a name for it.
> 
> An alternative may be to name it "Default2" (or "Default3", and so on). Or do you want to actually force a description?
</details>
Specifically *during* a contest you don't want to be surprised with a wobbly wombat, imho. Also an additional dependency just for this is a bit silly. Another option is to ask the user for a name if not provided in the source.

---

*[cmscontrib/ImportDataset.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xrRQoOckW_n2JfpW:-KP9qWsX9R4tSW4TDZ1o:b-ictray) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L100)):*
<details><summary><i>Previously, wil93 (William Di Luigi) wrote…</i></summary>
> Done.
</details>
And no need for else :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/613)*

**Comment by wil93** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmscontrib/ImportDataset.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xU-6vv9i7ueTYjrV:-KPL2f6WYG3vTYFNbJLF:b-1thrym) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L78)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Specifically *during* a contest you don't want to be surprised with a wobbly wombat, imho. Also an additional dependency just for this is a bit silly. Another option is to ask the user for a name if not provided in the source.
</details>
Done. Now the scripts asks the user for a description.

---

*[cmscontrib/ImportDataset.py, line 100 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/613#-KP8xrRQoOckW_n2JfpW:-KPL3M_XDZSXVAUSmJMU:b2edl7j) ([raw file](https://github.com/cms-dev/cms/blob/e19d087d853feee114e9f9966f5fa07c23b562d5/cmscontrib/ImportDataset.py#L100)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> And no need for else :)
</details>
Whoops, right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/613)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/613#-:-KPNdCQ5IbbZIE-uj0y4:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged!

**Pull request closed without merging**
