### PR TITLE
Fix italy_yaml loader and cmsAddContest

### PR DESCRIPTION
**Pull request by lucach**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/499)

### CODE REVIEW

**Comment by lucach** [comment]
Also fixes #490

**Comment by stefano-maggiolo** [comment]
Looks good, but I'd like @wil93 to also take a look.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[cmscontrib/loaders/italy_yaml.py, line 631 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3njFOFPHL039suAYhA:-K3njFOFPHL039suAYhB:-87400903) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L631)):_
Nit: all of these short pydoc can be one liners:
"""See ..."""

---

_[cmscontrib/loaders/italy_yaml.py, line 639 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3ncqqYYVS2MECt9A26:-K3ncqqYYVS2MECt9A27:114546796) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L639)):_
This should be a return False, right? Or better a sys.exit(1), but return None is not handled correctly anyway. (The pydoc for contest_has_changed() does not mention None)

---

_[cmscontrib/loaders/italy_yaml.py, line 676 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3njN7h3uOj4JXeoQpE:-K3njN7h3uOj4JXeoQpF:1854746597) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L676)):_
Same here

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499#-:-K3njhcocUC0mGCZ16vw:559967625)_

**Comment by wil93** [comment]
Mmmm.... This PR clashes with #481

We have two options:

* I split #481 in two PRs (as I should have done from the beginning), moving away the "support hidden participation" part, which is in b63cf9b1a3702f36dc642d2d2ebfb2308a0b09c6 and also (partly) in b8fc6b34134edb12d7d8b6887a913861cb4b5445
* ...Or, this PR gets rebased onto #481 

I think that the second option is the most straightforward since there will always be a need for a rebase (either this PR or the upcoming "support hidden participation" PR).

**Comment by lucach** [comment]
Changed after #481
We still have an issue: the details of a participation cannot be updated if the participation already exists (I've added a FIXME).
However, I can't call it a regression since ``cmsAddContest --update-contest``, as it is now in master, doesn't work at all.

**Comment by stefano-maggiolo** [comment]
A few more notes, then we  can push. Sorry it took me so long to review.

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cmscontrib/AddContest.py, line 191 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HFA1ezdcpVfWLvGud:-K4HFA1ezdcpVfWLvGue:-286527598) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/AddContest.py#L191)):*
Isn't it easier to delete the existing one and recreating it?

If you prefer this way, fine with me, but maybe add a log message that the participation was already in the db and you did not update it.

---

*[cmscontrib/loaders/italy_yaml.py, line 676 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3njN7h3uOj4JXeoQpE:-K4HJzuboDfUnq6AQh1I:-1741020405) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L676)):*
Please fix :)

---

*[cmscontrib/loaders/italy_yaml.py, line 677 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HJ_xyiocXlNtp5QrA:-K4HJ_xyiocXlNtp5QrB:-803869309) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L677)):*
I think you're missing a sys.exit here as well. Also, how would the admin know that they have to delete .import_error_contest?

---

*[cmscontrib/loaders/italy_yaml.py, line 771 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HK1Yg74l8oNa1VUQI:-K4HK1Yg74l8oNa1VUQJ:-1440067999) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L771)):*
And also here the same as above applies

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499#-:-K4HK7EV1dhXCDRY4bhQ:-689874997)*

**Comment by lucach** [comment]
This is embarrassing, but I've messed up with Reviewable last time. I though that the comments were sent, but in fact they have been kept in draft.
Really sorry about that.

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmscontrib/AddContest.py, line 191 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HFA1ezdcpVfWLvGud:-K4IvDXm2AzR_q4XKtNE:-194151532) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/AddContest.py#L191)):*
I thought that deleting a participation implies the deletion of all the corresponding submissions (which is the bug we're trying to fix with this patch). Am I wrong? (see https://github.com/cms-dev/cms/blob/master/cms/db/submission.py#L55-L67).

---

*[cmscontrib/loaders/italy_yaml.py, line 631 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3njFOFPHL039suAYhA:-K3nsvdrDdogwrEqsqA0:-373775041) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L631)):*
It is a good time to change them. Done :)

---

*[cmscontrib/loaders/italy_yaml.py, line 639 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3ncqqYYVS2MECt9A26:-K3ntC2C1-sY3lS4J9Uy:-1001874694) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L639)):*
Neither False nor True as the import cannot proceed. Switched to sys.exit(1).

---

*[cmscontrib/loaders/italy_yaml.py, line 676 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K3njN7h3uOj4JXeoQpE:-K3ntdJq7s39nzrDDev-:-1844131066) ([raw file](https://github.com/cms-dev/cms/blob/e4652ba1925f1956ae6348767509bb1c64e9f7a8/cmscontrib/loaders/italy_yaml.py#L676)):*
The above was in fact taken from here. Changed here too.

---

*[cmscontrib/loaders/italy_yaml.py, line 677 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HJ_xyiocXlNtp5QrA:-K4IozV9I9nPZJjSS666:1660018287) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L677)):*
You're right, let's be consistent.
I took the hidden file method from ```task_has_changed```. As it's now, there's no way to discover that he/she has to remove the file to override this kind of behaviour. Maybe we should be a little more verbose in the log message.

---

*[cmscontrib/loaders/italy_yaml.py, line 771 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HK1Yg74l8oNa1VUQI:-K4IowSv3TGNxhv97O03:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L771)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499#-:-K4IzD68pe65uBRKyUVN:-1119369001)*

**Comment by stefano-maggiolo** [comment]
No worries, we are all getting the hang of it...

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmscontrib/AddContest.py, line 191 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HFA1ezdcpVfWLvGud:-K4J-64sl_l_x_O9AFcI:1912027681) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/AddContest.py#L191)):*
No you're completely right! Let's keep it like that for the moment with the fixme. 

---

*[cmscontrib/loaders/italy_yaml.py, line 677 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HJ_xyiocXlNtp5QrA:-K4J-RXihpsLTZciJDA8:-1836713487) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L677)):*
Yes please, add something like "After fixing the error, delete the file .import_error_contest" or something similar. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499#-:-K4J-2-VUy9czmGUvNLS:-311239911)*

**Comment by lucach** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmscontrib/loaders/italy_yaml.py, line 677 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/499#-K4HJ_xyiocXlNtp5QrA:-K4J3So5nCivjEwXo1MH:1080490529) ([raw file](https://github.com/cms-dev/cms/blob/2eea839cf5dfb83560c6f8b550b2d76311c2c735/cmscontrib/loaders/italy_yaml.py#L677)):*
Done (also in ```task_has_changed```).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/499)*

**Comment by stefano-maggiolo** [comment]
Merged, thank you!

**Pull request closed without merging**
