### PR TITLE
Add module to encapsulate all our digesting needs

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/889)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmscommon/digest.py, line 79 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VKbOqLRQ0usFPoWZk:-L7VKbOqLRQ0usFPoWZl:b-4gtsky) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmscommon/digest.py#L79)):*
> ```Python
>     with io.open(path, 'rb') as fin:
>         d = Digester()
>         buf = fin.read(io.DEFAULT_BUFFER_SIZE)
> ```

What happens if you don't pass the buffer size?

---

*[cmscontrib/DumpExporter.py, line 62 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VKr5EIp-boFPo-cjj:-L7VKr5EIp-boFPo-cjk:b-43xcvc) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmscontrib/DumpExporter.py#L62)):*
> ```Python
> 
> from cmscommon.digest import path_digest
> from cmscommon.datetime import make_timestamp
> ```

Nit: sort

---

*[cmstestsuite/unit_tests/testidgenerator.py, line 49 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VL2OGKhBssHuhmE2n:-L7VL2OGKhBssHuhmE2o:b-8kgdbx) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmstestsuite/unit_tests/testidgenerator.py#L49)):*
> ```Python
> def unique_digest():
>     """Return a unique digest-like string."""
>     return bytes_digest(unique_unicode_id().encode())
> ```

Is the encoding optional? Which one is used: ASCII, UTF-8, system locale?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/889#-:-L7VMMKY-t5gq6PeRwyj:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmscommon/digest.py, line 79 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VKbOqLRQ0usFPoWZk:-L7WDED33cgS8f7obBZ9:b-do4brt) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmscommon/digest.py#L79)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

What happens if you don't pass the buffer size?
</blockquote></details>

I think read() usually reads the whole file.

---

*[cmscontrib/DumpExporter.py, line 62 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VKr5EIp-boFPo-cjj:-L7WDNZVk2yQfHjEE0Mv:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmscontrib/DumpExporter.py#L62)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Nit: sort
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/testidgenerator.py, line 49 at r1](https://reviewable.io:443/reviews/cms-dev/cms/889#-L7VL2OGKhBssHuhmE2n:-L7WD_htZCgelvlw4nDh:bsxmlwi) ([raw file](https://github.com/cms-dev/cms/blob/0d091446b6e7587f66a6db6d3855ef17b798cea1/cmstestsuite/unit_tests/testidgenerator.py#L49)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Is the encoding optional? Which one is used: ASCII, UTF-8, system locale?
</blockquote></details>

Ah! indeed I only looked at python3, where the default encoding is utf-8, whereas in python2 it is the current locale.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/889)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/889)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
