### PR TITLE
Fix Travis on py3

### PR DESCRIPTION
**Pull request by lerks**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/832)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 32 at r3](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4beNRYTE5HcRgHEFNA:-L4beNRYTE5HcRgHEFNB:b-u2kgpe) ([raw file](https://github.com/cms-dev/cms/blob/6a846a856d898df4f946715700b2b80acf53860d/.travis.yml#L32)):*
> ```YAML
>   - sudo pip install -r dev-requirements.txt
> # We need to build psycopg2 from source on Travis because of https://github.com/psycopg/psycopg2/issues/543
>   - sudo pip install 'psycopg2>=2.7,<2.8' --no-binary psycopg2 --ignore-installed
> ```

No need anymore?

---

*[prerequisites.py, line 38 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bcNbQPLnfKe8Tf_BA:-L4bcNbR4iICu8onXG3c:br9ieox) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L38)):*
> ```Python
> # called as root and thus may get a different environment than the one
> # the user will be using and in which the requirements were installed
> # (e.g. the site installation rather than a venv).
> ```

Please explain what is the eventual issue - not having future?
[Note that this script is called also as non-root.]

---

*[prerequisites.py, line 58 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bcls_ILI1g1GKj19z:-L4bcls_ILI1g1GKj1A-:b4fx4uw) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L58)):*
> ```Python
> AS_ROOT = False
> NO_CONF = False
> CMSUSER = "cmsuser"
> ```

Comment on these globals

---

*[prerequisites.py, line 310 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bdIDB6B4DspcaSvk3:-L4bdIDB6B4DspcaSvk4:bgm6osu) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L310)):*
> ```Python
>     print("===== Creating user and group %s" % CMSUSER)
>     subprocess.call(["useradd", CMSUSER, "-c", "CMS default user",
>                      "-M", "-r", "-s", "/bin/false", "-U"])
> ```

Comment on what happens when the user already exists, and better info on the print. There is a bit of an issue in case there CMSUSER exists but not the group, in which case I'm sure something later will fail (e.g. chown root:CMSUSER). Maybe also create the group separately?

---

*[prerequisites.py, line 429 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bdwLVG0fPkjbsCGvN:-L4bdwLWc5mB0DvSHV4u:b-ntmi2i) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L429)):*
> ```Python
>         subprocess.call(["userdel", CMSUSER])
>     except KeyError:
>         print("[Warning] Group %s not found" % CMSUSER)
> ```

Argh. Ask before deleting?

---

*[prerequisites.py, line 480 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4beDbaak5sc3x0v94c:-L4beDbaak5sc3x0v94d:bluro5c) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L480)):*
> ```Python
>         NO_CONF = True
>     if args.as_root:
>         AS_ROOT = True
> ```

ALWAYS_YES = args.yes and similar?

---

*[cms/__init__.py, line 47 at r1](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bbAma89IijxJXlknu:-L4bbAma89IijxJXlknv:bnxu87i) ([raw file](https://github.com/cms-dev/cms/blob/d573e1b82e627b876e4a4564165fdb5f45941fd2/cms/__init__.py#L47)):*
> ```Python
>      "Address", "ServiceCoord", "ConfigError", "async_config", "config",
>     # util
>     "mkdir", "utf8_decoder", "get_safe_shard", "get_service_address", \
> ```

No need for the `\`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/832)*

**Comment by lerks** [comment]
Review status: 6 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[.travis.yml, line 32 at r3](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4beNRYTE5HcRgHEFNA:-L4bmnu-qfAqYS3nUM6E:b-yixx3b) ([raw file](https://github.com/cms-dev/cms/blob/6a846a856d898df4f946715700b2b80acf53860d/.travis.yml#L32)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

No need anymore?
</blockquote></details>

Yes, as stated in the commit msg. Apparently it was just an issue when we installed pysocpg2 using pip as a site package. When we do it in the venv it works fine.

---

*[prerequisites.py, line 38 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bcNbQPLnfKe8Tf_BA:-L4bn1_8-85w6SYo2n95:bnf67pz) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L38)):*
> Do not use imports from the future module
I did: "Do not use imports from the *future* module". Do you want me to clarify anything?

---

*[prerequisites.py, line 58 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bcls_ILI1g1GKj19z:-L4boNm69CqJadgO_2FX:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L58)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Comment on these globals
</blockquote></details>

Done.

---

*[prerequisites.py, line 310 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bdIDB6B4DspcaSvk3:-L4buS6sYoVXDh4vxX4o:bcs7p60) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L310)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Comment on what happens when the user already exists, and better info on the print. There is a bit of an issue in case there CMSUSER exists but not the group, in which case I'm sure something later will fail (e.g. chown root:CMSUSER). Maybe also create the group separately?
</blockquote></details>

I've done as follows: first check if the group exists, if it doesn't create it; then check if the user exists, if it doesn't create it (with the previous group as primary group). Fail if any of the creation commands fail. Is this ok?

---

*[prerequisites.py, line 429 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bdwLVG0fPkjbsCGvN:-L4bwBZl9M8VcLIRDdP4:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L429)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Argh. Ask before deleting?
</blockquote></details>

Done.

---

*[prerequisites.py, line 480 at r2](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4beDbaak5sc3x0v94c:-L4bwIA1s-VSBt20e0b6:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e7e8e619d9792686401ac478c2c3c80e48a0f64a/prerequisites.py#L480)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

ALWAYS_YES = args.yes and similar?
</blockquote></details>

Done.

---

*[cms/__init__.py, line 47 at r1](https://reviewable.io:443/reviews/cms-dev/cms/832#-L4bbAma89IijxJXlknu:-L4bwY3VlC8mF_-OYH5B:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/d573e1b82e627b876e4a4564165fdb5f45941fd2/cms/__init__.py#L47)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

No need for the `\`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/832)*

**Comment by stefano-maggiolo** [comment]
Good to go, merge ahead

**Comment by lerks** [comment]
Done.

**Pull request closed without merging**
