### PR TITLE
Get rid of the last remaining Python2-only dependencies

### PR DESCRIPTION
**Pull request by lerks**
Contrary to what I said in #286, there were some dependencies left that haven't been ported to Python 3 yet. These were BeautifulSoup (which I ported to version 4) and mechanize (which I replaced with requests).

---

This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/624)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 3 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cmstestsuite/__init__.py, line 78 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKshhmjspJsUx2bvyJH:-KKshhmkboOC-EY6_c9r:1302072199) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/__init__.py#L78)):*
> ```Python
> 
> 
> # Sessions to access AWS and CWS.
> ```

What is a session?

---

*[cmstestsuite/ReplayContest.py, line 228 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_Q-r2-228:-KKsi3xXEvky8APzXkYu:-602331978) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/ReplayContest.py#L228)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary>
> Codacy Issue found: [Unexpected keyword argument 'filename' in constructor call](https://www.codacy.com/app/s-maggiolo/cms/file/2815486131/issues/source?bid=3167167&fileBranchId=3375264#l228)
</details>
I think this got out of sync with SubmitRequest (similarly to RunTimeTest) when we allowed more than one file in the submission, please can you fix?

---

*[cmstestsuite/ReplayContestFromAdapter.py, line 113 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_R-r2-113:-KKsiFQg1ENexcnPYYNm:-995671636) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/ReplayContestFromAdapter.py#L113)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary>
> Codacy Issue found: [Unexpected keyword argument 'filename' in constructor call](https://www.codacy.com/app/s-maggiolo/cms/file/2815486132/issues/source?bid=3167167&fileBranchId=3375264#l113)
</details>
Ditto, you could actually use files instead of files[0] here.

---

*[cmstestsuite/web/__init__.py, line 49 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsi_XAVuR6F_7l3LpY:-KKsi_XAVuR6F_7l3LpZ:-1300937918) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/__init__.py#L49)):*
> ```Python
>     file_names (list): a list of files to pass as POST arguments. Each
>                   entry is a tuple containing two strings: the field
>                   name and the file name to send.
> ```

[(string, string)], an dyou can indent only 4

---

*[cmstestsuite/web/__init__.py, line 116 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsirif7owVr5jpwocv:-KKsirif7owVr5jpwocw:-1108877646) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/__init__.py#L116)):*
> ```Python
>             self.response = session_do_request(self.session, self.url,
>                                                self.data, self.files)
>             self.response.raise_for_status()
> ```

This is different, right? We did not raise for 302 before, or am I missing something?

Also it seems you gave a different meaning to self.redirect_to

---

*[cmstestsuite/web/CWSRequests.py, line 178 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_V-r2-178:-KKsjq3dn4-nOgctk1Oi:45507496) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/CWSRequests.py#L178)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary>
> Codacy Issue found: [__init__ method from a non direct base class 'GenericRequest' is called](https://www.codacy.com/app/s-maggiolo/cms/file/2815486314/issues/source?bid=3167167&fileBranchId=3375264#l178)
</details>
Should it be SubmitRequest.__init__?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/624)*

**Comment by lerks** [comment]
Updated these old commits and added a few new ones that I had lying around.

**Comment by lerks** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmstestsuite/__init__.py, line 78 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKshhmjspJsUx2bvyJH:-KfiLBvx-QsVmribVmVh:b-etx4gr) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/__init__.py#L78)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

What is a session?
</blockquote></details>

Doesn't apply anymore. Plus (as I mentioned in the commit msg) I cleared up the usage of browser vs session.

---

*[cmstestsuite/ReplayContest.py, line 228 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_Q-r2-228:-KfiSecfMiWIsp1xYZIO:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/ReplayContest.py#L228)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

I think this got out of sync with SubmitRequest (similarly to RunTimeTest) when we allowed more than one file in the submission, please can you fix?
</blockquote></details>

Done.

---

*[cmstestsuite/ReplayContestFromAdapter.py, line 113 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_R-r2-113:-KfiSfRXZVidMt3_s8Sh:b-x75zv5) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/ReplayContestFromAdapter.py#L113)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Ditto, you could actually use files instead of files[0] here.
</blockquote></details>

Done (to a reasonable approximation).

---

*[cmstestsuite/web/__init__.py, line 49 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsi_XAVuR6F_7l3LpY:-KfiWxQVncAoddZjgiC2:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/__init__.py#L49)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

[(string, string)], an dyou can indent only 4
</blockquote></details>

Done.

---

*[cmstestsuite/web/__init__.py, line 116 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsirif7owVr5jpwocv:-KfiSLKvJ5TXb3xcFZK3:bc7o3rm) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/__init__.py#L116)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

This is different, right? We did not raise for 302 before, or am I missing something?

Also it seems you gave a different meaning to self.redirect_to
</blockquote></details>

`raise_for_status` only raises for status codes 400 to 599. So the difference is actually the other way around: before we did raise for, like, 301, whereas now we don't anymore.

---

*[cmstestsuite/web/CWSRequests.py, line 178 at r2](https://reviewable.io:443/reviews/cms-dev/cms/624#-KKsAr5rvznK8i5FfX_V-r2-178:-KfiWnuOwIxMH1b3qWJy:bg5gcac) ([raw file](https://github.com/cms-dev/cms/blob/a475e8f97815824a82c3d298a6984b7314cac727/cmstestsuite/web/CWSRequests.py#L178)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Should it be SubmitRequest.__init__?
</blockquote></details>

Not sure. It doesn't appear to use anything from SubmitRequest anywhere, and it actually overwrites most of it fields. I fixed it by doing the opposite: put GenericRequest as its superclass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/624)*

**Comment by stefano-maggiolo** [comment]
Slightly better name for the commit 'varius fixes'?

Apart from that and the two comments, :lgtm: go ahead and submit once fixed

---

Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmstestsuite/web/__init__.py, line 68 at r25](https://reviewable.io:443/reviews/cms-dev/cms/624#-KgsI3D-HRGUbLyi7T67:-KgsI3D-HRGUbLyi7T68:b-uog0fl) ([raw file](https://github.com/cms-dev/cms/blob/c20ef5bc481049aa5c9ca9362f55790c940d34d0/cmstestsuite/web/__init__.py#L68)):*
> ```Python
>         file_names ([(str, str)]): a list of files to pass as POST
>             arguments. Each entry is a tuple containing two strings:
>             the field name and the file name to send.
> ```

nit: "and the file name to send" -> "and the name of the file to send" 

---

*[cmstestsuite/web/AWSRequests.py, line 129 at r25](https://reviewable.io:443/reviews/cms-dev/cms/624#-KgsLBSNspeXRyScImum:-KgsLBSOAIHVh63kRbMA:b-i92cdb) ([raw file](https://github.com/cms-dev/cms/blob/c20ef5bc481049aa5c9ca9362f55790c940d34d0/cmstestsuite/web/AWSRequests.py#L129)):*
> ```Python
>         # Only valid after self.execute()
>         # Parse user test information out of response.
>         soup = BeautifulSoup(self.res_data)
> ```

/home/stefano/github/cms/.cms-venv/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/624#-:-KgsJSOQMra-LuHKq4ZE:bt63un3)*

**Comment by stefano-maggiolo** [comment]
Shall we now use https://pypi.python.org/pypi/future and transition to py3k code?

**Comment by lerks** [comment]
Let's keep this discussion in #286.

**Pull request merged**
