### PR TITLE
Fix a few issues with the new CIDR and ipaddress usage

### PR DESCRIPTION
**Pull request by lerks**
We were using a too recent API of psycopg2, CWS was broken and some
code in cmscontrib had not been updated.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/742)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Did you test this manually?

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmscontrib/ImportContest.py, line 206 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2qUPJ4Ugbbar192Cx:-Kh2qUPJ4Ugbbar192Cy:be0zsvr) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/cmscontrib/ImportContest.py#L206)):*
> ```Python
>                         args["hidden"] = p["hidden"]
>                     if "ip" in p:
>                         args["ip"] = [ipaddress.ip_address(p["ip"])]
> ```

Why ip_address here and ip_network earlier?

---

*[docs/Configuring a contest.rst, line 124 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2o9FDMMbp2Qzzp7Pt:-Kh2o9FDMMbp2Qzzp7Pu:b-3y4wv4) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L124)):*
> ```reStructuredText
> ==========
> 
> Users can log into CWS manually, using their credentials (username and a password), or they can get logged in automatically by CMS based on the IP addresses their requests are coming from.
> ```

I think it sounds better with singular (`the IP address their requests are coming from`)

---

*[docs/Configuring a contest.rst, line 129 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2ooHnLJbWwKkZ01Hn:-Kh2ooHnLJbWwKkZ01Ho:b4jv7r2) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L129)):*
> ```reStructuredText
> ----------------------------------
> 
> If the "IP-based autologin" option in the contest configuration is set, CWS tries to find a user that matches the IP address the request is coming from. If it finds exactly one user, the requester is automatically logged in as that user. If zero or more than one user match, CWS does not let the user in (and the incident is logged to allow troubleshooting).
> ```

There are other occurrences of "IP based" without dash later, maybe try to make them uniform.

---

*[docs/Configuring a contest.rst, line 131 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2obfJGRxoawpmHT8g:-Kh2obfJGRxoawpmHT8h:b-oyylie) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L131)):*
> ```reStructuredText
> If the "IP-based autologin" option in the contest configuration is set, CWS tries to find a user that matches the IP address the request is coming from. If it finds exactly one user, the requester is automatically logged in as that user. If zero or more than one user match, CWS does not let the user in (and the incident is logged to allow troubleshooting).
> 
> In general, each user can have multiple ranges of IP addresses associated to it. These are defined as a list of subnets in CIDR format (e.g., `192.168.1.0/24`). Only the subnets whose mask is maximal (i.e., `/32` for IPv4 or `/128` for IPv6) are considered for autologin purposes (subnets with non-maximal mask are still useful for IP-based restrictions, see below). The autologin will kick in if *any* of the subnets matches the IP of the request.
> ```

Do we require that the /32 or /128 to be spelled out?

---

*[docs/Configuring a contest.rst, line 151 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2qCcVUtqyYP7ETskU:-Kh2qCcVUtqyYP7ETskV:b-mwathf) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L151)):*
> ```reStructuredText
> The following are some common reasons for login failures, all of them coming with some useful log message from CWS.
> 
> - IP address mismatch (with IP based autologin): if IP address doesn't match any subnet of any participation or if it matches some subnets of more than one participation, then the login fails. Note that if the user is using the IP address of a different user, CWS will happily log them in without noticing anything.
> ```

*the* IP address

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/742#-:-Kh2qbe5_qp4sWWo-gUv:bobjwkx)*

**Comment by lerks** [comment]
I tested CWS and AWS manually. I didn't test the importers as I don't know how they work nowadays...

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmscontrib/ImportContest.py, line 206 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2qUPJ4Ugbbar192Cx:-Kh33C_WuNqi047J53fN:b-e9bl14) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/cmscontrib/ImportContest.py#L206)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Why ip_address here and ip_network earlier?
</blockquote></details>

It's supposed to be `network` here as well, nice catch! Changed.

(It didn't actually have any effect, since psycopg2 converts both to the same string and then postgres converts them back to the type it expects)

---

*[docs/Configuring a contest.rst, line 124 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2o9FDMMbp2Qzzp7Pt:-Kh348H99PwOX7Sn0wyA:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L124)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

I think it sounds better with singular (`the IP address their requests are coming from`)
</blockquote></details>

Done.

---

*[docs/Configuring a contest.rst, line 129 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2ooHnLJbWwKkZ01Hn:-Kh348YBFYzgzDRIshW8:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L129)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

There are other occurrences of "IP based" without dash later, maybe try to make them uniform.
</blockquote></details>

Done.

---

*[docs/Configuring a contest.rst, line 131 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2obfJGRxoawpmHT8g:-Kh33sVDB83nGeq2Mb_S:brhsusy) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L131)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Do we require that the /32 or /128 to be spelled out?
</blockquote></details>

If the value is input through AWS one can omit the `/32` or `/128` but then it will be added automatically (i.e., when you hit the "Update" button the value that shows up in the `ip` field has the `/32` or `/128`).

---

*[docs/Configuring a contest.rst, line 151 at r1](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh2qCcVUtqyYP7ETskU:-Kh34fWbKNhItkMgnfTV:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/6b6832d986cebab3dc3b8d321d6f43a900954c5f/docs/Configuring a contest.rst#L151)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

*the* IP address
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/742#-:-Kh32X2bSm8DkQTUOrCP:bg0qbwx)*

**Comment by stefano-maggiolo** [comment]
You can run `cmsImportContest /path/to/con_test -i` to test (well, not now, since that is broken too...)
Answer the comment than :lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmscontrib/ImportContest.py, line 206 at r2](https://reviewable.io:443/reviews/cms-dev/cms/742#-Kh5mXgA4kkhWzxJ2vTE:-Kh5mXgByP353AMfhcba:b-xphn6w) ([raw file](https://github.com/cms-dev/cms/blob/0e6cee6595a428eea141ba8d20164e9e05e91dc8/cmscontrib/ImportContest.py#L206)):*
> ```Python
>                         args["hidden"] = p["hidden"]
>                     if "ip" in p:
>                         args["ip"] = [ipaddress.ip_network(p["ip"])]
> ```

You must allow None as an input value (at least in con_test it is set to null)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/742#-:-Kh5cPqa1iUXPrU4w4on:btavpfr)*

**Comment by lerks** [comment]
Pushed as 825afb83d56660b7c3bffa740aad386f006766ab.

**Pull request closed without merging**
