### PR TITLE
Starting to clean up cmscommon

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/891)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cms/server/contest/handlers/tasksubmission.py, line 414 at r4](https://reviewable.io:443/reviews/cms-dev/cms/891#-L7WM8unegHERgU-hala:-L7WM8unegHERgU-halb:bz0t54n) ([raw file](https://github.com/cms-dev/cms/blob/9771f80ff4607a536fef98e75020622009b4eb4e/cms/server/contest/handlers/tasksubmission.py#L414)):*
> ```Python
>                     task=task, submissions=submissions,
>                     submissions_left=submissions_left,
>                     submissions_download_allowed=self.contest.
> ```

Nit: I find this confusing, and I am surprised that pep8/pylint are ok with it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/891#-:-L7WMmMvDdZUAaLfh81k:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cms/server/contest/handlers/tasksubmission.py, line 414 at r4](https://reviewable.io:443/reviews/cms-dev/cms/891#-L7WM8unegHERgU-hala:-L7Z5voUBgYs875iEfll:bxrjy8z) ([raw file](https://github.com/cms-dev/cms/blob/9771f80ff4607a536fef98e75020622009b4eb4e/cms/server/contest/handlers/tasksubmission.py#L414)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Nit: I find this confusing, and I am surprised that pep8/pylint are ok with it...
</blockquote></details>

Yeah, there's no good way. I'll extract the variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/891)*

**Comment by lerks** [comment]
Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/891)*

**Comment by stefano-maggiolo** [comment]
Merged, thanks

**Pull request closed without merging**
