### PR TITLE
Restore default database pool size and increase pool timeout instead

### PR DESCRIPTION
**Pull request by andreyv**
Large pool size causes increased memory usage through spawned PostgreSQL processes. Tests show that the default pool size achieves the same throughput, but has different response time distribution. To accommodate for this, database pool timeout is increased from 30 to 60 seconds.

Related documentation and warning about user count per server are also adjusted.

See #375 for more information and discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/698)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/698#-:-KbJYdDVCouJh_ZRvxdB:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/698)*

**Comment by stefano-maggiolo** [comment]
Merged

**Comment by andreyv** [comment]
Thanks a lot! :)

**Pull request closed without merging**
