### PR TITLE
Fixed docs for submission format of OutputOnly

### PR DESCRIPTION
**Pull request by akmohtashami**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/719)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
I mean, it's not a fix but an extension, right?

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/719#-:-KdlI7MUwXQttx7MCbQ0:bnfp4nl)*

**Comment by akmohtashami** [comment]
I think the previous description assumes the codenames are 001, 002 , etc. which might not be true.

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
