### PR TITLE
Only copy managers relevant to the submission language

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/908)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cms/grading/TaskType.py, line 95 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/908#-L8DLVl5ELRRzI9SLPaa:-L8DLVl5ELRRzI9SLPab:b8wzhbo) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L95)):*
> ```Python
> 
> def is_manager_for_compilation(filename, language):
>     """Return if a manager should be copied in the compilation sandbox.
> ```

s/if/whether/?

---

*[cms/grading/TaskType.py, line 97 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/908#-L8DLMunBZL_JjlGirhe:-L8DLMunBZL_JjlGirhf:b4clvkr) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L97)):*
> ```Python
>     """Return if a manager should be copied in the compilation sandbox.
> 
>     Only return true for manager required by the language of the
> ```

for *a* manager?

---

*[cms/grading/TaskType.py, line 108 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/908#-L8DJx6_-1JsnCsEJsAE:-L8DJx6_-1JsnCsEJsAF:bayeiam) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L108)):*
> ```Python
>     return (
>         any(filename.endswith(header)
>             for header in language.source_extensions) or
> ```

Wrap *before* binary operators

---

*[cms/grading/TaskType.py, line 110 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/908#-L8DK7oI3H-BTbzUqxd5:-L8DK7oJ5N3QcC9LGbee:bowcusl) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L110)):*
> ```Python
>             for header in language.source_extensions) or
>         any(filename.endswith(source)
>             for source in language.header_extensions) or
> ```

Nit: you called `header` the item of `source_extensions` and `source` the item of `header_extensions`

---

*[cms/grading/tasktypes/Batch.py, line 40 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/908#-L8DKXG9A4KiYS4-9o6m:-L8DKXGA4ic2vV4ykHxo:b83c8oo) ([raw file](https://github.com/cms-dev/cms/blob/a0701c4a9df588356bb9b5ba9dddfd13df0d57e1/cms/grading/tasktypes/Batch.py#L40)):*
> ```Python
>     white_diff_step
> from cms.grading.languagemanager import \
>     LANGUAGES, HEADER_EXTS, SOURCE_EXTS, OBJECT_EXTS, get_language
> ```

Are these values still used anywhere else? Can they be removed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/908)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/grading/TaskType.py, line 95 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DLVl5ELRRzI9SLPaa:-L8DcAhlve1wPnvKYGt1:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L95)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/if/whether/?
</blockquote></details>

Done.

---

*[cms/grading/TaskType.py, line 97 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DLMunBZL_JjlGirhe:-L8DcAUrDDtD7-zHZISi:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L97)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

for *a* manager?
</blockquote></details>

Done.

---

*[cms/grading/TaskType.py, line 108 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DJx6_-1JsnCsEJsAE:-L8DcPjDKBwWPKC6bq4z:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L108)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Wrap *before* binary operators
</blockquote></details>

Done.

---

*[cms/grading/TaskType.py, line 110 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DK7oI3H-BTbzUqxd5:-L8DcQ9lBwxfa5F3QaF2:b2nhroa) ([raw file](https://github.com/cms-dev/cms/blob/e8dcbcd216cfd1aa76d33e5cd978480f9fe1641d/cms/grading/TaskType.py#L110)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Nit: you called `header` the item of `source_extensions` and `source` the item of `header_extensions`
</blockquote></details>

Wow

---

*[cms/grading/tasktypes/Batch.py, line 40 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DKXG9A4KiYS4-9o6m:-L8DcSiSJTqZhqJ2ixxo:b-jnz4rg) ([raw file](https://github.com/cms-dev/cms/blob/a0701c4a9df588356bb9b5ba9dddfd13df0d57e1/cms/grading/tasktypes/Batch.py#L40)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Are these values still used anywhere else? Can they be removed?
</blockquote></details>

Uhm, you were commenting on the pre- version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/908)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/grading/tasktypes/Batch.py, line 40 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DKXG9A4KiYS4-9o6m:-L8DdPGiKa4OHADTgXYM:b-luxxxz) ([raw file](https://github.com/cms-dev/cms/blob/a0701c4a9df588356bb9b5ba9dddfd13df0d57e1/cms/grading/tasktypes/Batch.py#L40)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Uhm, you were commenting on the pre- version.
</blockquote></details>

Yes I was. But you can answer me wherever you want.

Anyways, `HEADER_EXTS` is used by `italy_yaml`, whereas the other ones aren't used by anyone anymore. Up to you whether to delete them or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/908#-:-L8DdhKUYKtvsek5d8s5:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/grading/tasktypes/Batch.py, line 40 at r1](https://reviewable.io:443/reviews/cms-dev/cms/908#-L8DKXG9A4KiYS4-9o6m:-L8De94ei9C8v8tqAuUJ:bxciuh2) ([raw file](https://github.com/cms-dev/cms/blob/a0701c4a9df588356bb9b5ba9dddfd13df0d57e1/cms/grading/tasktypes/Batch.py#L40)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Yes I was. But you can answer me wherever you want.

Anyways, `HEADER_EXTS` is used by `italy_yaml`, whereas the other ones aren't used by anyone anymore. Up to you whether to delete them or not.
</blockquote></details>

Oops, sorry. I thought you were asking to remove the import (which I did). I'll see (low prio) if I can update italy_yaml to use a similar logic, otherwise I'll keep all of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/908)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
