### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
* Removed some old resources.
* Changed some sentences that made me cringe.
* Added a section on the data model of CMS, which might be helpful as
  a primer before other sections start using concepts that have not
  been explained first.
* Noticed that virtualenv + installed doesn't work.
* Added a guide to run non-installed.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/705)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/Creating a contest.rst, line 17 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkPBi4nQRf6eSAWX2R:-KbkPBi4nQRf6eSAWX2S:b-o5mjuy) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Creating a contest.rst#L17)):*
> ```reStructuredText
> ======================================
> 
> CMS philosophy is that, unless you want, it should not change how you develop tasks, or how you store contests, tasks and user information.
> ```

s/CMS/CMS's/ ?

And s/it should not/you should not/ sounds better to me.

---

*[docs/Data model.rst, line 4 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkPzR2EafUM32FcZOR:-KbkPzR2EafUM32FcZOS:bjyl0aa) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L4)):*
> ```reStructuredText
> **********
> 
> CMS is used in many different settings: single onsite contests, with remote participations, short training camps, always on training websites, university assignments... Its data model needs to support all of these, and therefore might be a bit surprising if you only think of the first use case.
> ```

s/always on/always-on/

---

*[docs/Data model.rst, line 6 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkQ9r7ArSu157SNsvC:-KbkQ9r7ArSu157SNsvD:bm8dii1) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L6)):*
> ```reStructuredText
> CMS is used in many different settings: single onsite contests, with remote participations, short training camps, always on training websites, university assignments... Its data model needs to support all of these, and therefore might be a bit surprising if you only think of the first use case.
> 
> In the following, we explain the main objects in CMS' data model.
> ```

s/CMS'/CMS's/ ?

---

*[docs/Data model.rst, line 30 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkQVWLGzchAPXJuFdF:-KbkQVWLGzchAPXJuFdG:b63sm2y) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L30)):*
> ```reStructuredText
> ==================
> 
> A task is one of the problem to solve within a contest. A task cannot be associated to more than one contest, but you can have tasks temporarily not associated to any.
> ```

s/problem/problems/

---

*[docs/Installation.rst, line 269 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkRdN5tM1PESRv56J7:-KbkRdN5tM1PESRv56J8:busf58d) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Installation.rst#L269)):*
> ```reStructuredText
>     ./prerequisites.py build
> 
> There are still a few steps to complete manually in this case. First, make sure that CMS and isolate are in the path, and to create the configuration files:
> ```

s/, and to create/and create/ ?

---

*[docs/Score types.rst, line 13 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkSv8CvDDbhdH4LF68:-KbkSv8CvDDbhdH4LF69:bjmds3i) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Score types.rst#L13)):*
> ```reStructuredText
> ====================
> 
> CMS has built in the following score types: Sum, GroupMin, GroupMul, GroupThreshold.
> ```

s/has built in/ships with/ ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/705#-:-KbkTCiPgP9BIXBvq5oX:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/Creating a contest.rst, line 17 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkPBi4nQRf6eSAWX2R:-Kbo7H1QcEGuJnjRJIdC:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Creating a contest.rst#L17)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/CMS/CMS's/ ?

And s/it should not/you should not/ sounds better to me.
</blockquote></details>

Done.

---

*[docs/Data model.rst, line 4 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkPzR2EafUM32FcZOR:-Kbo7NKkBr912NBCqpKk:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L4)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/always on/always-on/
</blockquote></details>

Done.

---

*[docs/Data model.rst, line 6 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkQ9r7ArSu157SNsvC:-Kbo7PSGWg5WAtF12DaR:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L6)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/CMS'/CMS's/ ?
</blockquote></details>

Done.

---

*[docs/Data model.rst, line 30 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkQVWLGzchAPXJuFdF:-Kbo7SWAGfub8gDfNn7J:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Data model.rst#L30)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/problem/problems/
</blockquote></details>

Done.

---

*[docs/Installation.rst, line 269 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkRdN5tM1PESRv56J7:-Kbo7qHywJuOLBOUqs7w:b-ldytwx) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Installation.rst#L269)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/, and to create/and create/ ?
</blockquote></details>

Changed from passive to active instead

---

*[docs/Score types.rst, line 13 at r1](https://reviewable.io:443/reviews/cms-dev/cms/705#-KbkSv8CvDDbhdH4LF68:-Kbo7yT8AOdtZqmws4-J:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/ce3267bede897adc2c1c5844966a85d0d9cbfb80/docs/Score types.rst#L13)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/has built in/ships with/ ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/705)*

**Comment by lerks** [comment]
Did you maybe forget to push it?

**Comment by stefano-maggiolo** [comment]
Yeah, I was getting in the tube and only manage to publish the comments... done now.

**Comment by lerks** [comment]
Good to go

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/705#-:-KbqhaRJ6tYZAVXFKxJB:b-opoyhd)*

**Pull request closed without merging**
