### PR TITLE
Improve cmstestsuite determinism and usability

### PR DESCRIPTION
**Pull request by bblackham**
These commits add the ability to run individual unit tests, and make the test ordering deterministic (not dependent on filesystem inode ordering). Unfortunately, this also exposes the fact that ImportTaskTest and ImportContestTest can fail unless ImportDatasetTest has run first. And even then, there are some weird dependency issues I haven't figured out yet. So this commit causes the unit tests to fail. But I'm hoping someone else can fix the failure who better understands what exploded! This reproduces it on a fresh database:

`$ TEST_SUITE=unittests cmsRunTests ImportTask
`

If you run the tests in reverse order, they all pass, but I'd prefer to get the failure fixed (presumably before this can be merged!) Or we can not merge the last commit in the sequence (that sorts the tests), but then it's still a ticking time bomb.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/858)

### CODE REVIEW

**Comment by bblackham** [comment]
Well apparently these tests do pass on Travis despite being in the same order that fails for me. So I've now no idea what is causing the tests to fail on my local machine (see attached). I'll file this as a separate issue.

[log.txt](https://github.com/cms-dev/cms/files/1748390/log.txt)

**Comment by stefano-maggiolo** [comment]
Not sure what is happening in your logs, but it doesn't seem to be order-dependent.

It is caused by setting the task id to null when deleting all rows in all tables between unittests, but I don't understand why the task id should be set to null (I'd understand if it was a foreign key and you deleted the referred row before the referring).

**Comment by stefano-maggiolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmstestsuite/RunUnitTests.py, line 176 at r2](https://reviewable.io:443/reviews/cms-dev/cms/858#-L67NcWSQczr1BapUdTS:-L67NcWSQczr1BapUdTT:b-512t32) ([raw file](https://github.com/cms-dev/cms/blob/d87b3b0f22689b5ca1f1411b2b6813268b43cbe5/cmstestsuite/RunUnitTests.py#L176)):*
> ```Python
>         test_list = get_all_tests()
> 
>     if args.regex:
> ```

Can you move the argument definition from the "unused" section and copy the help from the functional tests?

---

*[cmstestsuite/RunUnitTests.py, line 181 at r2](https://reviewable.io:443/reviews/cms-dev/cms/858#-L67NUUEPHz9eGsFigjo:-L67NUUEPHz9eGsFigjp:b-3zmdp5) ([raw file](https://github.com/cms-dev/cms/blob/d87b3b0f22689b5ca1f1411b2b6813268b43cbe5/cmstestsuite/RunUnitTests.py#L181)):*
> ```Python
> 
>         def test_match(t):
>             return any([r.search(t) is not None for r in filter_regexps])
> ```

You can get rid of the []

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/858)*

**Comment by bblackham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmstestsuite/RunUnitTests.py, line 176 at r2](https://reviewable.io:443/reviews/cms-dev/cms/858#-L67NcWSQczr1BapUdTS:-L67goIMHYoeKFzGPRv2:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/d87b3b0f22689b5ca1f1411b2b6813268b43cbe5/cmstestsuite/RunUnitTests.py#L176)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Can you move the argument definition from the "unused" section and copy the help from the functional tests?
</blockquote></details>

Done.

---

*[cmstestsuite/RunUnitTests.py, line 181 at r2](https://reviewable.io:443/reviews/cms-dev/cms/858#-L67NUUEPHz9eGsFigjo:-L67gon9GsTwGe2VeGEj:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/d87b3b0f22689b5ca1f1411b2b6813268b43cbe5/cmstestsuite/RunUnitTests.py#L181)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

You can get rid of the []
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/858)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/858#-:-L6GwQa2Pq9Gmz3mJieK:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged!

**Pull request closed without merging**
