### PR TITLE
Fix broken prerequisites.py introduced by Py2+3 code

### PR DESCRIPTION
**Pull request by wil93**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/856)

### CODE REVIEW

**Comment by lerks** [comment]
Nice catch!

Though, I did the py2->py3 conversion and know that code in and out, and it still took me a bit to realize why this fix was necessary. Can you add a comment explaining it better?

Also, I have personally never seen an except for NameError, it feels a bit weird. I would prefer `if sys.version_info < (3.0): ...`, and maybe you can even put it just around the only instance where we use input.

**Comment by wil93** [comment]
I think I've seen NameError being used in this way before (`statement` without side effect, followed by some action in the right Python version, and the wrong version of Python will throw a NameError) I even remembered it was a NameError without having to look it up... but if you personally prefer a different equivalent implementation you are free to change it :smile:

**Comment by lerks** [comment]
Ok, fine, leave the code as it is but please add a more useful comment.

**Comment by wil93** [comment]
Done

**Comment by lerks** [comment]
Pushed (at last), as 289fbd94b693945418e6116fb27981f32d18257b.

**Pull request closed without merging**
