### PR TITLE
Assume that CMS is installed

### PR DESCRIPTION
**Pull request by wil93**
Depends on #478.

At the moment, CMS checks if it's installed or run directly from source. This is messy because, right now, CMS believes that it's *not* installed when it's installed and run in a virtual environment.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/479)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
I agree it's not the most nice way of doing things, but removing everything doesn't just remove the possibility of running it without having access to /*/local/*/cms?

**Comment by wil93** [comment]
Yes.. maybe we should expand this section from the config

```
"_section": "System-wide configuration",

"temp_dir": "/tmp",
```

to include also "log_dir" and so on...

I think it would be the quickest solution to implement. The best thing to do, however, is probably to just manage the needed directories in a better way (logs, for example, could just be sent to a syslog server, instead of written to a file).

**Comment by stefano-maggiolo** [comment]
Wouldn't it be simpler to find a way of detecting virtualenv + installed?

**Comment by stefano-maggiolo** [comment]
Sorry, even if you have a point re installed in virtualenv not being detected correctly, this breaks other stuff. Closing for now.

**Pull request closed without merging**
