### PR TITLE
Add option to allow / disallow submissions download

### PR DESCRIPTION
**Pull request by artikz**
Admins can control from AWS whether contestants are allowed to download their submissions. This option maybe useful for security reasons.

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Just curious, why do you need this?

**Comment by artikz** [comment]
For example, you gave somebody access to CMS to solve a problem and he submitted several solutions. Then username and password of the somebody were stolen by another somebody. I don't want that another somebody to be able to get anything from this :)

It doesn't meant to use in a real supervised contest, more in a contest where you don't have control on who has access to the system and whether they exchange their credentials (voluntarily or unintentionally).

**Comment by wil93** [comment]
I, for one, needed this option sometime ago (and I ended up editing ContestWebServer.py by raising a 403 error if a user *which wasn't hidden* tried to download a submission)

**Comment by stefano-maggiolo** [comment]
Make sense. Merged: c8c3a4b37a10589a72d12a0badee0c8c448af227

**Pull request closed without merging**
