### PR TITLE
Couple of changes to DB relationships

### PR DESCRIPTION
**Pull request by lerks**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/925)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 6 of 6 files at r1, 31 of 31 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cms/db/task.py, line 247 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WbXMyDX1mDJ56Ireo:-L9WbXMyDX1mDJ56Irep:bcponq2) ([raw file](https://github.com/cms-dev/cms/blob/28face4d23ef373bd181a7f817cca3a7dce31dc6/cms/db/task.py#L247)):*
> ```Python
>     datasets = relationship(
>         "Dataset",
>         foreign_keys="[Dataset.task_id]",
> ```

[Discussed offline]: put a comment on why we need it.

---

*[cms/db/user.py, line 258 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WbBqI9yBhnghx7GMC:-L9WbBqI9yBhnghx7GMD:b-hflw8j) ([raw file](https://github.com/cms-dev/cms/blob/28face4d23ef373bd181a7f817cca3a7dce31dc6/cms/db/user.py#L258)):*
> ```Python
>     messages = relationship(
>         "Message",
>         order_by="Message.timestamp",
> ```

`[Message.timestamp]`?

---

*[cms/db/validation.py, line 78 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WczUk8ab6mJunZZdD:-L9WczUk8ab6mJunZZdE:b4yl73b) ([raw file](https://github.com/cms-dev/cms/blob/595c1d630c5a496916d25f4d5435736e3e047f39/cms/db/validation.py#L78)):*
> ```Python
>         # This works for (in)equality but, as the order of the operands
>         # is preserved, it doesn't work for regexp matching, where the
>         # syntax is "<text> ~ <pattern>". Our regexp is so simple we
> ```

s/so simple/only checks each character on its own/

---

*[cms/server/admin/templates/task.html, line 132 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WdW2Z3uQa8F47ZE39:-L9WdW2Z3uQa8F47ZE3A:bxfs0t1) ([raw file](https://github.com/cms-dev/cms/blob/8b68cd5d45a9bd6a91b9d4980ccd5a1d5badc9b0/cms/server/admin/templates/task.html#L132)):*
> ```HTML
>         </td>
>         <td>
>           <input type="text" name="submission_format" value="{{ task.submission_format|map(attribute="filename")|list|tojson|forceescape }}"/>
> ```

Change help text too

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/925)*

**Comment by lerks** [comment]
PTAL

---

Review status: 32 of 36 files reviewed at latest revision, 4 unresolved discussions.

---

*[cms/db/task.py, line 247 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WbXMyDX1mDJ56Ireo:-L9Z8N4yEx05BBglzu1M:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/28face4d23ef373bd181a7f817cca3a7dce31dc6/cms/db/task.py#L247)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

[Discussed offline]: put a comment on why we need it.
</blockquote></details>

Done.

---

*[cms/db/user.py, line 258 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WbBqI9yBhnghx7GMC:-L9Z7xn1B4KdjA7Omub5:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/28face4d23ef373bd181a7f817cca3a7dce31dc6/cms/db/user.py#L258)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

`[Message.timestamp]`?
</blockquote></details>

Done.

---

*[cms/db/validation.py, line 78 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WczUk8ab6mJunZZdD:-L9Z7wLzCAsTCu3T_IFz:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/595c1d630c5a496916d25f4d5435736e3e047f39/cms/db/validation.py#L78)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

s/so simple/only checks each character on its own/
</blockquote></details>

Done.

---

*[cms/server/admin/templates/task.html, line 132 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/925#-L9WdW2Z3uQa8F47ZE39:-L9Z7wwa6AeKuMna1_tA:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/8b68cd5d45a9bd6a91b9d4980ccd5a1d5badc9b0/cms/server/admin/templates/task.html#L132)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Change help text too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/925#-:-L9Z8Oln5UX_0aSC1OQx:bb71pro)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/925#-:-L9g7dN29-kZt4Tcgukk:bnfp4nl)*

**Comment by lerks** [comment]
Merged.

**Pull request closed without merging**
