### PR TITLE
Updated Spanish translation

### PR DESCRIPTION
**Pull request by elsantodel90**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1045)

### CODE REVIEW

**Comment by lerks** [comment]
I quickly looked at the file and it appears that at the end you commented out some translations for messages that are still in use (this means that these translations won't be built and won't be used). Is this on purpose?

**Comment by elsantodel90** [comment]
mmm no, I'll have to give it a look. I did not edit the file directly but used "poedit" instead, but based on what I saw, I did not notice that I had actually removed translations. I'll probably be giving it a manual check tomorrow to make sure the translation is ok and does not erase or comment translations. If necessary will commit again.

**Comment by elsantodel90** [comment]
I checked, and those commented lines at the end are automatically generated by the update_catalog command:

(cms-traducir) santo@elaine:~/repos/git/cms$ ./setup.py update_catalog -l es
/home/santo/.virtualenvs/cms-traducir/local/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '1.4.rc0' to '1.4rc0'
  normalized_version,
running update_catalog
updating catalog cms/locale/es/LC_MESSAGES/cms.po based on cms/locale/cms.pot

Maybe those are strings that previously existed in cms, but changed or are not used like that anymore, and since there was a translation, the update_catalog command comments them instead of deleting them?

I am not familiar enough with cms code to directly check whether those strings still exists or it is ok that they are commented, but I confirm that their "commenting" is done automatically by update_catalog. I then just translated all missing items using "poedit" on the resulting "cms.po" file.

For example, "Test too big!" appears in the codebase in "./cms/server/contest/submission/workflow.py", however it is not present in the "cms/locale/cms.pot" file.

**Comment by elsantodel90** [comment]
Created a new pull request merging into the master branch.

**Pull request closed without merging**
