### PR TITLE
Fix the trouble with the dates past Y2k38

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Only last commit is useful, but injecting the other two to have tests.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/877)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Fixes #848

**Comment by lerks** [comment]
If you didn't include the two commits of #876 in here too you would have a LGTM by now :P

**Comment by stefano-maggiolo** [comment]
Rebasing to master to see reports...

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
