### PR TITLE
Add basic registration form

### PR DESCRIPTION
**Pull request by wil93**
I think the absence of this feature is hindering CMS adoption to a too great extent.

This PR introduces a new setting (defaults to False) for contests: `allow_registration`. If enabled, it will let users autonomously choose a password, create an account and participate in the contest.

The admin is thus freed from the responsibility to:

- create the account
- communicate the credentials

Screenshots:

screenshot from 2018-11-05 03-36-10
screenshot from 2018-11-05 03-37-06
screenshot from 2018-11-05 03-37-30

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1067)

### CODE REVIEW

**Comment by wil93** [comment]
I think this PR is ready for review again :smile:

**Comment by wil93** [comment]
I rebased on master so the localization messages should be correct now

**Comment by wil93** [comment]
Please check the cms.pot file because I think it's still missing something.
Maybe you Luca can try to regenerate it

**Comment by stefano-maggiolo** [comment]
Yeah, I was going to merge this yesterday, but doing it today.

**Comment by stefano-maggiolo** [comment]
Reverting the pot before merging due to #1096

**Comment by stefano-maggiolo** [comment]
Merged ;p

**Pull request closed without merging**
