### PR TITLE
Some fixes to the documentation

### PR DESCRIPTION
**Pull request by wil93**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/669)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/Installation.rst, line 58 at r1](https://reviewable.io:443/reviews/cms-dev/cms/669#-KVaV27GJM2rvC7QWRvo:-KVaV27GJM2rvC7QWRvp:b8axkiy) ([raw file](https://github.com/cms-dev/cms/blob/732ced6060523c95d09293e9bf029475d81fa04e/docs/Installation.rst#L58)):*
> ```reStructuredText
>     sudo apt-get install build-essential fpc postgresql postgresql-client \
>          gettext python2.7 iso-codes shared-mime-info stl-manual cgroup-lite \
>          git
> ```

Why git?

---

*[docs/Installation.rst, line 266 at r1](https://reviewable.io:443/reviews/cms-dev/cms/669#-KZ2m9fzeI04jtRcTllU:-KZ2m9fzeI04jtRcTllV:b-5tj595) ([raw file](https://github.com/cms-dev/cms/blob/732ced6060523c95d09293e9bf029475d81fa04e/docs/Installation.rst#L266)):*
> ```reStructuredText
>     # sudo apt-get install python-yaml python-sphinx python-cups python-pypdf2
> 
> Method 3: Using ``pacman`` on Arch Linux
> ```

Should this be Method 4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/669)*

**Comment by wil93** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/Installation.rst, line 58 at r1](https://reviewable.io:443/reviews/cms-dev/cms/669#-KVaV27GJM2rvC7QWRvo:-KZ2mh6QX4LHIxk7QcLf:bjrvthw) ([raw file](https://github.com/cms-dev/cms/blob/732ced6060523c95d09293e9bf029475d81fa04e/docs/Installation.rst#L58)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Why git?
</blockquote></details>

It's probably because I had to do `git submodule update --init` during the installation

---

*[docs/Installation.rst, line 266 at r1](https://reviewable.io:443/reviews/cms-dev/cms/669#-KZ2m9fzeI04jtRcTllU:-KZ2rxHG-OOq5s9pRB-m:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/732ced6060523c95d09293e9bf029475d81fa04e/docs/Installation.rst#L266)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Should this be Method 4?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/669)*

**Comment by wil93** [comment]
I just fixed conflicts (even though it would have been easier to just merge this PR before #705, oh well...)

Pls merge? :smile:

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
