### PR TITLE
Introduce teams and enable ProxyService to send team data

### LINKED ISSUE #65: Align contest data between CMS and RWS (i.e. make CMS team-aware)
At the moment CMS doesn't support teams, because they're not needed to run the contest. RWS is the only piece of CMS that supports them, because the ranking is the only part where they make sense. 

That means that SS isn't able to send team data to RWS (even if it sends everything else) and contest administrators need to insert it manually, by creating some JSON files for the teams and editing JSON files for the users.

We may want to align the contest data that these two "instances" have, and the only way I see to achieve that is to make CMS team-aware, i.e. add a Team class to the DB model.

### PR DESCRIPTION
**Pull request by wil93**
Fixes #65.
Depends on ~~#472~~ and ~~#480~~.

No more need to touch `/teams/` and `/users/`, they are now completely automated :smile:. Now it's enough to provide `/faces/` and `/flags/`.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/481)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Not sure I'll get to it soon, but can you at least clean up the history and rebase (remving the merged commits)?

**Comment by wil93** [comment]
Done :smile:

**Comment by stefano-maggiolo** [comment]
Please also note that jenkins is failing on this: http://cms.di.unipi.it/jenkins/view/PR/job/cms.cms-dev.pr481/3/console

**Comment by stefano-maggiolo** [comment]
Rebase? :P

**Comment by stefano-maggiolo** [comment]
After which I'll look at this, I promise.

**Comment by stefano-maggiolo** [comment]
Also, tests are still failing: http://cms.di.unipi.it/jenkins/job/cms.cms-dev.pr481/7/console

**Comment by wil93** [comment]
Rebased.

As for the tests: honestly I don't understand why they fail... especially since jenkins seem to fail on ProxyService, while on my laptop the fail was on RankingWebServer (and, after the rebase, it's now on AdminWebServer). Any idea where to look?

**Comment by wil93** [comment]
Nevermind, running the tests a second time (after the rebase, of course) seem to have done something useful. Now I also fail on ProxyService. I will look more into it.

**Comment by wil93** [comment]
Tests should be fine now :stuck_out_tongue:

**Comment by stefano-maggiolo** [comment]
Ok, first pass. I carefully looked only at the core part, and left some comments on the loader part, which I recommend you to split in different commits (also if you added some other functionality, like the "hidden" thing, just split it to another commit).

You can rebase, I'm trying reviewing this in reviewable and supposedly should handle rebases. Let's give it a try.


---

Reviewed 4 of 14 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: 8 of 14 files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

<sup>**[cms/db/user.py, line 116 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1Tjy8eTyrs1_9MJs3h)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L116)):</sup>
Can you expand this a little bit to say what is a "team"? Something like this:

> A team is a way of grouping the users participating in a contest. This grouping has no effect on the contest itself; it is only used for display purposes in RWS. 


---

<sup>**[cms/db/user.py, line 122 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1ToZIcZUVz-L5VZku5)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L122)):</sup>
Since code is unique anyway, why not using that as primary key?


---

<sup>**[cms/db/user.py, line 127 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TnkiM4t7CFlRaO13u)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L127)):</sup>
"e.g. ISO 3166-1 code of a country"


---

<sup>**[cms/db/user.py, line 133 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TnuhK7IanpNfALO52)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L133)):</sup>
"e.g. ISO 3166-1 short name of a country"


---

<sup>**[cms/db/user.py, line 137 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TwsY1Wba6-8XTGcEd)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L137)):</sup>
Maybe add a TODO for storing flags in this object.


---

<sup>**[cms/db/user.py, line 218 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1To5G8zT5mbq0fs-hF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L218)):</sup>
We always use "the user" in the comments of this class.


---

<sup>**[cms/db/user.py, line 222 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TxH_7j-pGzC5DB-KF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L222)):</sup>
So teams are shared between contests, and if I delete a team, all participations on that team will be also deleted? This seems quite dangerous (and in general not something an admin would like to do). I would at least use ondelete RESTRICT.

I guess that this doesn't justify per-contest teams...


---

<sup>**[cms/db/user.py, line 224 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TypAAtf0zJ3694TZS)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L224)):</sup>
Do we need an index here? I don't think you ever use it.


---

<sup>**[cms/server/admin/templates/participation.html, line 66 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1Tro9d3uCmpu2MQaq7)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/server/admin/templates/participation.html#L66)):</sup>
It would be nice to see also the name - codes can be tricky.


---

<sup>**[cms/service/ProxyService.py, line 369 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TyWFf6Fh8s8fKG7Qr)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/service/ProxyService.py#L369)):</sup>
Don't you need to sent teams first?


---

<sup>**[cmscontrib/AddContest.py, line 82 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UJkLEuuuUirRLPExE)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L82)):</sup>
Can you keep the changes to the loaders independent from those to the db and core (as in, two separate commits)?


---

<sup>**[cmscontrib/AddContest.py, line 160 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPAV0hLlNX5WlgtGo)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L160)):</sup>
you can use p.get("team") everywhere instead of this.


---

<sup>**[cmscontrib/AddContest.py, line 190 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPIKeaj6tAIVMF7oE)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L190)):</sup>
Split commits by functionality please! Also, do we document anywhere all of these parameters?


---

<sup>**[cmscontrib/AddTeam.py, line 9 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQYbk-GTeCdyoy6R0)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L9)):</sup>
Remove all other names.


---

<sup>**[cmscontrib/AddTeam.py, line 25 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UR4JgNQ_APKchDwAF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L25)):</sup>
This is quite different from all other Add<Object> scripts, which add a single object using data from the command line. Why do you need importing all teams using a loader anyway, isn't that ContestImporter's job?


---

<sup>**[cmscontrib/AddTeam.py, line 60 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQctusPYJsBAQD6Mr)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L60)):</sup>
class TeamImporter(object):
    """Script to create a team in the database."""


---

<sup>**[cmscontrib/AddTeam.py, line 68 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQk5R9wsV-e_LmhlT)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L68)):</sup>
No need for whitelines around pydoc comments.


---

<sup>**[cmscontrib/AddTeam.py, line 89 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQnvD-7vzULohhCRL)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L89)):</sup>
But the """...""" syntax is only allowed if it fits in a line, otherwise you need the 

```python
    """...
    ...

    """
```


---

<sup>**[cmscontrib/loaders/base_loader.py, line 232 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPurU43Q_hC4foUYX)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/loaders/base_loader.py#L232)):</sup>
No, please, if you change the loader interface, you need to change it for all the loaders.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/481)

**Comment by wil93** [comment]
Review status: 5 of 15 files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

<sup>**[cms/db/user.py, line 116 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1Tjy8eTyrs1_9MJs3h)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L116)):</sup>
Done.


---

<sup>**[cms/db/user.py, line 122 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1ToZIcZUVz-L5VZku5)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L122)):</sup>
This is debatable, to some extent. In general I think it's good *not to care* about what the primary key is. This way you don't have to update anything if you change, say, the "US" code to "USA", since all the other references point to, say, Team(id=8) and not to Team(code="US").

So I'd say: the code is unique, yes, but I'm not sure it won't ever be modified.


---

<sup>**[cms/db/user.py, line 127 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TnkiM4t7CFlRaO13u)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L127)):</sup>
Done.


---

<sup>**[cms/db/user.py, line 133 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TnuhK7IanpNfALO52)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L133)):</sup>
Done.


---

<sup>**[cms/db/user.py, line 137 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TwsY1Wba6-8XTGcEd)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L137)):</sup>
Done.


---

<sup>**[cms/db/user.py, line 218 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1To5G8zT5mbq0fs-hF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L218)):</sup>
Done.


---

<sup>**[cms/db/user.py, line 222 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TxH_7j-pGzC5DB-KF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L222)):</sup>
Done. It was a copy-paste leftover.


---

<sup>**[cms/db/user.py, line 224 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TypAAtf0zJ3694TZS)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L224)):</sup>
Done. Copy-paste as well.


---

<sup>**[cms/server/admin/templates/participation.html, line 66 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1Tro9d3uCmpu2MQaq7)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/server/admin/templates/participation.html#L66)):</sup>
Yeah but I'm not sure it can be done easily... I vote to push this to "later" :stuck_out_tongue: 


---

<sup>**[cms/service/ProxyService.py, line 369 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1TyWFf6Fh8s8fKG7Qr)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/service/ProxyService.py#L369)):</sup>
Done. However I think it wasn't really an issue, technically (tasks/users/teams are quite independent in RWS).


---

<sup>**[cmscontrib/AddContest.py, line 82 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UJkLEuuuUirRLPExE)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L82)):</sup>
Done.


---

<sup>**[cmscontrib/AddContest.py, line 160 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPAV0hLlNX5WlgtGo)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L160)):</sup>
Done (not tested, though). Good to know :smile: 


---

<sup>**[cmscontrib/AddContest.py, line 190 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPIKeaj6tAIVMF7oE)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L190)):</sup>
Done. The paramers are the same that can be found in contest.yaml "users" array.


---

<sup>**[cmscontrib/AddTeam.py, line 9 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQYbk-GTeCdyoy6R0)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L9)):</sup>
Done.


---

<sup>**[cmscontrib/AddTeam.py, line 25 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UR4JgNQ_APKchDwAF)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L25)):</sup>
Mmm I see cmsAddTeam as being very similar to cmsAddUser, actually. The italy_yaml format saves teams in contest.yaml (like users) but that could not be the case, in general. One day there could be a "teams/" folder with flags and such.


---

<sup>**[cmscontrib/AddTeam.py, line 60 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQctusPYJsBAQD6Mr)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L60)):</sup>
Done.


---

<sup>**[cmscontrib/AddTeam.py, line 68 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQk5R9wsV-e_LmhlT)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L68)):</sup>
Done.


---

<sup>**[cmscontrib/AddTeam.py, line 89 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UQnvD-7vzULohhCRL)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddTeam.py#L89)):</sup>
Done.


---

<sup>**[cmscontrib/loaders/base_loader.py, line 232 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPurU43Q_hC4foUYX)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/loaders/base_loader.py#L232)):</sup>
Done (not tested, though).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/481)

**Comment by wil93** [comment]
I added updater_18.py, just in case. It wasn't strictly necessary but I saw that the updater script is used even if it does nothing, so I added it. I used 18 because #483 already uses 17. Thus, this PR now depends on #483.

**Comment by stefano-maggiolo** [comment]
Feel free to use 17, this will probably go in first. I'd really like to see a simple team editor in AWS. Can you promise you'll do it soon? If so, once you complete the small nits of this last review I think this is ready.


---

Reviewed 10 of 14 files at r1, 6 of 6 files at r4.
Review status: 15 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[cms/db/user.py, line 122 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1ToZIcZUVz-L5VZku5)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/db/user.py#L122)):</sup>
Fair enough. [Specifically for the case you mention, we have onupdate cascade that should take care of it. But I see future-proofness as a motivation for keeping the autoincrement key.]


---

<sup>**[cms/server/admin/templates/participation.html, line 66 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1Tro9d3uCmpu2MQaq7)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cms/server/admin/templates/participation.html#L66)):</sup>
Ok, I guess together with all editing interface for teams... :P


---

<sup>**[cmscontrib/AddContest.py, line 160 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPAV0hLlNX5WlgtGo)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L160)):</sup>
Can you test at least importing something without teams? I'm unsure of filter(Team.code == p.get("team"))


---

<sup>**[cmscontrib/AddContest.py, line 188 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K3JBFSIY8R-5asjlY8X)** ([raw file](https://github.com/cms-dev/cms/blob/8a6e53b271b99dda07d91f3114ac484249ca9efb/cmscontrib/AddContest.py#L188)):</sup>
Seems that some tabs slipped in.


---

<sup>**[cmscontrib/loaders/base_loader.py, line 232 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPurU43Q_hC4foUYX)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/loaders/base_loader.py#L232)):</sup>
I don't think that team is required, is it?


---

<sup>**[setup.py, line 113 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K3J8RieAJrqu67FmVle)** ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/setup.py#L113)):</sup>
This needs to be moved in the other commit.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/481)

**Comment by wil93** [comment]
Now it's 17. Right now you can change a participation's team using AWS, but you can't add new teams (you can using cmsAddTeam) or delete them. I think I will add a page to add/delete teams in AWS, eventually (possibly in the AWS rewrite? this could be a good argument towards using flask-admin).

---

Review status: 11 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

_[cmscontrib/AddContest.py, line 160 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPAV0hLlNX5WlgtGo:-K3KB9qF7ZBsImVjNvAr:1670836433) ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/AddContest.py#L160)):_
Sine that last comment I tested it and it works. Just to be sure I just tested it again (with some participation having a team and one participation without it) and it worked.

---

_[cmscontrib/AddContest.py, line 188 \[r4\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K3JBFSIY8R-5asjlY8X:-K3KBU-Rebq9iidBeBZA:1758359711) ([raw file](https://github.com/cms-dev/cms/blob/8a6e53b271b99dda07d91f3114ac484249ca9efb/cmscontrib/AddContest.py#L188)):_
Fixed.

---

_[cmscontrib/loaders/base_loader.py, line 232 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K1UPurU43Q_hC4foUYX:-K3KCJIjXFgA9CuD9R0X:-1372986955) ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/cmscontrib/loaders/base_loader.py#L232)):_
Right, I changed it.

---

_[setup.py, line 113 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/481#-K3J8RieAJrqu67FmVle:-K3KDPtHkngDmoB9pHyH:-1642731165) ([raw file](https://github.com/cms-dev/cms/blob/26ebd3fd50a6057086df78da2f1076fcdf2b4fc6/setup.py#L113)):_
Done. Good catch :smile: 

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/481#-:-K3K6mS66qwvGy5srcht:-587268358)_

**Comment by stefano-maggiolo** [comment]
(Finally) Merged! Sorry for the long time it took.

211a65818c0ecf6fc7799159ce37cad93d659c25
f8ba5b98848644a230a8e8492c1af20fa93699b6
b61e37558785081787c8e47b2fbf429abdfb24e9

**Comment by stefano-maggiolo** [comment]
When you have time, would you like to write a page in AWS to manage the teams?

**Pull request closed without merging**
