### PR TITLE
Refactoring of OutputOnly

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Similar to Batch, might want to extract some common code later.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/868)

### CODE REVIEW

**Comment by lerks** [comment]
If I remember correctly the functional tests have no tests for output only tasks. Did you test manually?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cms/grading/tasktypes/OutputOnly.py, line 142 at r2](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67MN4IUXxr-_jJBpTn:-L67MN4IUXxr-_jJBpTo:b-5oudz9) ([raw file](https://github.com/cms-dev/cms/blob/da3bc0a1b93d416c3aae1b791e1843d1242a3008/cms/grading/tasktypes/OutputOnly.py#L142)):*
> ```Python
> 
>         # First and only one step: diffing (manual or with manager).
>         output_digest = job.files["output_%s.txt" %
> ```

Any way this can be exported to a constant too?

---

*[cms/grading/tasktypes/OutputOnly.py, line 191 at r2](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67LcpN-yCjGaGFrYck:-L67LcpN-yCjGaGFrYcl:b-3t5bob) ([raw file](https://github.com/cms-dev/cms/blob/da3bc0a1b93d416c3aae1b791e1843d1242a3008/cms/grading/tasktypes/OutputOnly.py#L191)):*
> ```Python
>             raise ValueError("Unrecognized first parameter "
>                              "`%s' for OutputOnly tasktype. "
>                              "Should be `diff' or `comparator'." %
> ```

Inject constants

---

*[cms/grading/tasktypes/OutputOnly.py, line 136 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67NjnhAbz-hdw7m9EU:-L67NjniNChrFwhj-LpD:bajabhv) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L136)):*
> ```Python
> 
>         user_output_filename = \
>             "output_%s.txt" % job.operation["testcase_codename"]
> ```

Now it's moved to here!

---

*[cms/grading/tasktypes/OutputOnly.py, line 149 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67OlbpiNtDW6u9Ixk2:-L67OlbpiNtDW6u9Ixk3:b-c69dml) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L149)):*
> ```Python
> 
>         # Put input, output and reference solution into the sandbox.
>         sandbox.create_file_from_storage(OutputOnly.INPUT_FILENAME, job.input)
> ```

This means we're putting the input into the sandbox even when we don't need it (say because we're using white_diff). What's the performance impact of that?

---

*[cms/grading/tasktypes/OutputOnly.py, line 152 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67NzQI3dDQqHXH6Dx2:-L67NzQI3dDQqHXH6Dx3:b74a0e1) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L152)):*
> ```Python
>         output_digest = job.files[user_output_filename].digest
>         sandbox.create_file_from_storage(
>             OutputOnly.OUTPUT_FILENAME, output_digest)
> ```

This seems the only place you use `output_digest`, you could avoid creating a variable

---

*[cms/grading/tasktypes/OutputOnly.py, line 205 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67P07L1t_6DFWUIVpu:-L67P07L1t_6DFWUIVpv:b-mqap15) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L205)):*
> ```Python
>             return False, None, []
> 
>         try:
> ```

There wasn't a try before, how come?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/868#-:-L67PRlLW3PoRMbyh6wt:b-qrsk8o)*

**Comment by stefano-maggiolo** [comment]
Right, I'll try.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cms/grading/tasktypes/OutputOnly.py, line 191 at r2](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67LcpN-yCjGaGFrYck:-L67mz0oA-KexG5l5wF_:bgdq6bk) ([raw file](https://github.com/cms-dev/cms/blob/da3bc0a1b93d416c3aae1b791e1843d1242a3008/cms/grading/tasktypes/OutputOnly.py#L191)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Inject constants
</blockquote></details>

It's disappearing anyway

---

*[cms/grading/tasktypes/OutputOnly.py, line 149 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67OlbpiNtDW6u9Ixk2:-L67l9J6kaFNLcW-0VLH:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L149)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

This means we're putting the input into the sandbox even when we don't need it (say because we're using white_diff). What's the performance impact of that?
</blockquote></details>

Done.

---

*[cms/grading/tasktypes/OutputOnly.py, line 152 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67NzQI3dDQqHXH6Dx2:-L67lM6a9W0pcHWI8-MY:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L152)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

This seems the only place you use `output_digest`, you could avoid creating a variable
</blockquote></details>

Done.

---

*[cms/grading/tasktypes/OutputOnly.py, line 205 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67P07L1t_6DFWUIVpu:-L67mTM2pI9ZRieiW2jK:bxukraq) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L205)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

There wasn't a try before, how come?
</blockquote></details>

It's mimicking Batch. Looks sensible to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/868#-:-L67n0pqQ_3HcVX9vp-Y:b-kh52io)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/grading/tasktypes/OutputOnly.py, line 191 at r2](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67LcpN-yCjGaGFrYck:-L67pFNjtDj0FHm7Tu-G:b2ngvnt) ([raw file](https://github.com/cms-dev/cms/blob/da3bc0a1b93d416c3aae1b791e1843d1242a3008/cms/grading/tasktypes/OutputOnly.py#L191)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

It's disappearing anyway
</blockquote></details>

...

---

*[cms/grading/tasktypes/OutputOnly.py, line 205 at r3](https://reviewable.io:443/reviews/cms-dev/cms/868#-L67P07L1t_6DFWUIVpu:-L67pQ7yFLL9BKyG6Pk1:b-1exum8) ([raw file](https://github.com/cms-dev/cms/blob/cd3dee101ead5ef8503fc7ceb89edd1c7440077d/cms/grading/tasktypes/OutputOnly.py#L205)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

It's mimicking Batch. Looks sensible to me.
</blockquote></details>

Yes, I'm totally ok with that, I was wondering if there was anything that changed and made this necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/868#-:-L67pZQV5SR2GDTc7b76:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged. Thanks for reminding me we don't have functional tests.

**Pull request closed without merging**
