### PR TITLE
Add escape around first and last names in RWS.

### PR DESCRIPTION
**Pull request by qnighy**
Since we (Japanese OI committee) use a registration form for online contest, we don't trust neither last names nor first names. This patch adds escapes around first and last names in RWS.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/592)

### CODE REVIEW

**Comment by wil93** [comment]
Why not use the existing [`escape`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) function?

**Comment by wil93** [comment]
Mmm nevermind, escape is not useful here. However [this could be used](https://github.com/mathiasbynens/he) (demo [here](https://mothereff.in/html-entities))

**Comment by qnighy** [comment]
I don't know which way is the best, but I also prepared the one you suggested. The former one is simpler, I think.

**Comment by qnighy** [comment]
We should avoid building raw HTML and use jQuery in the end, but it's too much for this single issue.

**Comment by stefano-maggiolo** [comment]
If I tracked back Hara-san's code correctly, that is used in mustache.js. I would prefer not to pull in another library for just 10 lines of JS, so I'll include the original version.

**Comment by stefano-maggiolo** [comment]
Merged with two changes:
- removed last comma in the map definition (not valid JS);
- added escaping to task and contest names.

**Comment by wil93** [comment]
If #459 is merged then we could easily use the external library

**Pull request closed without merging**
