### PR TITLE
Fix Haskell timeout-cputime test

### PR DESCRIPTION
**Pull request by wil93**
This PR should (hopefully) fix the error in the Travis logs

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1162)

### CODE REVIEW

**Comment by andreyv** [comment]
Looks like the test now fails even with the old Ubuntu version.

**Comment by wil93** [comment]
Yeah 😕 we're looking into it

**Comment by andreyv** [comment]
FWIW, I can't reproduce the failure on a local Ubuntu 18.04 installation. I'll continue later on my side.

I noticed that the program maps 1 TB of virtual memory, which may (or may not) be relevant.

**Comment by wil93** [comment]
It should work now! I rebased the right commit on top of master.

**Comment by andreyv** [comment]
Thanks :) Now it also works with Ubuntu 18.04.

**Comment by andreyv** [comment]
Merged in fe15f9183d4fc6478c506fa18b5da83b2f1bedeb.

**Pull request closed without merging**
