### PR TITLE
Compilation command improvements

### PR DESCRIPTION
**Pull request by andreyv**
- C11/C++11:
  - Enable GNU extensions (default GCC mode).
- Pascal:
  - Reorder flags to follow (preprocessor, compiler, linker) order.
  - Enable symbol stripping.
- Java:
  - Replace `mv` calls with direct output names.
  - Use `/bin/sh` instead of `/bin/bash` for portability.
  - Drop unneeded full paths inside shell commands.
  - Define `eval` system property for evaluation, similar to `-DEVAL`. Can be read with `Boolean.getBoolean("eval")` in the code. Possible alternative name: `cms.eval`.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/899)

### CODE REVIEW

**Comment by andreyv** [comment]
One more possible improvement: escape `executable_filename` in shell commands with `pipes.quote()`/`shlex.quote()`.

**Comment by stefano-maggiolo** [comment]
Thanks, looks good. Couple of comments:
- can you split the first commit in 3 (C/C++, Java, Pascal) since they are pretty much unrelated?
- using quote applies to any language really, right? Am I not seeing a reason for doing it only in Java?

**Comment by andreyv** [comment]
1. Done.
2. Only names that are passed to shell need to be escaped. So far there are only two such commands, both in this file.

**Comment by stefano-maggiolo** [comment]
Right, makes sense. Thank you! :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/899#-:-L7urBKj-GOsUwlZxXV_:beufe9y)*

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
