### PR TITLE
Clearer unofficial submissions in CWS

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1091)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
With both official and unofficial submissions:
2018-12-10-082656_1131x690_scrot

Only with official submissions:
2018-12-10-082728_1146x604_scrot

Only with unofficial submissions (I removed the "yet" since this screenshot)
2018-12-10-082802_1092x648_scrot

**Comment by andreyv** [comment]
Is the "Official" column in the table still needed after the redesign?

**Comment by stefano-maggiolo** [comment]
No, I think I removed it, didn't I?

Btw, if you want to do full review, feel free - @lerks seems a bit overworked :)

**Comment by stefano-maggiolo** [comment]
Per #1096, not regenerating the pot.

**Pull request merged**
