### PR TITLE
Improve comments around sandbox and fix a few PEP8 issues

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Full list of commits this one is part of: https://github.com/stefano-maggiolo/cms/commits/declutter_sandbox

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/933)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cms/grading/__init__.py, line 248 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWDtiCuwk7V4nVVMm:-L9qWDtiCuwk7V4nVVMn:b-1c2mbf) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L248)):*
> ```Python
>     directories, appropriate limits).
> 
>     Terminate early after a command if the sandbox fails, or the command did
> ```

s/did/does/

---

*[cms/grading/__init__.py, line 393 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWlbD6NBimSRAkgem:-L9qWlbD6NBimSRAkgen:bclul2e) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L393)):*
> ```Python
> 
>     sandbox (Sandbox): the sandbox we consider, already created.
>     commands ([[str]]): compilation commands to execute.
> ```

s/compilation/evaluation/

---

*[cms/grading/__init__.py, line 394 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWsCxDyx_pIWt5jxB:-L9qWsCxDyx_pIWt5jxC:b-1o0msn) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L394)):*
> ```Python
>     sandbox (Sandbox): the sandbox we consider, already created.
>     commands ([[str]]): compilation commands to execute.
>     time_limit (float): time limit in seconds (applied to each command); if
> ```

This and `memory_limit` could also be None (in the DB), right? (proper support for them being None is an outstanding bug)

---

*[cms/grading/__init__.py, line 396 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qXA0NDRGGFNc-czfF:-L9qXA0NDRGGFNc-czfG:b-btioke) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L396)):*
> ```Python
>     time_limit (float): time limit in seconds (applied to each command); if
>         non-positive, no time limit is enforced.
>     memory_limit (int): memory limit in MB (applied to each command); if
> ```

s/MB/MiB/

---

*[cms/grading/__init__.py, line 398 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qXJ2C1tR3o4gII3RV:-L9qXJ2C1tR3o4gII3RW:byjyopa) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L398)):*
> ```Python
>     memory_limit (int): memory limit in MB (applied to each command); if
>         non-positive, no memory limit is enforced.
>     allow_dirs ([string]|None): if not None, a list of external
> ```

s/string/str/ (also below)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/933)*

**Comment by stefano-maggiolo** [comment]
PTAL

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/grading/__init__.py, line 248 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWDtiCuwk7V4nVVMm:-L9t6UbO6wLurdEwswgw:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L248)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/did/does/
</blockquote></details>

Done.

---

*[cms/grading/__init__.py, line 393 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWlbD6NBimSRAkgem:-L9t6YB8-EF653TGUoC6:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L393)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/compilation/evaluation/
</blockquote></details>

Done.

---

*[cms/grading/__init__.py, line 394 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWsCxDyx_pIWt5jxB:-L9t6fKxEOQA_pfpaz45:b81yady) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L394)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

This and `memory_limit` could also be None (in the DB), right? (proper support for them being None is an outstanding bug)
</blockquote></details>

As a matter of fact, next commit I was going to send you modifies the default from 0 to None (to mean no limit).

---

*[cms/grading/__init__.py, line 396 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qXA0NDRGGFNc-czfF:-L9t6qHhAUtiJuiBLADU:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L396)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/MB/MiB/
</blockquote></details>

Done.

---

*[cms/grading/__init__.py, line 398 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qXJ2C1tR3o4gII3RV:-L9t6z1j6ibSmMt3qYxc:bb6un1j) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L398)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/string/str/ (also below)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/933#-:-L9t7AEp6yJoUMMaC6Wy:bb71pro)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/grading/__init__.py, line 394 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/933#-L9qWsCxDyx_pIWt5jxB:-L9tCwiBANoFgptzo9b7:b-7jwzas) ([raw file](https://github.com/cms-dev/cms/blob/fa91298e1917015856b26a55bc268d0df683db9e/cms/grading/__init__.py#L394)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

As a matter of fact, next commit I was going to send you modifies the default from 0 to None (to mean no limit).
</blockquote></details>

OK, I'll wait.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/933#-:-L9tD4_F9fjUJiAeLdb7:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
