### PR TITLE
Move submissions_status to AWS

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
There is nothing ES-specific in that RPC (since it just queries the
DB), and ES is already our fatter, resource intensive service. No need
to bother it with things that other services can do.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/709)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Any taker for reviewing this PR?

**Comment by karliss** [comment]
Working on it.

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/admin/server.py, line 85 at r2](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZaV9CuwNLvFrJidtA:-KcZaV9DFHQHKLRNJL6h:baevaw0) ([raw file](https://github.com/cms-dev/cms/blob/5251617cbd871ca11d36487844303a30ba63dc1f/cms/server/admin/server.py#L85)):*
> ```Python
>         self.file_cacher = FileCacher(self)
>         self.admin_web_server = self.connect_to(
>             ServiceCoord("AdminWebServer", 0))
> ```

Does this mean AWS is trying to connect to itself? Plus, I don't see it used anywhere...

---

*[cms/server/admin/server.py, line 160 at r2](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZb8Z8bo8h4n9V_cyg:-KcZb8Z8bo8h4n9V_cyh:b-rsasgt) ([raw file](https://github.com/cms-dev/cms/blob/5251617cbd871ca11d36487844303a30ba63dc1f/cms/server/admin/server.py#L160)):*
> ```Python
>             queries['compiling'] = not_compiled.filter(
>                 SubmissionResult.compilation_tries <
>                 EvaluationService.EvaluationService.MAX_COMPILATION_TRIES)
> ```

It may be good to move these constants to a "higher" place, since now they aren't just used in ES. I don't want you to do it in this PR, but could you add a TODO near their definition (in ES) regarding that?

---

*[cms/server/admin/server.py, line 179 at r3](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZcZLxsqxuebXb8yVK:-KcZcZLyR8mCUg1VOLCM:b-blzy5u) ([raw file](https://github.com/cms-dev/cms/blob/3e056c9cf3041e8bed03cd1015c58379303639e7/cms/server/admin/server.py#L179)):*
> ```Python
>                 .query(func.count(Submission.id))\
>                 .select_from(Submission)\
>                 .join(Task, Submission.task_id == Task.id)
> ```

You may want to filter by contest as well (if given)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/709#-:-KcZcrifkpBhyZhjAuCN:bnfp4nl)*

**Comment by karliss** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/admin/server.py, line 179 at r3](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZcZLxsqxuebXb8yVK:-KcZkCEblC6GQjMXt00j:billv1b) ([raw file](https://github.com/cms-dev/cms/blob/3e056c9cf3041e8bed03cd1015c58379303639e7/cms/server/admin/server.py#L179)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

You may want to filter by contest as well (if given)
</blockquote></details>

Fixing it is not optional because currently all submissions from other contests are counted as "compiling".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/709)*

**Comment by stefano-maggiolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/admin/server.py, line 85 at r2](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZaV9CuwNLvFrJidtA:-KcbnEJ9HLzhjh8NA341:b-4rg1me) ([raw file](https://github.com/cms-dev/cms/blob/5251617cbd871ca11d36487844303a30ba63dc1f/cms/server/admin/server.py#L85)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Does this mean AWS is trying to connect to itself? Plus, I don't see it used anywhere...
</blockquote></details>

It's not trying, it succeed :) It's to allow to call an AWS rpc from the JS. I know a usual handler would be better, but for sake of keeping the diff small I did the slightly dirty thing.

---

*[cms/server/admin/server.py, line 160 at r2](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZb8Z8bo8h4n9V_cyg:-KcbnVk2f9-Cxv-Kaf0C:bg8qgpb) ([raw file](https://github.com/cms-dev/cms/blob/5251617cbd871ca11d36487844303a30ba63dc1f/cms/server/admin/server.py#L160)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

It may be good to move these constants to a "higher" place, since now they aren't just used in ES. I don't want you to do it in this PR, but could you add a TODO near their definition (in ES) regarding that?
</blockquote></details>

Adding a TODO.

---

*[cms/server/admin/server.py, line 179 at r3](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZcZLxsqxuebXb8yVK:-Kcbnrg-ybAugfsFa1Av:b-ucfknh) ([raw file](https://github.com/cms-dev/cms/blob/3e056c9cf3041e8bed03cd1015c58379303639e7/cms/server/admin/server.py#L179)):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Fixing it is not optional because currently all submissions from other contests are counted as "compiling".
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/709)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/server/admin/server.py, line 85 at r2](https://reviewable.io:443/reviews/cms-dev/cms/709#-KcZaV9CuwNLvFrJidtA:-KcxYkYyaYNbZGUKNfyh:bftc2vi) ([raw file](https://github.com/cms-dev/cms/blob/5251617cbd871ca11d36487844303a30ba63dc1f/cms/server/admin/server.py#L85)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

It's not trying, it succeed :) It's to allow to call an AWS rpc from the JS. I know a usual handler would be better, but for sake of keeping the diff small I did the slightly dirty thing.
</blockquote></details>

No comment... :P
Except: add a TODO to clean this up! ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/709#-:-KcxZ9mCYcGdhrx9_hpv:bnfp4nl)*

**Pull request closed without merging**
