### PR TITLE
Allow checker to fork processes

### PR DESCRIPTION
**Pull request by wil93**
We needed this patch when developing a task

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/675)

### CODE REVIEW

**Comment by akmohtashami** [comment]
You can set the max_processes to None to allow unlimited number of processes. However this allows the possibility of unintentionally fork-bombing the workers. So I think it might be reasonable to write a comment explaining why this limit is being set to a big number rather than None.

**Comment by wil93** [comment]
`None` would work for my use case, I just didn't remember that it was a possibility :smile: 

Anyway I can see why one would like to avoid being unintentionally forkbombed by their checker, so it's probably good to just have a big number there...

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/675#-:-KY47eL4kDnYf8VTyYtI:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Just added the justification to "1000" in the comment. Merged.

**Pull request closed without merging**
