### PR TITLE
update setup.py for new scripts & fix typo in script description

### PR DESCRIPTION
**Pull request by myungwoo**
Just simple update.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/551)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Merged, thanks! If you want to add yourself to AUTHORS please do :)

**Comment by myungwoo** [comment]
I'll add me to AUTHORS next time :)
You mean the top content of each files, right?

**Comment by wil93** [comment]
@myungwoo There's also this: https://github.com/cms-dev/cms/blob/master/AUTHORS.txt

**Comment by stefano-maggiolo** [comment]
Yes, I meant AUTHORS.txt but we also encourage developers to add copyright to each file they touch (apart from trivial changes). Thanks!

**Pull request closed without merging**
