### PR TITLE
Admin panel bootstrap 3.3.6

### PR DESCRIPTION
**Pull request by valiro21**
Added boostrap 3.3.6 to admin panel for better aspect for multiple resolutions.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/631)

### CODE REVIEW

**Comment by wil93** [comment]
I think one might want to use https://necolas.github.io/normalize.css instead, which is included in Bootstrap.

**Comment by stefano-maggiolo** [comment]
All in favour of making aws more usable, but I tried this and the only things it seems to change is that it slightly break the left hand panel. Can you give an example where this patch helps?

**Comment by stefano-maggiolo** [comment]
Closing for the moment, if you want to add more info please reopen!

**Comment by valiro21** [comment]
Sorry I didn't respond earlier. It seemed to fix text overlapping on smaller screens for me. I will come back once I can reproduce the problem.

**Pull request closed without merging**
