### PR TITLE
Deduplicate checker code

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Yes, it's in the following PR.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cms/grading/steps/trusted.py, line 58 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5MWsGAKLsrlFdXi7z:-LB6yzGjEspQjg7Sxbcj:b2x952e) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L58)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I think I would prefer if this was passed in by the TaskType when it calls `checker_step`: TaskTypes should be able to provide custom values.

If you decide to go this way, the signature of `checker_step` could be simplified so that it takes the manager's digest and the name it should appear with in the sandbox

Also: the filename in the sandbox and the codename in the job's manager dict don't necessarily have to be same, do they?
</blockquote></details>

For the name: I can make it configurable, but I'd like to keep at least this as default to avoid proliferating of constants with the same value in all our TaskTypes.

For the signature: I was indeed in doubt whether to pass the job, or the manager map, or just the checker's digest. The first I didn't like because steps doesn't feel like something that has to do with Jobs. The third I didn't like because it forced me to handle "checker not found" outside.

As for your third question, no it doesn't need to be the same, but I don't understand what you want me to do about it.

---

*[cms/grading/steps/trusted.py, line 200 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5NC7R05Yab0uMvjDc:-LB72FLeBW3J9fUDW4hE:b-gw9w3v) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L200)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Input and correct output could just be provided as digests, so they can be fetched "fresh" (I wanna say "virgin": is that PC?) from the FileCacher.

PS: you may have already addressed this issue in later PRs, but this is the first one I'm reviewing so I don't know yet...
</blockquote></details>

No I didn't. Yeah, I think that's a good idea since they should always be digests (note that they were fresh anyway, just they were fetched from the digest outside).

---

*[cms/grading/steps/trusted.py, line 227 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5Nx_YC4KZGaot9i6Y:-LB7fkKx1uZOq7UmdIQC:bv3oju0) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L227)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

If you only want to catch the case of a file not found (which is what the comment suggests) you should check the errno and reraise if different than enoent. But maybe it *does* make sense to catch all os errors (in that case, you may want to remove the comment, and maybe use EnvironmentError instead so that you also catch IOErrors).
</blockquote></details>

The problem is, in PY3 FNFE is an OSError, but doesn't have an errno, so it becomes tricky to handle both correctly. I don't particularly want to catch more... 

---

*[cmstestsuite/unit_tests/grading/steps/trusted_test.py, line 37 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5Pjz-6WxMhqSdxLTI:-LB7g1NPD5muJN1B00bh:b-yoh25d) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cmstestsuite/unit_tests/grading/steps/trusted_test.py#L37)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Is there a better way to import `trusted`? Mixing symbols and submodules seems "gross", but I don't know what I would have done instead...
</blockquote></details>

¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950#-:-LB6yx86EQ-ZXvPnB6Dw:b7i4cee)*

**Comment by lerks** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/grading/steps/trusted.py, line 58 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5MWsGAKLsrlFdXi7z:-LB8J_gm9B2thmIg43Yq:bmusym2) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L58)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

For the name: I can make it configurable, but I'd like to keep at least this as default to avoid proliferating of constants with the same value in all our TaskTypes.

For the signature: I was indeed in doubt whether to pass the job, or the manager map, or just the checker's digest. The first I didn't like because steps doesn't feel like something that has to do with Jobs. The third I didn't like because it forced me to handle "checker not found" outside.

As for your third question, no it doesn't need to be the same, but I don't understand what you want me to do about it.
</blockquote></details>

What I was proposing was: this module defines a CHECKER_FILENAME constant, which is the name the checker will be stored as in the sandbox; the function's signature takes just the checker's digest (no dict of the all job's managers, no codename, no filename (the above constant is *always* used)); each TaskType has a CHECKER_CODENAME constant that is used to look up the checker's digest in the job's managers dict.

I understand your objections (mainly the fact that the checker-non-existing check needs to be done outside by each tasktype; I don't buy too much the proliferation of constants) so if you want to keep it this way it's fine.

---

*[cms/grading/steps/trusted.py, line 227 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5Nx_YC4KZGaot9i6Y:-LB8J7oE76BYCdCRcdWZ:bzgbimw) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L227)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

The problem is, in PY3 FNFE is an OSError, but doesn't have an errno, so it becomes tricky to handle both correctly. I don't particularly want to catch more... 
</blockquote></details>

```
In [1]: try:
   ...:     open("nonexisting", "rb").read()
   ...: except OSError as e:
   ...:     print(type(e))
   ...:     print(getattr(e, "errno"))
   ...:
<class 'FileNotFoundError'>
2
```
Maybe it's just the FNFEs that you raise in the mock sandbox that don't have it set?

---

*[cmstestsuite/unit_tests/grading/steps/trusted_test.py, line 250 at r4](https://reviewable.io/reviews/cms-dev/cms/950#-LB8IGDvBioJ76xnIdkB:-LB8IGDwDGAqsz5aFXaz:b-cpmiec) ([raw file](https://github.com/cms-dev/cms/blob/d1d2466a26d4ac2b0eafb98cd7126b9a24c899f8/cmstestsuite/unit_tests/grading/steps/trusted_test.py#L250)):*
> ```Python
>     def setUp(self):
>         super(TestCheckerStep, self).setUp()
>         # By default, this
> ```

Incomplete?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/grading/steps/trusted.py, line 58 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5MWsGAKLsrlFdXi7z:-LB8Xtq12qApCIj3Fw_x:b76mb86) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L58)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

What I was proposing was: this module defines a CHECKER_FILENAME constant, which is the name the checker will be stored as in the sandbox; the function's signature takes just the checker's digest (no dict of the all job's managers, no codename, no filename (the above constant is *always* used)); each TaskType has a CHECKER_CODENAME constant that is used to look up the checker's digest in the job's managers dict.

I understand your objections (mainly the fact that the checker-non-existing check needs to be done outside by each tasktype; I don't buy too much the proliferation of constants) so if you want to keep it this way it's fine.
</blockquote></details>

I forgot to mention: in the case of passing a digest for the checker, I was thinking of allowing none to mean "checker wasn't provided". Would that be ok to you?

---

*[cms/grading/steps/trusted.py, line 227 at r2](https://reviewable.io/reviews/cms-dev/cms/950#-LB5Nx_YC4KZGaot9i6Y:-LB8YTvlA7496RD0_Kou:bis2v2a) ([raw file](https://github.com/cms-dev/cms/blob/193131f44ea191c3c057ea0a1fc6077a8c038bb5/cms/grading/steps/trusted.py#L227)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

```
In [1]: try:
   ...:     open("nonexisting", "rb").read()
   ...: except OSError as e:
   ...:     print(type(e))
   ...:     print(getattr(e, "errno"))
   ...:
<class 'FileNotFoundError'>
2
```
Maybe it's just the FNFEs that you raise in the mock sandbox that don't have it set?
</blockquote></details>

Uhm, I'll try

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cms/grading/steps/trusted.py, line 45 at r6](https://reviewable.io/reviews/cms-dev/cms/950#-LBA_BXg5USvOtHhpIxK:-LBA_BXg5USvOtHhpIxL:b-bgkifs) ([raw file](https://github.com/cms-dev/cms/blob/38d04b522e4285ea7d66ac4cc41b7c9200f28e9f/cms/grading/steps/trusted.py#L45)):*
> ```Python
> 
> import errno
> ```

Can we try to keep the `__future__` and the `future` together (even though technically they are different) and put the stdlib imports later?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950#-:-LBA_MMiEA3JVE-2A4LB:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/grading/steps/trusted.py, line 45 at r6](https://reviewable.io/reviews/cms-dev/cms/950#-LBA_BXg5USvOtHhpIxK:-LBAcNof9OwIukkK7BhI:bgcfcdu) ([raw file](https://github.com/cms-dev/cms/blob/38d04b522e4285ea7d66ac4cc41b7c9200f28e9f/cms/grading/steps/trusted.py#L45)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Can we try to keep the `__future__` and the `future` together (even though technically they are different) and put the stdlib imports later?
</blockquote></details>

Yup, sorry, it's pycharm that keeps adding them in the middle...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/950)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
