### PR TITLE
Fix a bug where Batch task type couldn't be used multiple times

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
@wil93

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/907)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cms/grading/tasktypes/Batch.py, line 295 at r1](https://reviewable.io:443/reviews/cms-dev/cms/907#-L8Bisp9fHT6icVCO2A-:-L8Bisp9fHT6icVCO2A0:b-o3vthu) ([raw file](https://github.com/cms-dev/cms/blob/78cac6a8156c4f9466520b48589c81a3b0df7b7b/cms/grading/tasktypes/Batch.py#L295)):*
> ```Python
>         if len(self.output_filename) == 0:
>             stdout_redirect = self._actual_output
>             files_allowing_write.append(self._actual_output)
> ```

I believe the location of this line contradicts the comment: it should be moved out of the if (either in the else, or just after the block)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/907)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cms/grading/tasktypes/Batch.py, line 295 at r1](https://reviewable.io:443/reviews/cms-dev/cms/907#-L8Bisp9fHT6icVCO2A-:-L8BloWcsClccmyBnv7W:b-6eb4go) ([raw file](https://github.com/cms-dev/cms/blob/78cac6a8156c4f9466520b48589c81a3b0df7b7b/cms/grading/tasktypes/Batch.py#L295)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I believe the location of this line contradicts the comment: it should be moved out of the if (either in the else, or just after the block)
</blockquote></details>

Ops. Might it be why the tests are failing :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/907)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/907#-:-L8C89edhI--8OEoNEeG:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
