### PR TITLE
Couple of TODO solved.

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/501)

### CODE REVIEW

**Comment by giomasce** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/db/submission.py, line 294 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/501#-K4CUj-pZAXlTAbEA718:-K4CUj-pZAXlTAbEA719:347368553) ([raw file](https://github.com/cms-dev/cms/blob/542c9c02728bb9de16170bb7655233c5dbe761cd/cms/db/submission.py#L294)):*
Maybe `failures`? Ok, it is very trivial...

---

*[cms/db/submission.py, line 334 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/501#-K4CUwtdk0lk3cm7oIX1:-K4CUwtdk0lk3cm7oIX2:1663357018) ([raw file](https://github.com/cms-dev/cms/blob/542c9c02728bb9de16170bb7655233c5dbe761cd/cms/db/submission.py#L334)):*
As above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/501)*

**Comment by giomasce** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/501)*

**Comment by stefano-maggiolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[cms/db/submission.py, line 294 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/501#-K4CUj-pZAXlTAbEA718:-K4CcXlvbrPodxc3hWDR:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/542c9c02728bb9de16170bb7655233c5dbe761cd/cms/db/submission.py#L294)):*
Done.

---

*[cms/db/submission.py, line 334 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/501#-K4CUwtdk0lk3cm7oIX1:-K4CcYRtxKQ_1bhOQJQE:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/542c9c02728bb9de16170bb7655233c5dbe761cd/cms/db/submission.py#L334)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/501)*

**Comment by stefano-maggiolo** [comment]
5dc8160a29061f7cf0948de9778414e4a359d5b4
e3641f7f9afbffbd0da80ffa3a329324210db6e4

**Pull request merged**
