### PR TITLE
Finish porting the CWS templates from Tornado to Jinja2

### PR DESCRIPTION
**Pull request by lerks**
This is the third of a series of pull requests that ports CWS's templates from the Tornado engine to Jinja2. This pull request fixes the last outstanding bugs and makes CWS usable again.

After this PR is approved the `jinja` branch will be merged into `master`. I have some further clean-up commits but I will submit them after that.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/847)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 9 of 9 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[cms/server/jinja2_toolbox.py, line 36 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHQc927R_ZMJfCbQG:-L5rHQcAHD6CawTB8mI1:bb76tpr) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L36)):*
> ```Python
> 
> from jinja2 import Environment, StrictUndefined, contextfilter, contextfunction, \
>     environmentfunction
> ```

Wrap

---

*[cms/server/jinja2_toolbox.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHUrd2rhc3jEkNyor:-L5rHUrd2rhc3jEkNyos:b4k2a57) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L148)):*
> ```Python
>     try:
>         return get_task_type(*args, **kwargs)
>     except Exception as err:
> ```

Can we narrow the exception, also below?

---

*[cms/server/jinja2_toolbox.py, line 149 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHiu6-Dc9YIAMza3Z:-L5rHiu6-Dc9YIAMza3_:b-yzfyo8) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L149)):*
> ```Python
>         return get_task_type(*args, **kwargs)
>     except Exception as err:
>         return env.undefined("TaskType not found", exc=err)
> ```

Curious about this: will the exception be reported anywhere (since you're passing it to this function creating an undefined value, I assume)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/847)*

**Comment by lerks** [comment]
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[cms/server/jinja2_toolbox.py, line 36 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHQc927R_ZMJfCbQG:-L5uEaFcyG1k-Gcv2-l8:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L36)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Wrap
</blockquote></details>

Done.

---

*[cms/server/jinja2_toolbox.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHUrd2rhc3jEkNyor:-L5uEaiNKcQBy6PXW1Fo:b-570lhp) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L148)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Can we narrow the exception, also below?
</blockquote></details>

No, because the task/score type's constructor is called, which may raise whatever exception it likes (in fact, score types raise StandardError in some cases when their parameters are malformed).

---

*[cms/server/jinja2_toolbox.py, line 149 at r1](https://reviewable.io:443/reviews/cms-dev/cms/847#-L5rHiu6-Dc9YIAMza3Z:-L5uGwoDo3nARGIHgD7X:b-yfmhjy) ([raw file](https://github.com/cms-dev/cms/blob/287ed99a96452cf132cf08ad1a3cf1956299d3a6/cms/server/jinja2_toolbox.py#L149)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Curious about this: will the exception be reported anywhere (since you're passing it to this function creating an undefined value, I assume)
</blockquote></details>

I actually though so, but since you asked I checked and that is actually not the case. The exc value should be a subclass of UndefinedError and it can be used to provide a custom exception. It is not used for detailed reporting. So I formatted the error into the message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/847)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/847#-:-L5uKZtYc_d-TzSu3zX5:bnfp4nl)*

**Comment by lerks** [comment]
Pushed.

**Pull request closed without merging**
