### PR TITLE
task_score() tests

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @stefano-maggiolo)

---

*[cmstestsuite/unit_tests/databasemixin.py, line 94 at r1](https://reviewable.io/reviews/cms-dev/cms/982#-LGPKW7u1Zqzb1F2_8FZ:-LGPKW7u1Zqzb1F2_8F_:bmrknbu) ([raw file](https://github.com/cms-dev/cms/blob/70e5043dbd5609dd1aa36e24bdd2372e74804b5b/cmstestsuite/unit_tests/databasemixin.py#L94)):*
> ```Python
>         """Create an announcement"""
>         contest = contest if contest is not None \
>             else DatabaseObjectGeneratorMixin.get_contest()
> ```

If we made this a `classmethod` and used `cls` here instead of `DatabaseObjectGeneratorMixin` we would allow subclasses to override some of these methods. That's something we like, don't we?

(I know this was how we did it before, but since you touched the code you brought this to my attention again).

The same holds several times below.

---

*[cmstestsuite/unit_tests/databasemixin.py, line 432 at r1](https://reviewable.io/reviews/cms-dev/cms/982#-LGPLdf28ReA3b1Vl82t:-LGPLdf28ReA3b1Vl82u:b-rsy3vf) ([raw file](https://github.com/cms-dev/cms/blob/70e5043dbd5609dd1aa36e24bdd2372e74804b5b/cmstestsuite/unit_tests/databasemixin.py#L432)):*
> ```Python
>         submission_result = self.get_submission_result(
>             submission, dataset, **kwargs)
>         return submission_result
> ```

I think you accidentally removed the `self.session.add(submission_result)`.

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 34 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPMMGIEiTfrF4UAZV0:-LGPMMGIEiTfrF4UAZV1:b-oyedbd) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L34)):*
> ```Python
> from datetime import timedelta
> 
> from cmstestsuite.unit_tests.databasemixin import DatabaseMixin
> ```

Add comment explaining why it needs to be first?

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 134 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPN_bo0TkJADxg2TEv:-LGPN_bo0TkJADxg2TEw:bx850ci) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L134)):*
> ```Python
>         self.add_result(self.at(1), 44.4, tokened=True)
>         self.add_result(self.at(2), 66.6, tokened=True)
>         self.session.commit()
> ```

I am surprised that you need to commit here: `task_score` never creates a new Session thus it uses the one associated to the objects it receives as inputs; Alchemy flushes the data of a Session before each query thus the database is aware of it when it runs the query (even if the data still only exists inside an uncommitted transaction).

Have you tried without committing? Does it break?

(Holds for all test methods below too)

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 238 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPOVT14eLKk1SyUVOJ:-LGPOVT14eLKk1SyUVOK:bqh7j01) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L238)):*
> ```Python
>         self.add_result(self.at(2), None, tokened=False)
>         self.session.commit()
>         self.assertEqual(self.call(), (0.0, True))
> ```

"Morally", if a submission result already achieved the maximum score, then when using the `max` method `task_score` should not say that the score is partial even when there are unscored submission results. Is it something we take into account and should test for?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed, 5 unresolved discussions (waiting on @lerks and @stefano-maggiolo)

---

*[cmstestsuite/unit_tests/databasemixin.py, line 94 at r1](https://reviewable.io/reviews/cms-dev/cms/982#-LGPKW7u1Zqzb1F2_8FZ:-LGRhczb52YMD6yETAmf:bqv1y5b) ([raw file](https://github.com/cms-dev/cms/blob/70e5043dbd5609dd1aa36e24bdd2372e74804b5b/cmstestsuite/unit_tests/databasemixin.py#L94)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

If we made this a `classmethod` and used `cls` here instead of `DatabaseObjectGeneratorMixin` we would allow subclasses to override some of these methods. That's something we like, don't we?

(I know this was how we did it before, but since you touched the code you brought this to my attention again).

The same holds several times below.
</blockquote></details>

Done in a commit I will keep separate.

---

*[cmstestsuite/unit_tests/databasemixin.py, line 432 at r1](https://reviewable.io/reviews/cms-dev/cms/982#-LGPLdf28ReA3b1Vl82t:-LGRix-63wL9ifl3qebW:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/70e5043dbd5609dd1aa36e24bdd2372e74804b5b/cmstestsuite/unit_tests/databasemixin.py#L432)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I think you accidentally removed the `self.session.add(submission_result)`.
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 34 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPMMGIEiTfrF4UAZV0:-LGRl5hhAYnM9ha_fw6G:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L34)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Add comment explaining why it needs to be first?
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 134 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPN_bo0TkJADxg2TEv:-LGRlVU22sG5pTL3B-iv:b-t7om2w) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L134)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I am surprised that you need to commit here: `task_score` never creates a new Session thus it uses the one associated to the objects it receives as inputs; Alchemy flushes the data of a Session before each query thus the database is aware of it when it runs the query (even if the data still only exists inside an uncommitted transaction).

Have you tried without committing? Does it break?

(Holds for all test methods below too)
</blockquote></details>

Upon lengthy investigation... the simplest that breaks (but there are many) is `TestTaskScoreMax.test_all_submissions_scored`. It adds two submission & results to the session, task_score sees the 2 submissions, but is only able to find the result of the last (that is, get_result() returns None for the first unless there is the commit).

The reason is that before the first query, submissions have no ids; the first query fails but also apparently flushes, so after that ids are present. Might be a bug?

Anyway, if you prefer I can change all the commit() to flush() and avoid the delete_data(). WDYT?

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 238 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPOVT14eLKk1SyUVOJ:-LGRl7Mq97TGUSP5w0Rp:bmq3z3k) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L238)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

"Morally", if a submission result already achieved the maximum score, then when using the `max` method `task_score` should not say that the score is partial even when there are unscored submission results. Is it something we take into account and should test for?
</blockquote></details>

Yeah, I was indeed a bit surprised when writing the test about the unscored but irrelevant submission.

Given it's used only to show a note in the admin ranking, and looking at the max score seems a bit brittle, how about we change the semantic of the return value to say "True if there is at least one submission which hasn't been scored"?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed, 3 unresolved discussions (waiting on @lerks and @stefano-maggiolo)

---

*[cmstestsuite/unit_tests/databasemixin.py, line 81 at r3](https://reviewable.io/reviews/cms-dev/cms/982#-LGS-rOL1XxeGwR4dl6A:-LGS-rOL1XxeGwR4dl6B:b-o1w8t4) ([raw file](https://github.com/cms-dev/cms/blob/f75c593098cd791cf5edc3a5632fa9cdba3a7dc0/cmstestsuite/unit_tests/databasemixin.py#L81)):*
> ```Python
> 
>     @classmethod
>     def get_contest(cls, **kwargs):
> ```

This, `get_user` and `get_task` can actually be static. (I believe that one can override a static method with a class method, right?)

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 134 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPN_bo0TkJADxg2TEv:-LGS1foC5ziHwosGoU_Y:b67rhmv) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L134)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Upon lengthy investigation... the simplest that breaks (but there are many) is `TestTaskScoreMax.test_all_submissions_scored`. It adds two submission & results to the session, task_score sees the 2 submissions, but is only able to find the result of the last (that is, get_result() returns None for the first unless there is the commit).

The reason is that before the first query, submissions have no ids; the first query fails but also apparently flushes, so after that ids are present. Might be a bug?

Anyway, if you prefer I can change all the commit() to flush() and avoid the delete_data(). WDYT?
</blockquote></details>

Thanks for the investigation! I definitely prefer explicit flushing to explicit committing. However, given what you say, I believe the proper solution (that would also benefit the rest of the code) would be to flush in `Base.get_from_id` before accessing any `.id` field. What do you think?

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 238 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPOVT14eLKk1SyUVOJ:-LGS26skC056F9L6vyn7:bhy1qd2) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L238)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Yeah, I was indeed a bit surprised when writing the test about the unscored but irrelevant submission.

Given it's used only to show a note in the admin ranking, and looking at the max score seems a bit brittle, how about we change the semantic of the return value to say "True if there is at least one submission which hasn't been scored"?
</blockquote></details>

Yeah, this is really minor and the fixes aren't elegant (I had never fully realized that maximum scores are only defined per submission, and not per task). I'm ok with leaving it as it is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)*

**Comment by lerks** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @lerks and @stefano-maggiolo)

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 134 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPN_bo0TkJADxg2TEv:-LGUvQNz51IemGTKN_nc:b1beo4u) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L134)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Thanks for the investigation! I definitely prefer explicit flushing to explicit committing. However, given what you say, I believe the proper solution (that would also benefit the rest of the code) would be to flush in `Base.get_from_id` before accessing any `.id` field. What do you think?
</blockquote></details>

Never mind, I thought about this again and I think I prefer that the flushing is done by the code that creates a new object just after it creates it rather than by the code that accesses it. So, in this case, you should just replace the commits by flushes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @stefano-maggiolo)

---

*[cmstestsuite/unit_tests/databasemixin.py, line 81 at r3](https://reviewable.io/reviews/cms-dev/cms/982#-LGS-rOL1XxeGwR4dl6A:-LGWyf9I6U0OoLsT781l:b-y8bjfz) ([raw file](https://github.com/cms-dev/cms/blob/f75c593098cd791cf5edc3a5632fa9cdba3a7dc0/cmstestsuite/unit_tests/databasemixin.py#L81)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

This, `get_user` and `get_task` can actually be static. (I believe that one can override a static method with a class method, right?)
</blockquote></details>

Uhm, sure, whatever. (Yes, you can override.)

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 134 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPN_bo0TkJADxg2TEv:-LGX6yQD2SvJe1Olwl-c:b-y9x8wp) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L134)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Never mind, I thought about this again and I think I prefer that the flushing is done by the code that creates a new object just after it creates it rather than by the code that accesses it. So, in this case, you should just replace the commits by flushes.
</blockquote></details>

Upon deeper investigation: https://groups.google.com/forum/#!topic/sqlalchemy/ocXbxSHF__8 - get() doesn't trigger autoflush, apparently.

More precisely, looking at the code (thanks pycharm that makes it easy!): alchemy receives the get(), looks up in the identity map and doesn't find the object (because ids are not created yet). So it issues the query to the DB; that actually autoflushes, but  I suppose at that point the query issued to postgres only looks at persistent data (?! I didn't follow after that).

Obviously I don't care for this test - I wonder if we'd better switch to a filter() + one_or_none() (it becomes a bit more cumbersome because it needs to be specialized for classes such as SR with multiple fields for primary key). I think we're pretty safe because it seems strange to create an object and get_from_id' it in the same session... Also seems an error that would trigger, not something that stays hidden and happens sporadically.

For this test: I moved to flush() and avoided the delete_data().  

---

*[cmstestsuite/unit_tests/grading/init_test.py, line 238 at r2](https://reviewable.io/reviews/cms-dev/cms/982#-LGPOVT14eLKk1SyUVOJ:-LGXAjTQ4ab4YPDEBL8F:bojo2hs) ([raw file](https://github.com/cms-dev/cms/blob/5e136104f47ab5f5259a087ac9cf2794ef23e010/cmstestsuite/unit_tests/grading/init_test.py#L238)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Yeah, this is really minor and the fixes aren't elegant (I had never fully realized that maximum scores are only defined per submission, and not per task). I'm ok with leaving it as it is.
</blockquote></details>

Would you object changing the semantic like in the previous comment? In a different PR in case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/982)*

**Pull request merged**
