### PR TITLE
Deduplicate the code to store local backups of submissions and user tests

### PR DESCRIPTION
**Pull request by lerks**
And add tests.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/946)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cmstestsuite/unit_tests/server/contest/submission_test.py, line 1250 at r1](https://reviewable.io/reviews/cms-dev/cms/946#-LAs5QS5264J5zYd19-D:-LAs5QS5264J5zYd19-E:b-aajfy1) ([raw file](https://github.com/cms-dev/cms/blob/977891b8be4b3ecc94f0d39e3ca535ac27ee5f8a/cmstestsuite/unit_tests/server/contest/submission_test.py#L1250)):*
> ```Python
>         self.fail("store_local_copy didn't create any file")
> 
>     def test_success(self):
> ```

Maybe a test where you try twice and you check at the end you have both contents?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/946#-:-LAs5d0Z289wD0JdjWMj:bnfp4nl)*

**Comment by lerks** [comment]
PTAL

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/server/contest/submission_test.py, line 1250 at r1](https://reviewable.io/reviews/cms-dev/cms/946#-LAs5QS5264J5zYd19-D:-LAtsvKF9Z4lPM0fgpBw:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/977891b8be4b3ecc94f0d39e3ca535ac27ee5f8a/cmstestsuite/unit_tests/server/contest/submission_test.py#L1250)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Maybe a test where you try twice and you check at the end you have both contents?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/946#-:-LAtswmN-yOysL6D_rVQ:bb71pro)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cmstestsuite/unit_tests/server/contest/submission_test.py, line 1270 at r2](https://reviewable.io/reviews/cms-dev/cms/946#-LAuE8LnDuw1DXnkK2ZJ:-LAuE8LnDuw1DXnkK2ZK:b-4vgznm) ([raw file](https://github.com/cms-dev/cms/blob/45ddb3a7b6e43600aa2f2b1257de7247bb78baad/cmstestsuite/unit_tests/server/contest/submission_test.py#L1270)):*
> ```Python
>         # Giving the same user and timestamp would actually overwrite.
>         store_local_copy(self.base_dir, self.participation, self.task,
>                          self.timestamp + timedelta(seconds=1),
> ```

At least one for with the same name please

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/946#-:-LAuEP8nEe68_49aTWtK:bnfp4nl)*

**Comment by lerks** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/server/contest/submission_test.py, line 1270 at r2](https://reviewable.io/reviews/cms-dev/cms/946#-LAuE8LnDuw1DXnkK2ZJ:-LAuR5U224u8HBbpFnQt:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/45ddb3a7b6e43600aa2f2b1257de7247bb78baad/cmstestsuite/unit_tests/server/contest/submission_test.py#L1270)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

At least one for with the same name please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/946)*

**Pull request merged**
