### PR TITLE
Sweeping queries

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Use SQL queries returning lists of basic types to do the sweeping in ES and SS, instead of using long (as in running time) SQLAlchemy code.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/516)

### CODE REVIEW

**Comment by lerks** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/io/triggeredservice.py, line 132 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CEVvdNJ4zr1lSpxVe:-K7CEVvdNJ4zr1lSpxVf:-1840166628) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/io/triggeredservice.py#L132)):*
Why? Every log message gets already attached to it the "source" (filename, line number) of the call, hence this information could be easily extracted from there, instead of being put in the log message itself. At the moment it seems that such information is just discarded when we format & print the log message, but this could be changed. For example, we could continue to hide it from the AWS logs (because the clueless admin has no interest in knowing in which class that call resides, and could get confused), whereas it could be printed in the file logs. What do you think?

---

*[cms/log.py, line 258 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CFq8NOev92cA3TZdX:-K7CFq8OfTO5lI2Gmidy:100400957) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/log.py#L258)):*
What is this value? Does it bear any meaning or is it just an ID? In any case, it is mainly of interest to developers, not to "clueless admins". I propose a flag is added to this class, say "show_debug", and if activated then this information is shown. That same flag could control whether the filename and line number are printed.

As for the name of the thread, instead of an arbitrary human-unreadable ID I would prefer a codename. We could use a thread-local storage to keep those names, so that every thread with a specific role (say, a sweeper, or a request handler) can at any point set the name in that storage and then this method can retrieve it. (If that name is unset, of course, we fall back on the ID).

---

*[cms/service/EvaluationService.py, line 499 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CGhAbi_JXrVF6el5o:-K7CGhAbi_JXrVF6el5p:-812744328) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/service/EvaluationService.py#L499)):*
Same as above: the location shouldn't always be printed.

---

*[cms/service/EvaluationService.py, line 244 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CIWzZCFu-pwr6ADta:-K7CIWzZCFu-pwr6ADtb:-1346824669) ([raw file](https://github.com/cms-dev/cms/blob/130aa45ba5ca72de5ee94b02867ef030de8d417e/cms/service/EvaluationService.py#L244)):*
I remember wondering what the "post_finish_lock" should be acquired for, and when. If you figured it out (I assume you did, as you're using it), could you please add it as a comment in the __init__? It would also be nice if you could add a comment here on why this lock is needed.

---

*[cms/service/EvaluationService.py, line 455 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CJL_mlZqqTnEqyEcp:-K7CJL_mlZqqTnEqyEcq:-1394803499) ([raw file](https://github.com/cms-dev/cms/blob/5c24716d56ae2552d23174d50f687b0e8b0003ca/cms/service/EvaluationService.py#L455)):*
Why remove a helpful comment? :) And why remove the "> 0"? If I read the line now I wonder what is the meaning of the boolean that gets returned by enqueue...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r4, 3 of 3 files at r5, 6 of 6 files at r6.
Review status: 8 of 11 files reviewed at latest revision, 18 unresolved discussions.

---

*[cms/db/usertest.py, line 351 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CNTPoiVeKeiBehdD8:-K7CNTPoiVeKeiBehdD9:-1563265090) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/db/usertest.py#L351)):*
.isnot(None)? (Not really important; it's just an equivalent ways that avoids the #noqa)

---

*[cms/db/usertest.py, line 402 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7COCc6IujnkEFBXuLP:-K7COCc7h65ixm7WH62N:1662569705) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/db/usertest.py#L402)):*
Same here.

---

*[cms/service/esoperations.py, line 54 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CaigGCZmkB1nKM8rP:-K7CaigGCZmkB1nKM8rQ:-702895052) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L54)):*
Maybe use `Dataset.id` here?

---

*[cms/service/esoperations.py, line 56 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7COfvmIZ_xS6FJ1cNL:-K7COfvmIZ_xS6FJ1cNM:-76887568) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L56)):*
`and_` and `or_` could be used instead and maybe be more clear, I don't know... It's a matter of taste
See http://docs.sqlalchemy.org/en/latest/core/sqlelement.html
And of course is_(True) can again be used.

---

*[cms/service/esoperations.py, line 69 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CmDR6I3Hob85tNH6d:-K7CmDR72RUIKX80CahA:1854746597) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L69)):*
Same here

---

*[cms/service/esoperations.py, line 311 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CmHlL4Eo_iKeMrtGV:-K7CmHlL4Eo_iKeMrtGW:-1427664299) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L311)):*
You could use `.join(Task.datasets)` here. For symmetry I would use this still throughout the code (i.e., in the line before, .join(Submission.task).

---

*[cms/service/EvaluationService.py, line 257 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CpbQTIdHf16ioybLh:-K7CpbQTIdHf16ioybLi:-1513920444) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/EvaluationService.py#L257)):*
enqueue returns an int, so please do sth like "counter += self.enqueue(...)"

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 52 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cpo1CLG0L05U6eRW8:-K7Cpo1CLG0L05U6eRW9:-73308460) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L52)):*
I suggest putting autojudge=False here, to make sure that SRs belonging to this dataset get spotted because it's the active one, and not because it's active

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 79 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cv8uvdwm0JsYS8O70:-K7Cv8uvdwm0JsYS8O71:1298566024) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L79)):*
You're passing False as compilation_outcome (check below to see why it's bad).

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 112 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cq0BN0BLuj514tTJI:-K7Cq0BN0BLuj514tTJJ:-380059011) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L112)):*
Another reason for an operation to get included is for the dataset to be the active one. Since you're doing this check 17 times (I'm not commenting on all of them) I recommend adding a separate function:
def is_to_judge(dataset):
    return dataset.autojudge or dataset is dataset.task.active_dataset

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 270 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CvK71kOogWIRMlCNi:-K7CvK71kOogWIRMlCNj:677068555) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L270)):*
Same

---

*[cmstestsuite/unit_tests/testdbgenerator.py, line 265 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cv4IR9JzdZ5hejcwk:-K7Cv4IStGChA0uLfJ_R:-1829136407) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/testdbgenerator.py#L265)):*
If compilation_outcome is False it still passes this check.

---

*[cmstestsuite/unit_tests/testidgenerator.py, line 26 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cve42lkHDGmNBxFsf:-K7Cve42lkHDGmNBxFsg:582919837) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/testidgenerator.py#L26)):*
Just a note on random (feel free to ignore it): if for some bizarre reason a test fails because of a value that was filled by using one of these functions that failure may be very hard to reproduce. We may consider to be deterministic here...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[cms/service/scoringoperations.py, line 44 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DASPbEC4bzIp-3tBV:-K7DASPbEC4bzIp-3tBW:1797838137) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cms/service/scoringoperations.py#L44)):*
Here as well use Dataset.id

---

*[cms/service/scoringoperations.py, line 61 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DApgR9oWau_q9i2dE:-K7DApgR9oWau_q9i2dF:534909486) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cms/service/scoringoperations.py#L61)):*
If you decide to change the join style (i.e. use Submission.task instead) remember to change it here as well

---

*[cms/service/scoringoperations.py, line 68 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DAfVO5jxg9beJMVvu:-K7DAfVO5jxg9beJMVvv:-1764712840) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cms/service/scoringoperations.py#L68)):*
Don't you want to take these out into a global constant, FILTER_SUBMISSIONS_TO_SCORE, as you did in ES?

---

*[cmstestsuite/unit_tests/service/scoringoperationstest.py, line 50 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DC5KHfVRmVhW3b_mZ:-K7DC5KHfVRmVhW3b_m_:1060819325) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cmstestsuite/unit_tests/service/scoringoperationstest.py#L50)):*
Same as in the other file

---

*[cmstestsuite/unit_tests/service/scoringoperationstest.py, line 111 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DCPaH4Iv_ZIVAZ_SA:-K7DCPaH4Iv_ZIVAZ_SB:814370863) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cmstestsuite/unit_tests/service/scoringoperationstest.py#L111)):*
Same as in the previous commit

---

*[cmstestsuite/unit_tests/service/scoringoperationstest.py, line 116 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DCl4a9JeoLIqqhG3d:-K7DCl4a9JeoLIqqhG3e:-1666910322) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cmstestsuite/unit_tests/service/scoringoperationstest.py#L116)):*
And of course here too

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by stefano-maggiolo** [comment]
So summary:
1. removed the logs commit, will implement something more complete
2. removed the enqueue commit, which was wrong (sorry)
3. created a comment for post_finish_lock
4. fixed ES and SS operations for active datasets not autojudged, and the tests
5. added all the other style suggestions to those queries. 

---

Review status: 3 of 10 files reviewed at latest revision, 20 unresolved discussions.

---

*[cms/db/usertest.py, line 351 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CNTPoiVeKeiBehdD8:-K7LW0_4yGGGib8-oqK3:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/db/usertest.py#L351)):*
Done.

---

*[cms/db/usertest.py, line 402 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7COCc6IujnkEFBXuLP:-K7LWH80HKqdRn1Vi-B1:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/db/usertest.py#L402)):*
Done.

---

*[cms/io/triggeredservice.py, line 132 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CEVvdNJ4zr1lSpxVe:-K7Hrvy4XZCoA4a1gLCs:-1948496584) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/io/triggeredservice.py#L132)):*
1. I agree we could print more in the file and less on stdout and on AWS (thread name could be another example). (note that on aws we are not getting this anyway since it's >= warning)

2. These specific logs are confusing because the terms mean different things in TS and in ES/SS/..., so it is nice (for me, while developing) to have a fast way of knowing the origin, without polluting stdout with the line number and such things.

Anyhow, I removed this commit from the PR, I'll try to do another one with a more complete change that makes you happy.

---

*[cms/service/esoperations.py, line 54 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CaigGCZmkB1nKM8rP:-K7LWbyEFk8HeGlcHw3q:2088190418) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L54)):*
Done. Thanks, this was a mistake.

---

*[cms/service/esoperations.py, line 56 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7COfvmIZ_xS6FJ1cNL:-K7LWebtO2qSo2tiiRmG:44700528) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L56)):*
Agree on not using == True, but I prefer | and &

---

*[cms/service/esoperations.py, line 69 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CmDR6I3Hob85tNH6d:-K7LWko7hiA6REpTLyD2:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L69)):*
Done.

---

*[cms/service/esoperations.py, line 311 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CmHlL4Eo_iKeMrtGV:-K7LWlLmb2_I0rC6ZLCL:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/esoperations.py#L311)):*
Done.

---

*[cms/service/EvaluationService.py, line 499 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CGhAbi_JXrVF6el5o:-K7LAYMSsmRKx5bWnkjB:-303092460) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/service/EvaluationService.py#L499)):*
I disagree. Anyway, I didn't touch these lines in my commits.

---

*[cms/service/EvaluationService.py, line 244 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CIWzZCFu-pwr6ADta:-K7LjS36JHhX-yP1n5zk:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/130aa45ba5ca72de5ee94b02867ef030de8d417e/cms/service/EvaluationService.py#L244)):*
Done.

---

*[cms/service/EvaluationService.py, line 455 \[r3\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CJL_mlZqqTnEqyEcp:-K7LA9L4UoTiy6AnyFiN:-1829704290) ([raw file](https://github.com/cms-dev/cms/blob/5c24716d56ae2552d23174d50f687b0e8b0003ca/cms/service/EvaluationService.py#L455)):*
Because I mistakenly assumed this was another enqueue(), returning a bool. [It is maybe bad that we change the return type, though, overriding TS's int with ES's bool.] Anyway, I removed this commit.

---

*[cms/service/EvaluationService.py, line 257 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CpbQTIdHf16ioybLh:-K7LARtdSPaVvOyf47ia:1571131099) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/EvaluationService.py#L257)):*
Yeah, see later.

---

*[cms/service/scoringoperations.py, line 61 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DApgR9oWau_q9i2dE:-K7LTHfYkk5msEFqhEOl:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cms/service/scoringoperations.py#L61)):*
Done.

---

*[cms/service/scoringoperations.py, line 68 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DAfVO5jxg9beJMVvu:-K7LTj16sD__oUe_nbQv:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cms/service/scoringoperations.py#L68)):*
Done.

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 52 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cpo1CLG0L05U6eRW8:-K7LTmkpCsVhvNxra_a_:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L52)):*
Done.

---

*[cmstestsuite/unit_tests/service/esoperationstest.py, line 112 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cq0BN0BLuj514tTJI:-K7LTrAHjvqNipzVAhxG:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/service/esoperationstest.py#L112)):*
Done.

---

*[cmstestsuite/unit_tests/service/scoringoperationstest.py, line 50 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DC5KHfVRmVhW3b_mZ:-K7LTu8U33WXLvZPgOnX:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cmstestsuite/unit_tests/service/scoringoperationstest.py#L50)):*
Done.

---

*[cmstestsuite/unit_tests/service/scoringoperationstest.py, line 116 \[r7\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7DCl4a9JeoLIqqhG3d:-K7LTx5Wdn33g4SAfBHo:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/bda20d2fef05df6ade7e88e811d94205bdd9f3a3/cmstestsuite/unit_tests/service/scoringoperationstest.py#L116)):*
Done.

---

*[cmstestsuite/unit_tests/testdbgenerator.py, line 265 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cv4IR9JzdZ5hejcwk:-K7LUWkSRjWBew-ryIeZ:-1601089624) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/testdbgenerator.py#L265)):*
Discussed offline, it was intended.

---

*[cmstestsuite/unit_tests/testidgenerator.py, line 26 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Cve42lkHDGmNBxFsf:-K7LV8kERTJBdtqiGoq3:-954168832) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cmstestsuite/unit_tests/testidgenerator.py#L26)):*
Yeah, on the other hand we get more coverage, so I prefer to avoid setting a seed. We could print the random seed every time, but I suspect this won't be necessary and just clutter the output. 

---

*[cms/log.py, line 258 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CFq8NOev92cA3TZdX:-K7HsmPSeGkw7tYNkpwH:2034256103) ([raw file](https://github.com/cms-dev/cms/blob/78f272f23508435207eb658e4a4fe8843b56ce8f/cms/log.py#L258)):*
It's just an ID, no meaning. And it is also of interest when we get logs from other people. As said before, having it printed only on the files could be a better idea. I'll see if we can do it.

Good idea on the local variable, but when should it be set? And how do we prevent overrides?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516#-:-K7LjUJ6jqFmvBsGa7wM:-1094833177)*

**Comment by lerks** [comment]
Reviewed 8 of 8 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7Vw6Tcp5GoEJgkVe9y:318624273) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
You haven't moved to the "new" style (i.e. Task.datasets) in this function

---

*[cms/service/EvaluationService.py, line 257 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CpbQTIdHf16ioybLh:-K7VxpsHvjZUf0lbwERQ:-223078542) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/EvaluationService.py#L257)):*
I've seen but I didn't understand. This code is still here. (I.e. self.enqueue returns an int but you treat is as bool)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
*[cms/service/EvaluationService.py, line 257 \[r6\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7CpbQTIdHf16ioybLh:-K7VzQjxukkz6zHintJJ:1722957292) ([raw file](https://github.com/cms-dev/cms/blob/7cc533b728e4bf5a8a97766ac848f9af21e2e5ad/cms/service/EvaluationService.py#L257)):*
My bad, I misread

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7WcO2tU1HSbF-RHDS9:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7WdDNv7rx4B5JKtSB9:-1222241278) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
Nope, I didn't mean just this line. The previous one as well (UserTest.task) and the other ones I'm now commenting on

---

*[cms/service/esoperations.py, line 433 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7WdNy_cl3qkJrSre-7:-K7WdNy_cl3qkJrSre-8:335217914) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L433)):*
This one, and the two above.

---

*[cms/service/esoperations.py, line 460 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7WdQqxTeKw-fbT4Ws_:-K7WdQqxTeKw-fbT4Wsa:335217914) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L460)):*
This one, and the two above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by stefano-maggiolo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/service/esoperations.py, line 433 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7WdNy_cl3qkJrSre-7:-K7WfX14rThNjBihB_KX:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L433)):*
Done.

---

*[cms/service/esoperations.py, line 460 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7WdQqxTeKw-fbT4Ws_:-K7WfWeVM3UKxrINdj3r:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L460)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by stefano-maggiolo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7WfYgx5SmVS8c2M2rL:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7Wfq_kxfhTq1XBEDQi:5173670) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
No

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by stefano-maggiolo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/service/esoperations.py, line 412 \[r8\]](https://reviewable.io:443/reviews/cms-dev/cms/516#-K7Vw6Tcp5GoEJgkVe9x:-K7Wg16tESYJB3kMh2ax:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/59cf616057ff8fe56d098ee2dd424b1462ef1456/cms/service/esoperations.py#L412)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Comment by lerks** [comment]
Reviewed 1 of 8 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/516)*

**Pull request merged**
