### PR TITLE
Update and clarify documentation for task types.

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[docs/Task types.rst, line 19 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD62y0Y7bf4TtnoM_d3:-LD62y0Z8Vb7ffMUeru5:b2hkgej) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L19)):*
> ```reStructuredText
> ===================
> 
> CMS ships with four task types: Batch, OutputOnly, Communication, TwoSteps. The first three are well tested and reasonably strong against cheating attempts and stable with respect to the evaluation times. TwoSteps is less secure with respect to cheating; it can be used in situations where cheating attempts are unlikely, or at least with strong security-by-obfuscation (that is, with encrypted inputs, outputs, and communication protocols). This doesn't prevent all types of attacks, but provides safety against the easier ones.
> ```

Is this an unavoidable situation or just a limitation of our current implementation?

---

*[docs/Task types.rst, line 59 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD64SF5AciIyfDVFxKd:-LD64SF5AciIyfDVFxKe:b-igrvx7) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L59)):*
> ```reStructuredText
> In an OutputOnly task, contestants can see the input of each testcase, and have to compute offline a correct output.
> 
> In any submission, contestants may submit any subset of testcases. The submission format therefore must contain one element for each testcase, and the elements must be of the form :file:`output_{codename}.txt` where :samp:`{codename}` is the codename for the testcase.
> ```

s/submit any/submit outputs for any/ ?

---

*[docs/Task types.rst, line 84 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD64z0-DTdTgeJu0hhk:-LD64z0-DTdTgeJu0hhl:b22a07e) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L84)):*
> ```reStructuredText
> - the second is where the contestant's code runs, after being compiled together with an admin-provided stub that helps with the communication with the first process; it doesn't have access to the input, just to what the manager communicates.
> 
> This setup ensure that the contestant's code cannot access forbidden data, even in the case they have full knowledge of the admin code.
> ```

s/ensure/ensures/

---

*[docs/Task types.rst, line 105 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD65j79-E8c-WNoFASW:-LD65j79-E8c-WNoFASX:b-o985yc) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L105)):*
> ```reStructuredText
> --------
> 
> .. warning:: This task type is not secure in most cases; the user source could intercept the main function and take control of input reading and communication between the processes, which is not monitored.
> ```

I was wondering, couldn't TwoSteps be implemented safely as a Communication with num_processes == 2?

---

*[docs/Task types.rst, line 115 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD661Na12riBv4rw4hx:-LD661Na12riBv4rw4hy:bpboyfz) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L115)):*
> ```reStructuredText
> More precisely, the executable is called with two arguments: the first is an integer which is 0 if the executable is the computer, and 1 if it is the retriever; the second is the name of the pipe to be used for communication between the processes.
> 
> TwoSteps has one parameter, similar to Batch's third, that specify whether to compare the second process output with the correct output using white-diff or a checker. In the latter case, an executable manager named :file:`checker` must be provided.
> ```

s/specify/specifies/

---

*[docs/Task types.rst, line 117 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD66AbT092ww3EOAYRh:-LD66AbT092ww3EOAYRi:b-tkt645) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L117)):*
> ```reStructuredText
> TwoSteps has one parameter, similar to Batch's third, that specify whether to compare the second process output with the correct output using white-diff or a checker. In the latter case, an executable manager named :file:`checker` must be provided.
> 
> TwoSteps supports user tests; contestant must provide the manager in addition to input and their sources.
> ```

s/contestant/contestants/
s/to input/to the input/

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967#-:-LD66vpj2U266Fp1c0bw:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[docs/Task types.rst, line 19 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD62y0Y7bf4TtnoM_d3:-LD8UHmsAL5Of--bnE8_:bnj8ewo) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L19)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Is this an unavoidable situation or just a limitation of our current implementation?
</blockquote></details>

I think it's unavoidable without having a fully-admin-controlled manager somewhere. As you said later, it could be implemented as a communication with 2 processes... I'll rephrase the docs to say that.

---

*[docs/Task types.rst, line 59 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD64SF5AciIyfDVFxKd:-LD8UdU03c2DDu4Uk868:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L59)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/submit any/submit outputs for any/ ?
</blockquote></details>

Done.

---

*[docs/Task types.rst, line 84 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD64z0-DTdTgeJu0hhk:-LD8UgPF3PeimsF3WcNq:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L84)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/ensure/ensures/
</blockquote></details>

Done.

---

*[docs/Task types.rst, line 105 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD65j79-E8c-WNoFASW:-LD8UhFp0znyQ97Do1tO:b-kqo7d1) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L105)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I was wondering, couldn't TwoSteps be implemented safely as a Communication with num_processes == 2?
</blockquote></details>

See above. Thanks!

---

*[docs/Task types.rst, line 115 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD661Na12riBv4rw4hx:-LD8UlKvAkM_yktS5QkZ:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L115)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/specify/specifies/
</blockquote></details>

Done.

---

*[docs/Task types.rst, line 117 at r1](https://reviewable.io/reviews/cms-dev/cms/967#-LD66AbT092ww3EOAYRh:-LD8UottDHLeKHgC0vcg:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/57cfe45b01ebf2d911b645cf127b8642bd21ff71/docs/Task types.rst#L117)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/contestant/contestants/
s/to input/to the input/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967#-:-LD8XUy95gDtHSSxr0qB:bb71pro)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[docs/Task types.rst, line 101 at r4](https://reviewable.io/reviews/cms-dev/cms/967#-LD8sMwi5hqDvmylk9C0:-LD8sMwi5hqDvmylk9C1:b81n8fn) ([raw file](https://github.com/cms-dev/cms/blob/254ab362d35b1aa2b4c546f15b37494ce593cfc6/docs/Task types.rst#L101)):*
> ```reStructuredText
> Communication supports user tests. In addition to the input file, contestant must provide the stub and their source file. The admin-provided manager will be used; the output returned to the contestant will be what the manager writes to the file :file:`output.txt`.
> 
> .. note:: Particular care must be taken for tasks where the communication through the FIFOs is particularly large or frequent. In these cases, the time to send the data may dominate the actual algorithm runtime, thus making it hard to distinguish between different complexities.
> ```

I guess that from the moment the program calls the `write` syscall (or whatever it's called) the resources stops being accounted to the user time and become system/idle time, right? So, what you are saying here, is it that just the "formatting" of the data in order to pass it to write could be enough to exceed the user time limit, or that the writing and waiting could be so large that the wall time limit is hit (even with a small user time)? (I just want to understand)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967#-:-LD8tJXI7c8MhElf3anT:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[docs/Task types.rst, line 101 at r4](https://reviewable.io/reviews/cms-dev/cms/967#-LD8sMwi5hqDvmylk9C0:-LDDaxOO-z9qem9Tzgw2:b-l7wctk) ([raw file](https://github.com/cms-dev/cms/blob/254ab362d35b1aa2b4c546f15b37494ce593cfc6/docs/Task types.rst#L101)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I guess that from the moment the program calls the `write` syscall (or whatever it's called) the resources stops being accounted to the user time and become system/idle time, right? So, what you are saying here, is it that just the "formatting" of the data in order to pass it to write could be enough to exceed the user time limit, or that the writing and waiting could be so large that the wall time limit is hit (even with a small user time)? (I just want to understand)
</blockquote></details>

I think the other consideration that impacts user time is context switching - even if you're sending and receiving a lot of trivial messages I think the user time is substantially impacted by that. Given that I'm not an expert and I'm not in the mood to become one tonight (especially given the wide range of languages we officially support), I'd keep it in this generic state. If we do some better sample tasks with some communication library, we might give more info at least for c/c++/pascal/java.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967)*

**Comment by stefano-maggiolo** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cms-dev/cms/967#-:-LDDbiLJ9lKRf-kjGfzu:b-ucfknh)*

**Pull request merged**
