### PR TITLE
Reprise of analysis mode (#640)

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Original work by @akmohtashami 

I rebased, merged a few things (i.e., skipped the temporary step of "ignored" instead of "official"), and fixed/improve a few other things; most notably, simplified the list of submissions in CWS (don't show if a submission is official during the contest, don't show the token column in the analysis).

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/746)

### CODE REVIEW

**Comment by lerks** [comment]
Fixes #605.

**Comment by akmohtashami** [comment]
Thank you very much @stefano-maggiolo for rebasing this. 

I apologize for responding so late. 

@qnighy: ProxyService simply ignores all unofficial submissions which include submissions made in analysis session. 

@wil93: Agreeing with Stefano.

**Comment by lerks** [comment]
Why not remove analysis_enabled and make analysis_start and _stop nullable? It seems we use both these conventions in different places, making them uniform would lead to less ambiguity.

Nit: reword commit messages to be in imperative form.

---

Reviewed 10 of 10 files at r1, 14 of 14 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[cms/db/contest.py, line 202 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJyC3J613uiZaM-1Gq:-KhJyC3J613uiZaM-1Gr:b-6i4zge) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/db/contest.py#L202)):*
> ```Python
>         Boolean,
>         nullable=False,
>         default=False,
> ```

For consistency remove the trailing comma and move the parenthesis on this line.

---

*[cms/db/contest.py, line 398 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJyh6qUeIyktZHA2oS:-KhJyh6qUeIyktZHA2oT:b-1qjclb) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/db/contest.py#L398)):*
> ```Python
>                     self.analysis_start > timestamp:
>                 return 1
>             elif self.analysis_stop is None or self.analysis_stop > timestamp:
> ```

`analysis_start` and `analysis_stop` are not nullable, no need to check they are not None.

---

*[cms/server/util.py, line 161 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK-cxusZh08V2vVTph:-KhK-cxusZh08V2vVTpi:bk9zzd5) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L161)):*
> ```Python
> 
>         if analysis_start is not None:
>             assert actual_stop <= analysis_start
> ```

Not sure I like this assert. Suppose the analysis is scheduled to start immediately after the contest ends but a user is given delay or extra time. The admin forgets about the analysis mode (no blame here). When that user attempts to do anything in their extra time they will crash the request handler (not the whole server, fortunately). Not good. I guess in that case the user should get their extra time (be in phase 0) while everyone else can already do analysis (be in phase 3).

---

*[cms/server/util.py, line 191 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK0SmWH1l4XDD3NL1G:-KhK0SmWH1l4XDD3NL1H:bmbhv6m) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L191)):*
> ```Python
>     if actual_phase == +2:
>         if analysis_start is not None:
>             assert contest_stop <= analysis_start
> ```

Also assert that analysis_stop is not None and that it is after analysis_start?

---

*[cms/server/util.py, line 201 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK0q5kWkWikproeMdy:-KhK0q5kWkWikproeMdz:btcb2bo) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L201)):*
> ```Python
>                 current_phase_begin = analysis_stop
>                 current_phase_end = None
>                 actual_phase = +4
> ```

For consistency with the above add an else that raises a RuntimeError.

---

*[cms/server/admin/handlers/__init__.py, line 218 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvAp7M7dTELtEcu3K:-KhJvAp7M7dTELtEcu3L:b6onz1o) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/__init__.py#L218)):*
> ```Python
>         r"/submission/([0-9]+)(?:/([0-9]+))?/official",
>         SubmissionOfficialStatusHandler
>     ),
> ```

Can this be formatted differently? I.e.,
```
(r"/...",
 SubmissionOfficialStatusHandler),
```

---

*[cms/server/admin/handlers/submission.py, line 38 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvNPD7_PtsGlEUpSw:-KhJvNPD7_PtsGlEUpSx:b-j6ycr2) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L38)):*
> ```Python
> from cmscommon.datetime import make_datetime
> 
> import logging
> ```

Standard library imports should go before our own ones.

---

*[cms/server/admin/handlers/submission.py, line 42 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvSmA0a7SJrI7VrnN:-KhJvSmA0a7SJrI7VrnO:b-i4typk) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L42)):*
> ```Python
> from .base import BaseHandler, FileHandler, require_permission
> 
> logger = logging.getLogger(__name__)
> ```

Two blank lines of separation above.

---

*[cms/server/admin/handlers/submission.py, line 138 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJviNG1WPojzzXjlAX:-KhJviNHPX_tWQxB5cmU:b-q0xfqp) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L138)):*
> ```Python
>                         submission.participation.user.username,
>                         submission.participation.contest.name,
>                         ["unofficial", "official"][should_make_official])
> ```

Can you use `"official" if should_make_official else "unofficial"`? Indexing with a bool is weird.

---

*[cms/server/admin/templates/contest.html, line 271 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK1d4LUPFLeEx2mZIH:-KhK1d4LUPFLeEx2mZII:beu27w8) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/admin/templates/contest.html#L271)):*
> ```HTML
>         Analysis mode start time (in UTC)
>       </td>
>       <td><input type="text" name="analysis_start" value="{{ str(contest.analysis_start) }}"></td>
> ```

id missing? I don't really see the use of ids, but they are used in other fields. Be consistent.

---

*[cms/server/admin/templates/submission.html, line 87 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJx-AhM6uxsYxuRJfB:-KhJx-AhM6uxsYxuRJfC:b9biduq) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/submission.html#L87)):*
> ```HTML
>                   disabled
>               {% end %}
>                onclick="document.official_status_form.submit()"
> ```

Can't we use `<input type="submit">` here? This seems unnecessarily complicated.

---

*[cms/server/admin/templates/submission.html, line 98 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJx5EiIzAsdM2QfjoC:-KhJx5EiIzAsdM2QfjoD:b-816h6l) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/submission.html#L98)):*
> ```HTML
>                   disabled
>               {% end %}
>                onclick="document.official_status_form.submit()"
> ```

Same.

---

*[cms/server/admin/templates/fragments/submission_row.html, line 112 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxDMJfK6vBYNNcBjs:-KhJxDMJfK6vBYNNcBjt:b-mctelo) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/fragments/submission_row.html#L112)):*
> ```HTML
>   </td>
>   <td>
>     {% if s.official is False %}
> ```

Comparing a bool to a bool is weird: why not `if s.official: yes; else: no`?

---

*[cms/server/contest/static/cws_utils.js, line 263 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK2dvek24Ac1k3gOrr:-KhK2dvek24Ac1k3gOrs:b66m31h) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/contest/static/cws_utils.js#L263)):*
> ```JavaScript
>             this.format_timedelta(this.current_phase_end - server_time));
>         break;
>         case +3:
> ```

Bad indentation.

---

*[cms/server/contest/templates/submission_row.html, line 82 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxSPNfudcQfnBVEHZ:-KhJxSPOTriFS_Xcsri3:b-v32em0) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/contest/templates/submission_row.html#L82)):*
> ```HTML
> {% end %}
>     <td class="considered_in_score">
>       {% if s.official is True %}
> ```

Same, even more blatant.

---

*[cms/service/ProxyService.py, line 391 at r3](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhKA1TK1t0Lhfh-n877:-KhKA1TK1t0Lhfh-n878:b-mavpk3) ([raw file](https://github.com/cms-dev/cms/blob/c97ce3f05c8c2677e0f8a76fed2f71ef54902a45/cms/service/ProxyService.py#L391)):*
> ```Python
>             "task": encode_id(submission.task.name),
>             "time": int(make_timestamp(submission.timestamp)),
>         }
> ```

Why?! (same twice below)

---

*[cmscontrib/updaters/update_27.py, line 37 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxsC5GEJ5KK_VB3Q4:-KhJxsC6YRCD6Tc-Cpp9:b5qjck8) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cmscontrib/updaters/update_27.py#L37)):*
> ```Python
> 
>     def __init__(self, data):
>         assert data["_version"] == 26
> ```

The version in `cms.db.__init__` hasn't been updated to 27.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhJu_imAATNnAMsMx0a:bxk4nci)*

**Comment by lerks** [comment]
Oh and the updater for `analysis_(enabled|start|stop)` is missing.

---

Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhKQAl9jytkbCwEO1Y-:boxsxe1)*

**Comment by wil93** [comment]
> Why not remove analysis_enabled and make analysis_start and _stop nullable? It seems we use both these conventions in different places, making them uniform would lead to less ambiguity.

This is a good idea, and in some cases you may want `analysis_stop` to be null (e.g. in long-running instances with multiple contests, see #643)

**Comment by lerks** [comment]
I'm not all that in favor of having None mean unbounded here, especially because setting them both to none wouldn't mean unbounded in both directions (or, in other words, analysis starts after the contest ends and goes on forever) but rather would mean the opposite, no analysis at all.

---

Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[cms/server/util.py, line 161 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK-cxusZh08V2vVTph:-KhNOo2We_2R2ydUvr0o:b-4x32s0) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L161)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Not sure I like this assert. Suppose the analysis is scheduled to start immediately after the contest ends but a user is given delay or extra time. The admin forgets about the analysis mode (no blame here). When that user attempts to do anything in their extra time they will crash the request handler (not the whole server, fortunately). Not good. I guess in that case the user should get their extra time (be in phase 0) while everyone else can already do analysis (be in phase 3).
</blockquote></details>

I'm surprised this hasn't been caught by the unit tests. It may be worth adding some tests where analysis_start == contest_stop, and make sure that behaves correctly when delay_time and/or extra_time are not zero.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhNP35Xrbe7INcjgbn5:b-t2rceu)*

**Comment by stefano-maggiolo** [comment]
@akmohtashami not at all, thank you for your work!

@lerks I kind of like the checkbox in AWS (that is a different question, though, that is trying to make the interface as clear as possible instead of mapping 1:1 the db...).

@wil93 I thought that the "online judge" would use phase 0, not phase 3 (in which case you want to have contest_stop nullable to mean "extending indefinitely in the future"?

To make everybody agree, I think there is a possible solution, which I will outline here but probably implement in a second moment to avoid complicating this PR:
- we retain the current fields: contest_{start,stop}, analysis_{enabled,start,stop}
- all timestamps are nullable meaning "extending indefinitely in that direction"
- contest_stop = null => analysis_enabled = False
- analysis_enabled = False => analysis_start = null and analysis_stop = null
- analysis_enabled = True => analysis_start != null
- whenever non-null, contest_start <= contest_stop <= analysis_start <= analysis_stop

As mentioned, I don't particularly want to do this *now*. Given the proposal doesn't restrict the fields it should be effortless to write updaters. 

---

Review status: 14 of 27 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[cms/db/contest.py, line 202 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJyC3J613uiZaM-1Gq:-KhLCTB92CBl44JmYrAs:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/db/contest.py#L202)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

For consistency remove the trailing comma and move the parenthesis on this line.
</blockquote></details>

Done.

---

*[cms/db/contest.py, line 398 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJyh6qUeIyktZHA2oS:-KhLJkfcaebV54qSbh_0:b9h99pn) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/db/contest.py#L398)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

`analysis_start` and `analysis_stop` are not nullable, no need to check they are not None.
</blockquote></details>

That's true also of start and stop...

---

*[cms/server/util.py, line 161 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK-cxusZh08V2vVTph:-KhLWsVRuBiu69haqfZz:b-7hncne) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L161)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I'm surprised this hasn't been caught by the unit tests. It may be worth adding some tests where analysis_start == contest_stop, and make sure that behaves correctly when delay_time and/or extra_time are not zero.
</blockquote></details>

Correct, I was wondering if we needed to warn against setting analysis_start not immediately after the contest ended... But I think this would work, pending the two changes done (removing this and changing the current phase start time returned by compute_actual_phase in this situation).

Edit after your second comment: yeah, I had already added tests for this.

---

*[cms/server/util.py, line 191 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK0SmWH1l4XDD3NL1G:-KhLXR99ZopEX2HEVM94:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L191)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Also assert that analysis_stop is not None and that it is after analysis_start?
</blockquote></details>

Done.

---

*[cms/server/util.py, line 201 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK0q5kWkWikproeMdy:-KhLXUXCLJ8EXr7YHlXs:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/util.py#L201)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

For consistency with the above add an else that raises a RuntimeError.
</blockquote></details>

Done.

---

*[cms/server/admin/handlers/__init__.py, line 218 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvAp7M7dTELtEcu3K:-KhLXWuR5VVMjkJtPQzN:bzfjabc) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/__init__.py#L218)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Can this be formatted differently? I.e.,
```
(r"/...",
 SubmissionOfficialStatusHandler),
```
</blockquote></details>

Uhm, sure :P

---

*[cms/server/admin/handlers/submission.py, line 38 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvNPD7_PtsGlEUpSw:-KhLXhfpNMA_xOgchHD0:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L38)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Standard library imports should go before our own ones.
</blockquote></details>

Done.

---

*[cms/server/admin/handlers/submission.py, line 42 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJvSmA0a7SJrI7VrnN:-KhLXiJji8JvCPhdGwCN:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L42)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Two blank lines of separation above.
</blockquote></details>

Done.

---

*[cms/server/admin/handlers/submission.py, line 138 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJviNG1WPojzzXjlAX:-KhLXkmuMg9KWVogOv_K:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/handlers/submission.py#L138)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Can you use `"official" if should_make_official else "unofficial"`? Indexing with a bool is weird.
</blockquote></details>

Done.

---

*[cms/server/admin/templates/contest.html, line 271 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK1d4LUPFLeEx2mZIH:-KhLY8J9ADCF_d4Vpq8x:bdf6pnc) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/admin/templates/contest.html#L271)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

id missing? I don't really see the use of ids, but they are used in other fields. Be consistent.
</blockquote></details>

Actually they are only in checkboxes. Not sure if used, I removed it from the next one instead. 

---

*[cms/server/admin/templates/submission.html, line 87 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJx-AhM6uxsYxuRJfB:-KhLYvc1AbdA-3EJt3tH:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/submission.html#L87)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Can't we use `<input type="submit">` here? This seems unnecessarily complicated.
</blockquote></details>

Done.

---

*[cms/server/admin/templates/submission.html, line 98 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJx5EiIzAsdM2QfjoC:-KhLYvwuFmJnLPgd3sY6:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/submission.html#L98)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.

---

*[cms/server/admin/templates/fragments/submission_row.html, line 112 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxDMJfK6vBYNNcBjs:-KhLYzSEgsGMaObG4ocF:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/admin/templates/fragments/submission_row.html#L112)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Comparing a bool to a bool is weird: why not `if s.official: yes; else: no`?
</blockquote></details>

Done.

---

*[cms/server/contest/static/cws_utils.js, line 263 at r2](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhK2dvek24Ac1k3gOrr:-KhLZ8LJme1Ih0Ulz4ib:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/0cc61d091a574273133eb8c68eed9d356b97da45/cms/server/contest/static/cws_utils.js#L263)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Bad indentation.
</blockquote></details>

Done.

---

*[cms/server/contest/templates/submission_row.html, line 82 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxSPNfudcQfnBVEHZ:-KhLZEk6RfnyK0xVMp9L:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cms/server/contest/templates/submission_row.html#L82)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same, even more blatant.
</blockquote></details>

Done.

---

*[cms/service/ProxyService.py, line 391 at r3](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhKA1TK1t0Lhfh-n877:-KhLZIKlu92tAPI57nUs:b-skxrho) ([raw file](https://github.com/cms-dev/cms/blob/c97ce3f05c8c2677e0f8a76fed2f71ef54902a45/cms/service/ProxyService.py#L391)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Why?! (same twice below)
</blockquote></details>

Well, sure, not for this PR, but I actually like more this style :)
Reverted.

---

*[cmscontrib/updaters/update_27.py, line 37 at r1](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhJxsC5GEJ5KK_VB3Q4:-KhLZgRTsV8boybQL9kl:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/7efea7ea849704334b6be89a15116b0368fec0ca/cmscontrib/updaters/update_27.py#L37)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

The version in `cms.db.__init__` hasn't been updated to 27.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhLBzC1CDgNKMKFggpK:b-32n0h9)*

**Comment by lerks** [comment]
OK for not changing anything for now. Fixup looks good. Just spotted one more tiny thing. Also, could you mention analysis mode in the docs? Just a short paragraph would do.

---

Reviewed 13 of 13 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/server/__init__.py, line 90 at r7](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhOs53ux_oxr8bM6-eW:-KhOs53vl6lCNzAjWfMA:b-ub7dvx) ([raw file](https://github.com/cms-dev/cms/blob/21a0f47f339e5d35acf0befebee95349d205adc4/cmstestsuite/unit_tests/server/__init__.py#L90)):*
> ```Python
>     contest_stop (string): the contest's stop.
>     contest_start (string): the analysis mode's start.
>     contest_stop (string): the analysis mode's stop.
> ```

Just noticed: wrong parameter names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhOspJ_3xhxsZQxq550:b-aqolht)*

**Comment by stefano-maggiolo** [comment]
Filed the FR in #748.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmstestsuite/unit_tests/server/__init__.py, line 90 at r7](https://reviewable.io:443/reviews/cms-dev/cms/746#-KhOs53ux_oxr8bM6-eW:-KhR8Ghd5Di1sDattQ8J:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/21a0f47f339e5d35acf0befebee95349d205adc4/cmstestsuite/unit_tests/server/__init__.py#L90)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Just noticed: wrong parameter names.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/746#-:-KhQLDCzju82THce4ZTB:b-o40brx)*

**Comment by stefano-maggiolo** [comment]
Merged. Follow ups in #749

**Pull request closed without merging**
