### PR TITLE
Improvements to cmscommon.crypto

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/894)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cmscommon/crypto.py, line 83 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7if7Lw2LB606zk50Bi:-L7if7Lx4QOsoApHvHFo:b-u0e576) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L83)):*
> ```Python
> 
>     pt (bytes): the "plaintext" to encode.
>     key_hex (string): a 16-bytes key in hex (a string of 32 hex chars).
> ```

Could you be more specific and use `str` or `bytes`? `string` is ambiguous.

---

*[cmscommon/crypto.py, line 85 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7ifE5FDAwY1wctx1vo:-L7ifE5FDAwY1wctx1vp:b-mlh6ql) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L85)):*
> ```Python
>     key_hex (string): a 16-bytes key in hex (a string of 32 hex chars).
> 
>     return (string): pt encrypted using the key, in a format URL-safe
> ```

Same here (string).

---

*[cmscommon/crypto.py, line 86 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7ifEyz8XJzR1Z0fWnK:-L7ifEyz8XJzR1Z0fWnL:b7umj6g) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L86)):*
> ```Python
> 
>     return (string): pt encrypted using the key, in a format URL-safe
>         (more precisely, base64-encoded with alphabet a-zA-Z0-9.-_
> ```

You left the parenthesis open.

---

*[cmscommon/crypto.py, line 113 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7ifKWd8rff4jPxXHWY:-L7ifKWd8rff4jPxXHWZ:b-f9lo1t) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L113)):*
> ```Python
> 
>     ct_b64 (string): the ciphertext as produced by encrypt_binary.
>     key_hex (string): the 16-bytes key in hex format used to encrypt.
> ```

Same here (string) x2.

---

*[cmscommon/crypto.py, line 135 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7ifiQSE5Fww4MPf3nq:-L7ifiQSE5Fww4MPf3nr:b-fq1359) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L135)):*
> ```Python
>         pt = pt_pad.rstrip(b'\x00')[:-1]
>         return pt
>     except (TypeError, binascii.Error):
> ```

Nit: would be cool if `b64_to_bin` didn't raise exceptions that depend on its internal implementation details...

---

*[cmstestsuite/unit_tests/cmscommon/crypto_test.py, line 53 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7igI5a6nudoZNQ0GGt:-L7igI5a6nudoZNQ0GGu:b-rnzihd) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmstestsuite/unit_tests/cmscommon/crypto_test.py#L53)):*
> ```Python
>         valid = "0123456789abcdef"
>         for x in get_hex_random_key():
>             self.assertIn(x, valid)
> ```

Maybe add a comment that in py3 we can do this with `assertRegex`? (Maybe using six we can do it now already?)

---

*[cmstestsuite/unit_tests/cmscommon/crypto_test.py, line 134 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/894#-L7igzCp4wgEZ2sKceO3:-L7igzCp4wgEZ2sKceO4:bb47g35) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmstestsuite/unit_tests/cmscommon/crypto_test.py#L134)):*
> ```Python
>     def test_alphabet(self):
>         p = generate_random_password()
>         self.assertEqual(re.match("[a-z]+", p).group(0), p)
> ```

Same here (either comment to use assertRegex, or do now)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/894#-:-L7ihaIS5wQbVaLmR2h9:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[cmscommon/crypto.py, line 83 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7if7Lw2LB606zk50Bi:-L7jE2BcdFUDRu1pBbPL:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L83)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Could you be more specific and use `str` or `bytes`? `string` is ambiguous.
</blockquote></details>

Done.

---

*[cmscommon/crypto.py, line 85 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7ifE5FDAwY1wctx1vo:-L7jE2cPC59Qc3xhGscc:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L85)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same here (string).
</blockquote></details>

Done.

---

*[cmscommon/crypto.py, line 86 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7ifEyz8XJzR1Z0fWnK:-L7jCiWtLkLfUdYWfoDO:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L86)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

You left the parenthesis open.
</blockquote></details>

Done.

---

*[cmscommon/crypto.py, line 113 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7ifKWd8rff4jPxXHWY:-L7jCj7b4Bus-yAe4Gaa:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L113)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same here (string) x2.
</blockquote></details>

Done.

---

*[cmscommon/crypto.py, line 135 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7ifiQSE5Fww4MPf3nq:-L7jCotfdciPFVCSXZYo:b-5nzvma) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmscommon/crypto.py#L135)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Nit: would be cool if `b64_to_bin` didn't raise exceptions that depend on its internal implementation details...
</blockquote></details>

I guess so... next commit?

---

*[cmstestsuite/unit_tests/cmscommon/crypto_test.py, line 53 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7igI5a6nudoZNQ0GGt:-L7jDnMF2pFUXmZDAk2D:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmstestsuite/unit_tests/cmscommon/crypto_test.py#L53)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Maybe add a comment that in py3 we can do this with `assertRegex`? (Maybe using six we can do it now already?)
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscommon/crypto_test.py, line 134 at r2](https://reviewable.io:443/reviews/cms-dev/cms/894#-L7igzCp4wgEZ2sKceO3:-L7jE-JiGRmGa_Pcu9zB:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/60d22f1f95e3afc86fa8843cdcfb7cc3bed96d5f/cmstestsuite/unit_tests/cmscommon/crypto_test.py#L134)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same here (either comment to use assertRegex, or do now)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/894)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/894)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
