### PR TITLE
Fix "Subject too long" message

### LINKED ISSUE #1040: Broken "Subject must be at most…" message in .pot file
`cms/locale/cms.pot` contains
```pot
#, python-format
msgid ""
"Subject must be at most %(max_subject_length)d characters, content at most "
"%(max_text_length)d.max_subject_length"
msgstr ""
```

Notice garbage at the end of the string. It was added in 3401a2a51e90aa945fb9f7d95cad9ab24e8381cd.

The original message comes from ` cms/server/contest/communication.py` in `accept_question()`:
```python
        raise UnacceptableQuestion(
            N_("Question too long!"),
            N_("Subject must be at most %(max_subject_length)d characters, "
               "content at most %(max_text_length)d."
               % {"max_subject_length": Question.MAX_SUBJECT_LENGTH,
                  "max_text_length": Question.MAX_TEXT_LENGTH}))
```

Looks like it was added in a5032c89e2a23f1520d029cc49eaa1dbfbb15826.

### PR DESCRIPTION
**Pull request by andreyv**
Fixes #1040. Also update `.pot` file.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1041)

### CODE REVIEW

**Comment by lerks** [comment]
To be clear: the issue (a big one) is in our code, this PR uncovered and addressed one symptom but didn't fix the core problem.

**Comment by andreyv** [comment]
Thanks for the explanation, I confused `N_` with `_`. I'll re-work the PR.

**Comment by stefano-maggiolo** [comment]
Hi Andrey, do you have time to fix this up today or tomorrow? We'd like to include this fix in rc1 and to release it asap as there were a few substantial usability bugs in rc0. If not it's not a problem, I think Luca can work on it 😁

**Comment by lerks** [comment]
Superseded by #1046.

**Pull request closed without merging**
