### PR TITLE
Add missing 'return' keyword at function 'get_evaluation'

### PR DESCRIPTION
**Pull request by wafrelka**
Without 'return' keyword, the function always returns None ...

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/535)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Hi! wow, this is embarassing :)

Since this method has no callers (luckily!), can you remove it entirely instead? Unless you want to use it for something else in the future, in which case I'm happy to merge this. Let me know!

**Comment by wafrelka** [comment]
We want to use this function to create some tools for our domestic OI contest.

**Comment by stefano-maggiolo** [comment]
No problem, thanks! (merged)

**Comment by wafrelka** [comment]
thank you!

**Pull request closed without merging**
