### PR TITLE
[IOI2017] merge back changes related to TPS

### PR DESCRIPTION
**Pull request by wil93**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/852)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
This PR is for discussion only - decide what needs to be done and who is going to do it. Once this is achieved, a new PR should be done with the code expected to be merged.

**Comment by lerks** [comment]
Uhm... any context for people who were not at IOI2017 and have no idea what CPS, TPS and all other acronyms stand for?

**Comment by gollux** [comment]
TPS is the Task Preparation System developed in Iran for IOI2017,
published at https://github.com/ioi-2017/tps.

CPS is an older name of the same thing (Contest Preparation System).

**Comment by stefano-maggiolo** [comment]
Superseded by #935.

**Pull request closed without merging**
