### PR TITLE
Added e-mail field to registration form.

### PR DESCRIPTION
**Pull request by rvisser7**
Made a simple addition to the registration form for an e-mail address.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/1110)

### CODE REVIEW

**Comment by rvisser7** [comment]
> I think you can add `autocomplete="email"` as explained in https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill (similar to the password field later).

Done.

**Comment by stefano-maggiolo** [comment]
Do you need the email as a required field? I would prefer to keep it optional.

**Comment by rvisser7** [comment]
> Do you need the email as a required field? I would prefer to keep it optional.

Done (made it optional).  I'll keep it as a required field for our local version though.

**Comment by stefano-maggiolo** [comment]
Merged (with a small further change, if email == "" then make it None).

**Pull request closed without merging**
