### PR TITLE
Outputonly functional tests

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/878)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: 16 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/878#-:-L6_mUZ5wHxGL9kdFejG:bnfp4nl)*

**Comment by lerks** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cmstestsuite/web/__init__.py, line 35 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/878#-L6_mhr-6-lEEzdyMNad:-L6_mhr-6-lEEzdyMNae:bcubqit) ([raw file](https://github.com/cms-dev/cms/blob/2f21a1f62281abfe197926be7d991aba6eafa5a0/cmstestsuite/web/__init__.py#L35)):*
> ```Python
> import datetime
> import io
> import requests
> ```

Requests isn't in the stdlib, shouldn't it go into a separate block?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/878)*

**Comment by lerks** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/878)*

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
