### PR TITLE
Add --prefix to cmsImportTask

### PR DESCRIPTION
**Pull request by wil93**
This is useful when you want to add a task to a contest, but you have already added it to another contest.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/583)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Wouldn't it be more flexible to specify the whole name? What if you want a suffix instead?

**Comment by wil93** [comment]
This way you can do just `cmsImportTask --prefix "something_" .` without having to specify the name (handy if you have to run the command on many tasks).

**Comment by stefano-maggiolo** [comment]
Well, anyhow, this is for you so you know better...

**Comment by stefano-maggiolo** [comment]
Merged.

**Comment by wil93** [comment]
In retrospect, maybe it really would have been better to override the whole name :sweat_smile: see #616

**Pull request closed without merging**
