### PR TITLE
RS refactoring

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Mostly to get better performance when some services are not running, but I think the structure is also nicer.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/728)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/service/ResourceService.py, line 84 at r1](https://reviewable.io:443/reviews/cms-dev/cms/728#-KfaqEYeAUx7-VRq2MKY:-KfaqEYft-HIlidFyytY:b-hi4omz) ([raw file](https://github.com/cms-dev/cms/blob/1717ce722f4bd4f94603eb30f5afbf9412ff3b28/cms/service/ResourceService.py#L84)):*
> ```Python
> 
>         procs ({string: {int|None}: object): maps tuples (argument
>             with service name, shard) to psutil proc_info objects.
> ```

procs isn't an argument, is this a leftover? also, you should explain cpu_times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/728#-:-Kfasw8gjsaIQNUr4rHC:bnfp4nl)*

**Comment by lerks** [comment]
:lgtm_cancel: 

I'd like to try a totally different approach for RS (using lockfiles instead of parsing command lines) and I'm putting this PR on hold until that's done so that we can compare the two approaches and push the one we prefer.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/728#-:-KfjX_J0ZYDEsnTQDQHJ:b-3w3xvl)*

**Comment by stefano-maggiolo** [comment]
I disagree, we should merge this improvement at zero cost and if it becomes a need try different approaches. What you say might be better, but it's significantly different and creates some work that by merging this we won't have.

**Comment by lerks** [comment]
:lgtm:

You're right, agreed (and sorry). LGTM again, go ahead! :)

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/728#-:-KfkOtEJvqOz2n2AIpUm:b-9u1j2)*

**Comment by stefano-maggiolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/service/ResourceService.py, line 84 at r1](https://reviewable.io:443/reviews/cms-dev/cms/728#-KfaqEYeAUx7-VRq2MKY:-Kfs4jfAxLO9jVkO_Lbs:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/1717ce722f4bd4f94603eb30f5afbf9412ff3b28/cms/service/ResourceService.py#L84)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

procs isn't an argument, is this a leftover? also, you should explain cpu_times.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/728)*

**Pull request closed without merging**
