### PR TITLE
Support add/edit teams from AWS

### PR DESCRIPTION
**Pull request by wil93**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/504)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cms/server/admin/handlers/base.py, line 45 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MYOyVJG3rKTcvHarQ:-K4MYOyVJG3rKTcvHarR:1746811380) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/handlers/base.py#L45)):*
Keep sorted if already sorted :)

---

*[cms/server/admin/handlers/user.py, line 92 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MYZw_bSBs3nP6zrnv:-K4MYZw_bSBs3nP6zrnw:-499110562) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/handlers/user.py#L92)):*
class doc? (Not nitpicking, it's not easy to guess what get and post do without reading the code)

---

*[cms/server/admin/templates/add_team.html, line 5 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MZCAXLnl7EyI75cHO:-K4MZCAXLnl7EyI75cHP:678055138) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/add_team.html#L5)):*
team

---

*[cms/server/admin/templates/team.html, line 11 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MZYVjCUk-0y32ogvu:-K4MZYVjCUk-0y32ogvv:-1430370273) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/team.html#L11)):*
If this table is the same as the other, you can factor them out in fragments/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/504)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/server/admin/templates/base.html, line 175 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4M_S_kEgNScDzt7M5h:-K4M_S_kEgNScDzt7M5i:-529486507) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/base.html#L175)):*
It looks quite bad when there is one team :) Can you change this and also the user?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/504)*

**Comment by stefano-maggiolo** [comment]
Merged!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/504#-:-K4McAdJx36I5zjtkfHu:472139184)*

**Comment by stefano-maggiolo** [comment]
Of course not merged - wrong PR :)

**Comment by wil93** [comment]
Review status: 3 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[cms/server/admin/handlers/base.py, line 45 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MYOyVJG3rKTcvHarQ:-K4MkMQG5XwYDWRIcGGr:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/handlers/base.py#L45)):*
Done.

---

*[cms/server/admin/handlers/user.py, line 92 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MYZw_bSBs3nP6zrnv:-K4Mn2rYTmltYF6jIPg3:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/handlers/user.py#L92)):*
Done.

---

*[cms/server/admin/templates/add_team.html, line 5 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MZCAXLnl7EyI75cHO:-K4NJtUNJH90HbsXWPzD:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/add_team.html#L5)):*
Done.

---

*[cms/server/admin/templates/base.html, line 175 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4M_S_kEgNScDzt7M5h:-K4NR-COpAupVH-9se66:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/base.html#L175)):*
Done.

---

*[cms/server/admin/templates/team.html, line 11 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/504#-K4MZYVjCUk-0y32ogvu:-K4NSlp_LaQ1uKL29iIj:-1611527123) ([raw file](https://github.com/cms-dev/cms/blob/07245b1245e47c16530cf44488b5d269b4e8abd3/cms/server/admin/templates/team.html#L11)):*
I'm afraid it's not exactly the same (as in user.html and add_user.html)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/504)*

**Comment by stefano-maggiolo** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/504)*

**Comment by stefano-maggiolo** [comment]
Merged!

**Pull request closed without merging**
