### PR TITLE
Produce sane CSV output, that correctly handles commas in the fields

### PR DESCRIPTION
**Pull request by wil93**
[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/493)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 36 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y59Y5jGXVB9i9cp01)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L36)):</sup>
Please sort


---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
If BytesIO is good for py2, why isn't it good for py3? I'd say just use BytesIO, also because our code is in general not compatible with py3 (well, more like "we haven't tested it"), so adding it here has little value.


---

<sup>**[cms/server/admin/handlers/contestranking.py, line 124 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y6y1XAdlPUlGFGaVs)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L124)):</sup>
Same here, just keep the py2 version.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by stefano-maggiolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by wil93** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 36 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y59Y5jGXVB9i9cp01)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L36)):</sup>
Done.


---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
I took it from http://stackoverflow.com/a/9157370/747654

However I believe that it's good to leave the py3 version in order to ease the eventual transition. I'm not saying we should try to make it work on both py2 and py3, but just have it there so that (whenever the transition will be done) one does not have to look for what is the substitute of BytesIO.

Maybe there's even an automated way to detect these "mechanical" changes (2to3 maybe? I haven't used it yet -- nevermind, I just tried it and it doesn't detect that), but yet I don't see the harm in keeping both, since the `else` branch won't be reached.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
BytesIO doesn't disappear in py3. More importantly, are you sure that StringIO doesn't work already in py2 with unicode_literals?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by wil93** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
Mmm... https://docs.python.org/2.7/library/csv.html#module-csv

Also: http://stackoverflow.com/questions/13120127/how-can-i-use-io-stringio-with-the-csv-module


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
Oh I see, the problem is in csv, not in io. Can you add a comment clarifying it?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by wil93** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[cms/server/admin/handlers/contestranking.py, line 78 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/493#-K2y5gWq_dhc-ez24mE5)** ([raw file](https://github.com/cms-dev/cms/blob/58b05eae81ea28d8195490b17d3674d51fe274af/cms/server/admin/handlers/contestranking.py#L78)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by stefano-maggiolo** [comment]
Thank you William, merging this!


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/493)

**Comment by stefano-maggiolo** [comment]
1d8e7fb83e787af9337e3dc54dcc64d2bc16131e

**Pull request closed without merging**
