### PR TITLE
Cleaning up a bit cmscontrib.

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Tests, fixes to bugs found thanks to the tests, and removing useless
code (from when cmscontrib was more like a contrib and less like a
script folder).

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/898)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
I think somebody uses SpoolExporter, despite the fact it's a relic from the past. I wouldn't kill it but make it more universally useful (possibly moving its functionality elsewhere).

PTAL: sorry I added also a few other things apart from addressing the comments.

---

Review status: 4 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[cmscontrib/AddSubmission.py, line 59 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nlB7T1JHbqExrEM1X:-L7t8uYWpGTBN0eEOD_-:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L59)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

s/string/str/?
</blockquote></details>

Done.

---

*[cmscontrib/AddSubmission.py, line 69 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nlSA2STcfo7lHRNFe:-L7t957v0v7m6eIW2GYy:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L69)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

`iterkeys` would make it clearer, and may I suggest using filename (or even codename, for the filename-with-%l)?
</blockquote></details>

Done.

---

*[cmscontrib/AddSubmission.py, line 71 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nlfSVDmh7jPXIs_m4:-L7t95jcqg3DFodF508c:bqij0na) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L71)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Consider `file_.endswith(".%l")`
</blockquote></details>

This was copied from the submit handler - if we want to change we can, but needs to be done at a higher level (good candidate for putting it in cmscommon).

---

*[cmscontrib/AddSubmission.py, line 118 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nm0UGrTQRFY_2B8Qh:-L7tDQIKSF8gRc06QwR4:bb73xfv) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L118)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same: `element.endswith(".%l")` (or even `".%l" in element`)
</blockquote></details>

Same

---

*[cmscontrib/AddSubmission.py, line 123 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nmkwo_WKhztl2Maop:-L7t9XkirqHKNzVWECgV:be7z5zu) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L123)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Does logging the exception object work as it should?
</blockquote></details>

Shows like this:
```
.2018-03-18 12:51:13,258 - CRITICAL [<unknown>] Cannot recognize language for file `source.%l'.
```

---

*[cmstestsuite/unit_tests/databasemixin.py, line 186 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nrJR4z0o6A3G5jq1w:-L7t9wpx44NI6Ul_YHoU:bmknks4) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/databasemixin.py#L186)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

This should go in the previous commit
</blockquote></details>

Right, will change before submitting.

---

*[cmstestsuite/unit_tests/cmscontrib/AddAdminTest.py, line 53 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nrbzr7ApE8aWE4nY-:-L7t9zsXvTbXjZd-T6c8:b-n0gh1y) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/cmscontrib/AddAdminTest.py#L53)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Again, this cannot fail, right?
</blockquote></details>

Yeah, I got in the habit when I started doing these test to check again, but it's pretty pointless indeed. I'll avoid doing so in new tests.

---

*[cmstestsuite/unit_tests/cmscontrib/AddParticipationTest.py, line 67 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nrskgQ0qGh2iux7mg:-L7tAhG108pqFJI_slHM:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/cmscontrib/AddParticipationTest.py#L67)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Here as well
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py, line 47 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7ntjv_AI-nIH2XlwHh:-L7tAiHy0ftYcbda0Gm8:bc96xa) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py#L47)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Nit: in the AddAdmin test you put values like these as globals...
</blockquote></details>

In AddSubmission you mean? Yeah, that mostly because it's used in more than one class, but also works better (avoid having to use self. or <class>.)... I'll move these constant to the module, but in general I won't try to make all the tests look exactly the same - I prefer spending the time writing new tests :)

---

*[cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py, line 67 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7ntHiNUtlkaC648Sge:-L7tBqsHsuPVfrBGw4FN:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py#L67)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Too
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 86 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7npJ5qOqzK_yDHRFeK:-L7tBrr_y1Jx8eWPvBCV:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L86)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Can this ever fail? (given the query filters)
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 180 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nqXTiMtx79i600Iuy:-L7tC4u1KQcI6OGwsO10:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L180)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Fix docstring
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 220 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nqj2iiIOpV-12FMpa:-L7tDCeYb7mQieGLstDO:b-4pffk7) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L220)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Want to add a test where one file has a language (`file.c`) and the other doesn't (`file`)?
</blockquote></details>

Done. I expected this to succeed but it doesn't (requires an inferred language for all files with %l). Thinking about it, seems reasonable.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 224 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nqrTwuJrAuAqLopq3:-L7tC5ysb68Kq3iFzIHM:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L224)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/898#-:-L7t72IzdpUCiXYansGR:b6pldvc)*

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmscontrib/AddSubmission.py, line 71 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nlfSVDmh7jPXIs_m4:-L7tGbjRDYvj9ZTj613h:b810eg0) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L71)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

This was copied from the submit handler - if we want to change we can, but needs to be done at a higher level (good candidate for putting it in cmscommon).
</blockquote></details>

I am working on refactoring the submit handler (something should be out for review next week) and probably this file could reuse some code from that. If you don't want to do changes here now, though, could you add a TODO?

---

*[cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py, line 47 at r3](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7ntjv_AI-nIH2XlwHh:-L7tHIAe4emAXdvHPJ9t:b6944dd) ([raw file](https://github.com/cms-dev/cms/blob/8d837a5fec538b78e63c2684634978313dc0a0e9/cmstestsuite/unit_tests/cmscontrib/AddStatementTest.py#L47)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

In AddSubmission you mean? Yeah, that mostly because it's used in more than one class, but also works better (avoid having to use self. or <class>.)... I'll move these constant to the module, but in general I won't try to make all the tests look exactly the same - I prefer spending the time writing new tests :)
</blockquote></details>

Sure, no problem, just noticed this (in fact, I noticed that you were using `TestFooBar.` to access them, which seemed heavy) and found it worth mentioning.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 220 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nqj2iiIOpV-12FMpa:-L7tI12NiA0QyR1sCbvI:b-mijsjx) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L220)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Done. I expected this to succeed but it doesn't (requires an inferred language for all files with %l). Thinking about it, seems reasonable.
</blockquote></details>

That is good, but I was (also) thinking of a case where it should succeed, something like:
```
add_submission(
    self.contest.id, self.user.username, self.task.name, _TS, {
        "source1.%l": self.get_path(_FILENAME_1),
        "source2": self.get_path(_FILENAME_2),
     })
```
Where the submission format of the file without an extension had no `%l`. I agree this is weird, but we technically still allow it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/898)*

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmscontrib/AddSubmission.py, line 71 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nlfSVDmh7jPXIs_m4:-L7uHTBiOjGLaUI266rD:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmscontrib/AddSubmission.py#L71)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

I am working on refactoring the submit handler (something should be out for review next week) and probably this file could reuse some code from that. If you don't want to do changes here now, though, could you add a TODO?
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py, line 220 at r2](https://reviewable.io:443/reviews/cms-dev/cms/898#-L7nqj2iiIOpV-12FMpa:-L7uHiVdmQUU4ZfsYmJ7:b32w1t) ([raw file](https://github.com/cms-dev/cms/blob/a77a6fbaf4e0be1275936889459f6d0e8ebcbd73/cmstestsuite/unit_tests/cmscontrib/AddSubmissionTest.py#L220)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

That is good, but I was (also) thinking of a case where it should succeed, something like:
```
add_submission(
    self.contest.id, self.user.username, self.task.name, _TS, {
        "source1.%l": self.get_path(_FILENAME_1),
        "source2": self.get_path(_FILENAME_2),
     })
```
Where the submission format of the file without an extension had no `%l`. I agree this is weird, but we technically still allow it.
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/898)*

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/898#-:-L7uKLRMh3IK8CgaA6oc:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Merged

**Pull request closed without merging**
