### PR TITLE
Initial stuff related to ES performance testing and solutions

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
In particular for the "Resolve deadlock issue": this was something we saw in IOI day1 together with the poor performance. Bernard managed to solve it with that change - I'm not 100% sure that no other issues like that are present, but at least we didn't see anything bad in day2 (but it might also be because of the minor load).

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/485)

### CODE REVIEW

**Comment by giomasce** [comment]
Reviewed 206 of 206 files at r1.
Review status: 205 of 206 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[cmstestsuite/RunTimeTest.py, line 75 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/485#-K3JwQysVQQHg8T5vJfs)** ([raw file](https://github.com/cms-dev/cms/blob/d700ad337dca4cd4f261a11c97ac60437c9dfa26/cmstestsuite/RunTimeTest.py#L75)):</sup>
This can be shared with `RunFunctionalTests.py`.


---

<sup>**[cmstestsuite/tasks/batch_100/__init__.py, line 92 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/485#-K3JufhIsCDyaW7Ot-81)** ([raw file](https://github.com/cms-dev/cms/blob/d700ad337dca4cd4f261a11c97ac60437c9dfa26/cmstestsuite/tasks/batch_100/__init__.py#L92)):</sup>
Why are they commented starting from here?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/485)

**Comment by giomasce** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/485)

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[cmstestsuite/RunTimeTest.py, line 75 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/485#-K3JwQysVQQHg8T5vJfs:-K3Oz58bmRSPOzLCbMSy:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/d700ad337dca4cd4f261a11c97ac60437c9dfa26/cmstestsuite/RunTimeTest.py#L75)):_
Done.

---

_[cmstestsuite/tasks/batch_100/__init__.py, line 92 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/485#-K3JufhIsCDyaW7Ot-81:-K3Oz6F8PNAJcXtMCGgO:-1125802126) ([raw file](https://github.com/cms-dev/cms/blob/d700ad337dca4cd4f261a11c97ac60437c9dfa26/cmstestsuite/tasks/batch_100/__init__.py#L92)):_
Forgot them. On the other hand, I decided that 50 is probably enough (it is easier to change the length of the test by increasing the number of submissions). So I changed it to 50 testcases, and added command line options to change the number of submissions.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/485)_

**Comment by stefano-maggiolo** [comment]
9ae04dce8fd7b56381be089f58b89c6afda6a8ed
b8a4c798af6c2d197bea72b85ae923c2dc65b7f1
a443211a1ee0d9fcc06ac33ddd2309d056427e4d
7178b9856b8eee9725bf37a1c8d0c173a5769457
e9f0990d411c5b4429dde776933bb67798fed455
8225afa1121087e551ad82cc830941b66cb98630
2ecf42d0b742ef0caf51f6594e5e0e1d2886fd72

**Pull request merged**
