### PR TITLE
CWS: use cmscommon.archive when suitable

### PR DESCRIPTION
**Pull request by wil93**

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Please fix these small issues and I'll merge.

**Comment by wil93** [comment]
Done :)

**Comment by stefano-maggiolo** [comment]
Merged: fdc9754b0cedc207f5d56f893f6bc89eb0cdd6f5
I just changed a couple of things:
- no action when unable to delete the temp file
- now we align pydoc comments with 4 indent

Thanks for deleting code!

**Comment by wil93** [comment]
> no action when unable to delete the temp file

I also considered raising a `logger.warning()`, but maybe it's not really necessary.

**Pull request closed without merging**
