### PR TITLE
Add support for bcrypt password encryption for users

### PR DESCRIPTION
**Pull request by valiro21**
In relation to issue #710, I managed to add support for encrypting user passwords with bcrypt. They are  kept in the database as either clear text or hash, depending on how the account is created.

Options added:
 * Ability for admins to select either text or bcrypt when creating an user account, updating an user account or a participation to a contest
 * Users can login with the password, be it clear text or hash
 * Added bcrypt option to hash password for ```cmsAddUser``` and ```cmsAddParticipation```
 * Password now have the format algo:password in the database. Any password that does not match this format will raise an exception

Example of encryption selection:
Example encryption select

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/711)

### CODE REVIEW

**Comment by karliss** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcPRBmr7WjGqHfDJ2PG:-KcPRBmsQpAlRPUZTGGu:bm4b3pb) (no related file):*
Editing participation sets the password to "None". To repeat:
1. create a contest
2. create user, set password to "p1", add participation to contest
3. try logging into CWS with password "p1" - works as it should
4. edit one of the participation fields for example for example mark participation hiddden and press update
5. try logging in with password "p1" it fails, but logging in with password "None" succeds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by valiro21** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcPRBmr7WjGqHfDJ2PG:-KcPaeLnIMxyfNxJW6kI:b-mkzik9) (no related file):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Editing participation sets the password to "None". To repeat:
1. create a contest
2. create user, set password to "p1", add participation to contest
3. try logging into CWS with password "p1" - works as it should
4. edit one of the participation fields for example for example mark participation hiddden and press update
5. try logging in with password "p1" it fails, but logging in with password "None" succeds
</blockquote></details>

Thanks for noticing!
I think it was happening because I didn't remove the "method" from participation arguments when editing participation. 
Also, I now replace the password with an empty string if it is None. Strangely enough I did remove it when updating users. 
I fixed it. Now I can't reproduce it anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by karliss** [comment]
Reviewed 1 of 2 files at r1, 6 of 10 files at r2.
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcPRBmr7WjGqHfDJ2PG:-Kc_7ylat5XG3nH7Km0G:b-6qsi3z) (no related file):*
<details><summary><i>Previously, valiro21 (Valentin Rosca) wrote…</i></summary><blockquote>

Thanks for noticing!
I think it was happening because I didn't remove the "method" from participation arguments when editing participation. 
Also, I now replace the password with an empty string if it is None. Strangely enough I did remove it when updating users. 
I fixed it. Now I can't reproduce it anymore.
</blockquote></details>

It still removes bcrypt passwords.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcZppm5llMXyTg0hjhD:-KcZppm6_qwFj7E4eZiB:b8btla1) (no related file):*
Is it really necessary to keep support for creating new users with plain text passwords? Keeping it increases the amount of code that needs to be maintained and encourages bad practices. 

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcZr1iMXnWzV1EALBkv:-KcZr1iNXnkitcu2QdfR:by30sw4) (no related file):*
Database changes probably require updating the dumpUpdater. Stefano could give the official policy for maintaining it.

---

*[cms/server/admin/templates/base.html, line 14 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_BlF70A4D7dROp_ch:-Kc_BlF70A4D7dROp_ci:b-9r1pk1) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cms/server/admin/templates/base.html#L14)):*
> ```HTML
>     <link rel="shortcut icon" href="{{ url_root }}/static/favicon.ico" />
>     <link rel="stylesheet" type="text/css" href="{{ url_root }}/static/reset.css">
>     <link rel="stylesheet" type="text/css" href="{{ url_root }}/static/css/bootstrap.min.css">
> ```

Why is this needed? I notice any changes in html templates that would require adding it.

---

*[cmscommon/crypto.py, line 175 at r1](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_8W7V1MNvj-aQmSdR:-Kc_8W7V1MNvj-aQmSdS:bf4rxd9) ([raw file](https://github.com/cms-dev/cms/blob/51e69afe45dfb14d9b396137c0c1f34d9877aec3/cmscommon/crypto.py#L175)):*
> ```Python
> 
> 
> def generate_random_password_with_method(method="text"):
> ```

Using any method other "text" is pointless.  there is no way of knowing what password was generated if it's returned already hashed. 

---

*[cmscontrib/AddParticipation.py, line 124 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_9ykz7-zPmregGJWH:-Kc_9ykz7-zPmregGJWI:b3wkdsm) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cmscontrib/AddParticipation.py#L124)):*
> ```Python
>                         help="if the participation is unrestricted")
>     parser.add_argument("-B", "--bcrypt", action="store_true",
>                         help="use bcrypt to encrypt participation password")
> ```

I suggest using bcrypt by default.

---

*[cmscontrib/AddUser.py, line 102 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_AJ8s4QKf53RIRFlV:-Kc_AJ8s4QKf53RIRFlW:b-upj6zw) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cmscontrib/AddUser.py#L102)):*
> ```Python
>     parser.add_argument("-l", "--languages", action="store", type=utf8_decoder,
>                         help="comma-separated list of preferred languages")
>     parser.add_argument("-B", "--bcrypt", action="store_true",
> ```

Same as in AddParticipation it would be nice to have good defaults.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by valiro21** [comment]
Review status: 7 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcZppm5llMXyTg0hjhD:-Kcb-XN9GNAkCaakbewL:be8gntj) (no related file):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Is it really necessary to keep support for creating new users with plain text passwords? Keeping it increases the amount of code that needs to be maintained and encourages bad practices. 
</blockquote></details>

For some users I think it is better to keep a clear text option. For example, we hosted a local contest for juniors and they forgot their passwords even through we made them fill in their own password. It was easier to just email them their current password than create a new one and sent that (the new one would have to be random and harder for them to remember). Also, when we host private contests and we need to generate the password ourselves, it's easier to see the password on AWS than to keep them in a separate document.

---

*[cms/server/admin/templates/base.html, line 14 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_BlF70A4D7dROp_ch:-Kcayvc5gyYqF0y7II3b:b-q87twf) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cms/server/admin/templates/base.html#L14)):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Why is this needed? I notice any changes in html templates that would require adding it.
</blockquote></details>

I had problems with an old PR for cms. It was #631. I rebased my branch after making the changes so this line remained here. Sry for that :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by valiro21** [comment]
Review status: 7 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmscommon/crypto.py, line 175 at r1](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_8W7V1MNvj-aQmSdR:-KcnS0dyDZ6HpMjdlmCU:b-qecvxa) ([raw file](https://github.com/cms-dev/cms/blob/51e69afe45dfb14d9b396137c0c1f34d9877aec3/cmscommon/crypto.py#L175)):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Using any method other "text" is pointless.  there is no way of knowing what password was generated if it's returned already hashed. 
</blockquote></details>

You are right, this should be removed. I will remove it in the next commit.

---

*[cmscontrib/AddParticipation.py, line 124 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_9ykz7-zPmregGJWH:-KcnVhQwQ9-QSa1OgbZV:blz2arc) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cmscontrib/AddParticipation.py#L124)):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

I suggest using bcrypt by default.
</blockquote></details>

I thought that defaults should be preserved until people get used to it.

---

*[cmscontrib/AddUser.py, line 102 at r3](https://reviewable.io:443/reviews/cms-dev/cms/711#-Kc_AJ8s4QKf53RIRFlV:-KcnYaT9EqNt0S7DCOqc:bijbzsz) ([raw file](https://github.com/cms-dev/cms/blob/ef2d8520d1756c39179fb34176dce02f23813dcd/cmscontrib/AddUser.py#L102)):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

Same as in AddParticipation it would be nice to have good defaults.
</blockquote></details>

Same as in AddUser, preserving defaults.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by valiro21** [comment]
Review status: 5 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cms-dev/cms/711#-KcPRBmr7WjGqHfDJ2PG:-KcnjipC-gAvndDIqe3Y:b-ygfdep) (no related file):*
<details><summary><i>Previously, karliss wrote…</i></summary><blockquote>

It still removes bcrypt passwords.
</blockquote></details>

Sry :(. I fixed it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/711)*

**Comment by lerks** [comment]
Hi! Thanks for your contribution! Sorry it took us a while to get to it, we had quite a backlog. I rebased it on the current master, cleaned it and fixed it in #747. Review will continue there.

A few tips for next time:
* When you want to update your branch to a more recent master don't use merge commits: rebase it, as it results in a cleaner and easier to handle history.
* Check previous commits that do similar things to yours to see what needs to be done (here, for example, you didn't provide an updater).
* Test extensively and use the testsuite to help you in that (there were several bugs, mostly in the UI).

**Pull request closed without merging**
