### PR TITLE
Use Babel for common formatting tasks rather than home-made solution

### PR DESCRIPTION
**Pull request by lerks**
Babel provides access to the Common Locale Data Repository (CLDR) which
provides functions to perform many common formatting operations: dates,
times, numbers, lists, units, ...

Use those instead of our own "in-house" approaches.

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/838)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cms/server/contest/formatting.py, line 33 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L55tloOXOONr-PcE5xI-r1-33:-L59FKwM451DjwUgGlXK:bqlsr7o) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L33)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary><blockquote>

Codacy Issue found: [Unused timedelta imported from datetime](https://app.codacy.com/app/s-maggiolo/cms/pullRequest?prid=1324777)
</blockquote></details>

Please fix

---

*[cms/server/contest/formatting.py, line 102 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59FznrIt9VehRGTzAn:-L59FznrIt9VehRGTzAo:b-489nz9) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L102)):*
> ```Python
> 
> 
> def format_timedelta(td, translation=DEFAULT_TRANSLATION):
> ```

This file is ready to have some tests :)

---

*[cms/server/contest/formatting.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59GIRi222-eGszFsI4:-L59GIRi222-eGszFsI5:b-ctm0gu) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L148)):*
> ```Python
> 
> 
> def format_duration(d, length="short", translation=DEFAULT_TRANSLATION):
> ```

Move close to format timedelta? Also would be nice to have some examples in the docstrings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838)*

**Comment by lerks** [comment]
PTAL

---

Review status: 28 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/server/contest/formatting.py, line 33 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L55tloOXOONr-PcE5xI-r1-33:-L59J1Ed46ASG2auY84Z:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L33)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Please fix
</blockquote></details>

Done.

---

*[cms/server/contest/formatting.py, line 102 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59FznrIt9VehRGTzAn:-L59J5CgNVobf1ghmFMs:bqm34i3) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L102)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

This file is ready to have some tests :)
</blockquote></details>

Ack :)

---

*[cms/server/contest/formatting.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59GIRi222-eGszFsI4:-L59J72Qict3HjRbp2mQ:bvnsrlu) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L148)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Move close to format timedelta? Also would be nice to have some examples in the docstrings
</blockquote></details>

Done. I also wanted it to stay close to format_size (since they are the two methods used to format evaluation metrics: time and memory).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838#-:-L59JJMZamjWz_MtzpXA:bb71pro)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r2, 8 of 9 files at r3.
Review status: 34 of 35 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cms/server/contest/formatting.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59GIRi222-eGszFsI4:-L5Auii1Fl60hbIUQgIo:bm1bxte) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L148)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Done. I also wanted it to stay close to format_size (since they are the two methods used to format evaluation metrics: time and memory).
</blockquote></details>

What about the example(s)?

---

*[cms/server/contest/formatting.py, line 77 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AvZl1gUkQ34ra_lQu:-L5AvZl205BPgOCtCTnR:b-ug1knx) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cms/server/contest/formatting.py#L77)):*
> ```Python
> 
> 
> def format_datetime_smart(dt, now, timezone, translation=DEFAULT_TRANSLATION):
> ```

Missing docstring for this.

---

*[cms/server/contest/formatting.py, line 149 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5Av5ZYfw14admnEwq4:-L5Av5ZYfw14admnEwq5:blvb7qj) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cms/server/contest/formatting.py#L149)):*
> ```Python
>     if d < 0.001:
>         return translation.format_unit(d, "duration-second",
>                                        length=length, format="#")
> ```

IIUC this prints 0 instead of 0.000? Isn't the latter better, as it express precision of the measurement? (Alternatively: shouldn't 1.0001 be treated similarly?)

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 48 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AwSE-IPS0khoniY8h:-L5AwSE066jrwgUN97Id:b-mm3cpe) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L48)):*
> ```Python
> HINDI = Translation("hi")
> ITALIAN = Translation("it")
> NORWEGIAN = Translation("no")
> ```

zh_TW instead?

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 51 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5Awev3TTZzSfMiyD4a:-L5Awev3TTZzSfMiyD4b:bn7ctlv) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L51)):*
> ```Python
> 
> 
> class TestCWSFormatting(unittest.TestCase):
> ```

Optional style: I'd do a class for each method and split the methods to test individual behaviours.

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 311 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AxgN0mIeSZfr8m6o0:-L5AxgN0mIeSZfr8m6o1:b-mxx19) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L311)):*
> ```Python
>                          "1 byte")
>         # Cutoff is at 1000, not 1024, as we use kilo, mega, ... rather
>         # than kibi, mebi, ...
> ```

Uhm, we use MiB for the memory limit... should we make it uniform?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838)*

**Comment by stefano-maggiolo** [comment]
Also, tests are failing:
```
  File "overview_html.generated.py", line 583
    % {"start_time": format_datetime_smart(contest.start + current_user.delay_time, now, timezone, translation=translation),
                                                                                                                           ^
IndentationError: unindent does not match any outer indentation level
```

---

Reviewed 1 of 9 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838#-:-L5AyQjiAWSUZljYg1QN:b-fa0d6m)*

**Comment by lerks** [comment]
Done.

I also decided to move the formatting functions to methods of Translation objects, as they were using much more Babel internal machinery than I expected and I thus wanted to keep them closer to the rest of the Babel-using code.

PTAL.

---

Review status: 20 of 36 files reviewed at latest revision, 6 unresolved discussions.

---

*[cms/server/contest/formatting.py, line 148 at r1](https://reviewable.io:443/reviews/cms-dev/cms/838#-L59GIRi222-eGszFsI4:-L5Ytg9RzQR2dDLs7q_8:b24pbxj) ([raw file](https://github.com/cms-dev/cms/blob/d70825a2bb6fa59afa11c787428373b1882b2b25/cms/server/contest/formatting.py#L148)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

What about the example(s)?
</blockquote></details>

I improved the explanation in the docstring, which should leave no doubt as to how the result is formatted. I think that makes examples useless. I did the same for format_size and format_timedelta. (PS: examples are in the tests anyways).

---

*[cms/server/contest/formatting.py, line 77 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AvZl1gUkQ34ra_lQu:-L5ESiG7kO3CLJ2hi-im:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cms/server/contest/formatting.py#L77)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Missing docstring for this.
</blockquote></details>

Done.

---

*[cms/server/contest/formatting.py, line 149 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5Av5ZYfw14admnEwq4:-L5FG52q0wJ8CutvoYAL:b-vmquys) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cms/server/contest/formatting.py#L149)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

IIUC this prints 0 instead of 0.000? Isn't the latter better, as it express precision of the measurement? (Alternatively: shouldn't 1.0001 be treated similarly?)
</blockquote></details>

Changed the behavior.

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 48 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AwSE-IPS0khoniY8h:-L5FE2WJto35L_XtF_fU:b-d4va2x) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L48)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

zh_TW instead?
</blockquote></details>

Why? I wanted a language that used a symbol different than the colon to separate time elements. zh_TW appears to use colons. Also, I wanted to use a language with a 24h clock, and zh_TW uses a 12h clock. I added these motivations as comments.

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 51 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5Awev3TTZzSfMiyD4a:-L5FFmK5D4R9BfD89MKD:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L51)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Optional style: I'd do a class for each method and split the methods to test individual behaviours.
</blockquote></details>

Done.

---

*[cmstestsuite/unit_tests/server/contest/formatting.py, line 311 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AxgN0mIeSZfr8m6o0:-L5YvypKX6aRm8EQsQ78:b-8mxdjc) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/server/contest/formatting.py#L311)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

Uhm, we use MiB for the memory limit... should we make it uniform?
</blockquote></details>

Babel only provides kilo, mega, ... not kibi, mebi, ... I think I prefer the former (why should bytes have different prefixes than all SI units?). I think we could change from MiB to MB elsewhere (e.g. in memory limits), but the current situation is not too bad: if the limit is X MiB, then it's also at least X MB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838#-:-L5YwQoVYtaYbr2g-Y_G:b-lmxda9)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Review status: 20 of 36 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cms/locale/locale.py, line 242 at r5](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5_kKionk5Daf2H-8Ns:-L5_kKionk5Daf2H-8Nt:b-jiubqy) ([raw file](https://github.com/cms-dev/cms/blob/1211abf178b40596843de884d999578e8c626c2a/cms/locale/locale.py#L242)):*
> ```Python
>         f.frac_prec = (3, 3)
>         return babel.units.format_unit(d, "duration-second",
>                                        length=length, format=f, locale=self.locale)
> ```

This is going over 80 cols, check the rest of the file pls.

---

*[cmstestsuite/unit_tests/locale/locale.py, line 48 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5AwSE-IPS0khoniY8h:-L5_j-BkTpMYwkOOX9nY:b90vv6x) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/locale/locale.py#L48)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Why? I wanted a language that used a symbol different than the colon to separate time elements. zh_TW appears to use colons. Also, I wanted to use a language with a 24h clock, and zh_TW uses a 12h clock. I added these motivations as comments.
</blockquote></details>

Simply for handling a language code which is not [a-z]{2}, but maybe it's not really interesting here.

---

*[cmstestsuite/unit_tests/locale/locale.py, line 51 at r3](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5Awev3TTZzSfMiyD4a:-L5_jBYUV8RBjstrjZn6:btbh9po) ([raw file](https://github.com/cms-dev/cms/blob/22bf716d1ef8ee3e1dec4b1718f9366f25f0a9b6/cmstestsuite/unit_tests/locale/locale.py#L51)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks (I didn't mean to split *all* asserts in different methods, even if people say that's a good policy).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838#-:-L5_kbiZwkAnJBv3AQ6J:bnfp4nl)*

**Comment by lerks** [comment]
Review status: 20 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/locale/locale.py, line 242 at r5](https://reviewable.io:443/reviews/cms-dev/cms/838#-L5_kKionk5Daf2H-8Ns:-L5_xUKfK6pIfwpuZQUC:b2ca80p) ([raw file](https://github.com/cms-dev/cms/blob/1211abf178b40596843de884d999578e8c626c2a/cms/locale/locale.py#L242)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary><blockquote>

This is going over 80 cols, check the rest of the file pls.
</blockquote></details>

Fixed in later commit.

---

*[cms/server/contest/handlers/taskusertest.py, line 486 at r8](https://reviewable.io:443/reviews/cms-dev/cms/838#-L55tloOXOONr-PcE5xJ-r8-486:-L5_yV6cjluIrXb41AC3:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/3130c2aff50d950423385addcfd896da1c839a58/cms/server/contest/handlers/taskusertest.py#L486)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary><blockquote>

Codacy Issue found: [Line too long (82/80)](https://app.codacy.com/app/s-maggiolo/cms/pullRequest?prid=1324777)
</blockquote></details>

Done.

---

*[cms/server/contest/handlers/taskusertest.py, line 490 at r8](https://reviewable.io:443/reviews/cms-dev/cms/838#-L55tloOXOONr-PcE5xJ-r8-490:-L5_yVOJ-gpbdBGbmQrd:b-896fix) ([raw file](https://github.com/cms-dev/cms/blob/3130c2aff50d950423385addcfd896da1c839a58/cms/server/contest/handlers/taskusertest.py#L490)):*
<details><summary><i>Previously, codacy-bot (Codacy Bot) wrote…</i></summary><blockquote>

Codacy Issue found: [Line too long (82/80)](https://app.codacy.com/app/s-maggiolo/cms/pullRequest?prid=1324777)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/838)*

**Pull request merged**
