### PR TITLE
Fix travis testing; Add build badge to README.md

### PR DESCRIPTION
**Pull request by wil93**
Testing on travis now seems to work: https://travis-ci.org/wil93/cms/builds

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/611)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
This is great, thanks!

<details><summary><i>Previously, wil93 (William Di Luigi) wrote…</i></summary>
> #### Fix travis testing; Add build badge to README\.md
> 
> Testing on travis now seems to work: https://travis-ci.org/wil93/cms/builds
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 40 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/611#-KIatT4f9D8Pibzp7dYw:-KIatT4f9D8Pibzp7dYx:1985587232) ([raw file](https://github.com/cms-dev/cms/blob/07d3f306de7795e29e8a3cca002e735aedccf572/.travis.yml#L40)):*
> ```YAML
> 
>   - sudo chown root:$USER /usr/local/bin/isolate /usr/local/etc/cms.conf
>   - sudo chmod 777 /usr/local/bin/isolate /usr/local/etc/cms.conf
> ```

Why 777? 750 / 640 should be more realistic I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/611#-:-KIatw0xnQb4rVBjaQYd:-970016080)*

**Comment by wil93** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 40 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/611#-KIatT4f9D8Pibzp7dYw:-KIb-zWXCKujzcfwtnC4:1620594233) ([raw file](https://github.com/cms-dev/cms/blob/07d3f306de7795e29e8a3cca002e735aedccf572/.travis.yml#L40)):*
<details><summary><i>Previously, stefano-maggiolo (Stefano Maggiolo) wrote…</i></summary>
> Why 777? 750 / 640 should be more realistic I think.
</details>
I took that from travis.sh so I wouldn't know :stuck_out_tongue: Anyway I tried 640 and it stopped working, now I used 750 and it works. I also put back the "groups" command which I had removed (since there is a `ls -al` command, maybe it's worth to have both for debug reasons).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/611)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 40 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/611#-KIatT4f9D8Pibzp7dYw:-KIfz2gn3eamx3gz1kbq:1767763665) ([raw file](https://github.com/cms-dev/cms/blob/07d3f306de7795e29e8a3cca002e735aedccf572/.travis.yml#L40)):*
<details><summary><i>Previously, wil93 (William Di Luigi) wrote…</i></summary>
> I took that from travis.sh so I wouldn't know :stuck_out_tongue: Anyway I tried 640 and it stopped working, now I used 750 and it works. I also put back the "groups" command which I had removed (since there is a `ls -al` command, maybe it's worth to have both for debug reasons).
</details>
Yeah, I meant 750 for isolate and 640 for cms.conf. I'll tweak this before merging.

(And yes, groups and ls were there for debugging, since I wasn't able to make it work the first time. Honestly I submitted this by mistake.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/611)*

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/611)*

**Comment by wil93** [comment]
The button says "build: unknown", I think you need to enable testing on https://travis-ci.org/cms-dev/cms

**Comment by stefano-maggiolo** [comment]
It's just that it never triggered. Should do after the next push.

**Comment by stefano-maggiolo** [comment]
Oh, and thanks for making me realize this can be closed

**Pull request closed without merging**
