### PR TITLE
Update Latvian translation

### PR DESCRIPTION
**Pull request by andreyv**
CC @karliss

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/800)

### CODE REVIEW

**Comment by lerks** [comment]
Could you rebase and squash the four commits into one? Thanks!

**Comment by karliss** [comment]
Translation for "Official" submission looks suspicious. I can't think of better translation yet. All the names I can think of are long and mean the opposite.

**Comment by lerks** [comment]
@karliss I didn't understannd if you are OK with the translation proposed by @andreyv or if you would like some more time to propose a better one.

**Comment by andreyv** [comment]
This occurrence is quite hard to translate (would be much easier if it was "Unofficial" instead).

@karliss Do you like either of "Ieskaitīts" or "Pieņemts vērtēšanai"? There was also a suggestion "Sacensībās".

**Comment by karliss** [comment]
All three seem better than "Oficiāls".

**Comment by andreyv** [comment]
Updated the translation with "Ieskaitīts", it can be improved later if needed.

**Comment by andreyv** [comment]
This pull request should be good to merge now.

**Comment by stefano-maggiolo** [comment]
Thanks!

**Pull request closed without merging**
