### PR TITLE
Do not use 0 to mean no time/memory limit, and small code simplification

### LINKED ISSUE #849: Evaluation fails on tasks that have an unset memory limit
Leaving the memory limit unset means "no limit". Yet, at some point, some component (I think the sandbox) tries to convert the memory limit from megabytes (the unit it's stored in) to bytes (what isolate wants) and does it by just multiplying by 1024**2, without checking for non-None-ness. This fails.

### PR DESCRIPTION
**Pull request by stefano-maggiolo**
Full list of commits this one is part of: https://github.com/stefano-maggiolo/cms/commits/declutter_sandbox

Fixes #849

---
This change is [Reviewable](https://reviewable.io/reviews/cms-dev/cms/934)

### CODE REVIEW

**Comment by lerks** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cms/grading/__init__.py, line 395 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/934#-L9tfE4m6YN9dTlkmv4Q:-L9tfE4m6YN9dTlkmv4R:b-4n1rgb) ([raw file](https://github.com/cms-dev/cms/blob/e9d3ac8da672b8f6ee26059e0a1c2e9b029db122/cms/grading/__init__.py#L395)):*
> ```Python
>     commands ([[str]]): evaluation commands to execute.
>     time_limit (float|None): time limit in seconds (applied to each command);
>         if None or non-positive, no time limit is enforced.
> ```

maybe to be clearer and safer we should only have None mean "no limit" and raise an exception for non-negative values?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/934#-:-L9tfqdn7trb4ENxFd_e:bnfp4nl)*

**Comment by stefano-maggiolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cms/grading/__init__.py, line 395 at r1](https://beta.reviewable.io/reviews/cms-dev/cms/934#-L9tfE4m6YN9dTlkmv4Q:-L9u0dJl2b58Ms8QIjUe:bftu7qo) ([raw file](https://github.com/cms-dev/cms/blob/e9d3ac8da672b8f6ee26059e0a1c2e9b029db122/cms/grading/__init__.py#L395)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

maybe to be clearer and safer we should only have None mean "no limit" and raise an exception for non-negative values?
</blockquote></details>

Sounds reasonable. We could add a constraint in the db as well...

Edit: added constraints & updater

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/934)*

**Comment by lerks** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[cmscontrib/updaters/update_32.py, line 59 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/934#-L9uQDJm3ilf3Op42F2Z:-L9uQDJm3ilf3Op42F2_:be4jein) ([raw file](https://github.com/cms-dev/cms/blob/40e3e4414298d0d5ee6c97414e5397ccc0ec0aa4/cmscontrib/updaters/update_32.py#L59)):*
> ```Python
>                 # Zero explicitly meant no limits.
>                 if old_limit == 0.0:
>                     old_limit = None
> ```

you probably meant `v["time_limit"] = None` here (and same below)

---

*[cmscontrib/updaters/update_32.py, line 69 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/934#-L9uQW2fClwJf6wwIWMu:-L9uQW2fClwJf6wwIWMv:b-ps8b0c) ([raw file](https://github.com/cms-dev/cms/blob/40e3e4414298d0d5ee6c97414e5397ccc0ec0aa4/cmscontrib/updaters/update_32.py#L69)):*
> ```Python
>                 old_limit = v["memory_limit"]
>                 # Zero explicitly meant no limits.
>                 if old_limit == 0.0:
> ```

nit: value is int, so compare to `0` (not `0.0`)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/934)*

**Comment by stefano-maggiolo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmscontrib/updaters/update_32.py, line 59 at r2](https://beta.reviewable.io/reviews/cms-dev/cms/934#-L9uQDJm3ilf3Op42F2Z:-L9uVR4b6XpTRaI2GgQR:b-nbsupv) ([raw file](https://github.com/cms-dev/cms/blob/40e3e4414298d0d5ee6c97414e5397ccc0ec0aa4/cmscontrib/updaters/update_32.py#L59)):*
<details><summary><i>Previously, lerks (Luca Wehrstedt) wrote…</i></summary><blockquote>

you probably meant `v["time_limit"] = None` here (and same below)
</blockquote></details>

Yeah, sorry I was fixing the failure while you were reviewing, so I did it in a different way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/934)*

**Comment by lerks** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cms-dev/cms/934)*

**Comment by stefano-maggiolo** [comment]
Merged.

**Pull request closed without merging**
