### PR TITLE
Add support for multiple-Communication tasks.

### PR DESCRIPTION
**Pull request by qnighy**
We (Japanese OI committee) have used this kind of patch to provide tasks like:

> Contestants have to submit two programs. During judgement, functions in these programs
> are called in arbitrary order from the manager, and these functions can do something specified
> in the task statement. Therefore execution goes back and forth between two programs.

Actually there is such a task: [JOI2013 spring day4: manager](http://joisc2013-day4.contest.atcoder.jp/tasks/joisc2013_messenger). (Sorry, the task statement is in Japanese and not translated)

We can reuse the ``Communication`` tasktype to do this. This patch includes two extensions to ``Communication``.

1. Extension to the compilation phase: allow arbitrary submission formats. Although multiple submission files are used in earlier IOI tasks (e.g. ``encoder.cpp`` and ``decoder.cpp``), this is orthogonal to evaluation phase, since we get only one executable.
2. Extension to the evaluation phase: execute multiple subprocesses. Multiple FIFOs are given to the manager. An index is given to each user process.

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/575)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
This seems a sensible extension. We need to change the documentation too, though, as it is very non-obvious. Do you want to do it? 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/grading/tasktypes/Communication.py, line 89 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgTSxxagdwnkseDrqN:-KCgTSxxagdwnkseDrqO:-49539038) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L89)):*
Would it make sense to have this:
```python
"_".join(pattern[0].replace(".%l", "")
         for pattern in submission_format)
``` 

I don't particularly like "user_program", probably best would be the task name, but we don't have it here...

---

*[cms/grading/tasktypes/Communication.py, line 126 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgTHnpRdTpyGHqOy3o:-KCgTHnpRdTpyGHqOy3p:745997834) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L126)):*
Fits on previous line?

---

*[cms/grading/tasktypes/Communication.py, line 191 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgUS6yaQT3rW0wgrpq:-KCgUS6zY6TH8xvAqNpF:-586880028) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L191)):*
```
"in%d" % i
```

also one line later

---

*[cms/grading/tasktypes/Communication.py, line 237 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgV0SgJ1tJ-BJLYoHV:-KCgV0SgJ1tJ-BJLYoHW:-426877021) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L237)):*
Nit: processes

---

*[cms/grading/tasktypes/Communication.py, line 264 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgVEPTvkZ5bHZSRpeI:-KCgVEPTvkZ5bHZSRpeJ:-1126599872) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L264)):*
Nit: full sentences :) 
"Merge results."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KCgM_911N_oSmk2J-CW:-1039933262)*

**Comment by qnighy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cms/grading/tasktypes/Communication.py, line 126 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgTHnpRdTpyGHqOy3o:-KCiytw-erJKCwzYegPc:-1741357841) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L126)):*
What do you mean? BTW I noticed these lines in the patch are not related to the main issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575)*

**Comment by qnighy** [comment]
A self-comment on this patch: there is a little problem with compatibility. When the patch is applied, the ``num_processes`` configs for old Communication problems are set to ``None``. One is forced to change them to ``1`` before applying another change to these datasets. We might need default values.

**Comment by stefano-maggiolo** [comment]
We can have an updater to change all parameters for tasks of type communication. So there's that, documentation, and the last comment I left open here (about that line wrapped).

PS: I think you forgot to click on publish after answering the comments?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cms/grading/tasktypes/Communication.py, line 126 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgTHnpRdTpyGHqOy3o:-KCjNyT-aHYgr-LQB0Ws:1486035277) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L126)):*
I mean it looks like this statement now fits 80 columns without line breaks, since  you changed the indexes to something shorted

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KCjOS8xZTHm_mY5p_ol:1074272616)*

**Comment by stefano-maggiolo** [comment]
As you mentioned the parameters changed, so you need to update something on the tests side too: https://cms.di.unipi.it/jenkins/job/cms.cms-dev.pr575/2/console

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KCl-eKgJvoTUxRl7ugV:20351172)*

**Comment by qnighy** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[cms/grading/tasktypes/Communication.py, line 191 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgUS6yaQT3rW0wgrpq:-KCp23XuQIrQoLMzI8zU:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L191)):*
Done.

---

*[cms/grading/tasktypes/Communication.py, line 237 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/575#-KCgV0SgJ1tJ-BJLYoHV:-KCp26ba1rTx07pRGleo:-499146009) ([raw file](https://github.com/cms-dev/cms/blob/acf926053be3a342f4bfac5f5038f2d1a9402d60/cms/grading/tasktypes/Communication.py#L237)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575)*

**Comment by qnighy** [comment]
- [x] DB updater
- [x] ``italy_yaml`` importer
- [x] wrapped line
- [x] functional test
- [ ] documentation

---

Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KCpd-sJz_1L-AWP6TRY:1557834018)*

**Comment by qnighy** [comment]
@wafrelka pointed out that we should modify execution time checking.

**Comment by qnighy** [comment]
I also added the tests for multiple-Communication.

**Comment by stefano-maggiolo** [comment]
Thank you for all the work, especially tests and documentation!

---

Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 30 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 3 of 4 files at r14, 24 of 24 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KF07MHc5sE2DhmIJvKd:1760859272)*

**Comment by stefano-maggiolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 30 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 3 of 4 files at r14, 24 of 24 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/575#-:-KF3JGTLYFtXuHoU-mtU:1417088721)*

**Comment by stefano-maggiolo** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 30 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 3 of 4 files at r14, 24 of 24 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cms-dev/cms/575)*

**Comment by stefano-maggiolo** [comment]
Merged, thank you!

**Pull request closed without merging**
