### PR TITLE
Add cmsAddTask --contest-id flag, for simplicity

### PR DESCRIPTION
**Pull request by wil93**
This is useful to avoid having to "tie" a new task to an existing contest

[Review on Reviewable](https://reviewable.io/reviews/cms-dev/cms/489)

### CODE REVIEW

**Comment by stefano-maggiolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[cmscontrib/AddTask.py, line 47 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aj04kCykAXOK2qDnj)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L47)):</sup>
Alphabetically please (I know it is not always enforced, but we try).


---

<sup>**[cmscontrib/AddTask.py, line 144 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aimTOjNne-Sckxkwr)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L144)):</sup>
I would call this simply "-c", "--contest-id".


---

<sup>**[cmscontrib/AddTask.py, line 145 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aiSG-NzMq0w16PKwc)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L145)):</sup>
Another option would be to have a default value and make this a nargs='?', so that you could ask interactively if no argument is passed. On the other hand, I believe that doesn't play well with having the arg not in the final position... since you are using this feature, feel free to decide how it is more comfortable.


---

<sup>**[cmscontrib/AddTask.py, line 146 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1ahPDm3hjbAcJmG1uR)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L146)):</sup>
"id of the contest that will contain the task" / "id of the contest the task will be attached to" / ...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Comment by wil93** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[cmscontrib/AddTask.py, line 47 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aj04kCykAXOK2qDnj)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L47)):</sup>
Done. 


---

<sup>**[cmscontrib/AddTask.py, line 144 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aimTOjNne-Sckxkwr)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L144)):</sup>
Done.


---

<sup>**[cmscontrib/AddTask.py, line 145 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1aiSG-NzMq0w16PKwc)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L145)):</sup>
I think that in most cases the task will not be attached (or at least not immediately) so it's ok not to ask interactively.


---

<sup>**[cmscontrib/AddTask.py, line 146 \[r1\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K1ahPDm3hjbAcJmG1uR)** ([raw file](https://github.com/cms-dev/cms/blob/4e57e16124eebdceb0511e47db7b1ad851b42589/cmscontrib/AddTask.py#L146)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Comment by stefano-maggiolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[cmscontrib/AddTask.py, line 116 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K2y93P2uDsiIWMLUz6z)** ([raw file](https://github.com/cms-dev/cms/blob/266525540f9d9025ebd2e843e81de2dcf2b75261/cmscontrib/AddTask.py#L116)):</sup>
I'm merging this after I edit this to stay in one line.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Comment by stefano-maggiolo** [comment]
Merged in 9fcb6d5556e41cc409e053213b4970acaa95ab6a

**Comment by wil93** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[cmscontrib/AddTask.py, line 116 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K2y93P2uDsiIWMLUz6z)** ([raw file](https://github.com/cms-dev/cms/blob/266525540f9d9025ebd2e843e81de2dcf2b75261/cmscontrib/AddTask.py#L116)):</sup>
That was the output I received from yapf :stuck_out_tongue: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Comment by stefano-maggiolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[cmscontrib/AddTask.py, line 116 \[r2\]](https://reviewable.io:443/reviews/cms-dev/cms/489#-K2y93P2uDsiIWMLUz6z)** ([raw file](https://github.com/cms-dev/cms/blob/266525540f9d9025ebd2e843e81de2dcf2b75261/cmscontrib/AddTask.py#L116)):</sup>
File a bug!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cms-dev/cms/489)

**Pull request closed without merging**
